# Copyright (c) 2001, Stanford University
# All rights reserved.
#
# See the file LICENSE.txt for information on redistributing this software.

TOP = ../..

PROGRAM = quitms
FILES = quit

LIBRARIES = crmothership crutil

include $(TOP)/cr.mk
