# Copyright (c) 2001, Stanford University
# All rights reserved.
#
# See the file LICENSE.txt for information on redistributing this software.

TOP = ..

LIBRARY = crapp
SHARED = 1

FILES = appstub

include ${TOP}/cr.mk

LIB_DEFS = appstub.def
