# Written by Dale Beermann (beermann@cs.virginia.edu)


TOP = ..

include $(TOP)/arch.mk

FILES = crutapi
SHARED = 1
LIBRARY = crutapi
LIB_DEFS = crutapi.def
LIBRARIES = crmothership crutil

include $(TOP)/cr.mk
