# Copyright (c) 2001, Stanford University
# All rights reserved.
#
# See the file LICENSE.txt for information on redistributing this software.

TOP = ../../..

PROGRAM = NV_fog_distance
OPENGL = 1
GLUT = 1

LIBRARIES = crutil crextensionscommon

FILES = main

include ${TOP}/cr.mk
