# Copyright (c) 2001, Stanford University
# All rights reserved.
#
# See the file LICENSE.txt for information on redistributing this software.

TOP = ../..

PROGRAM = city
FILES = city
GLUT = 1
MATH = 1

include $(TOP)/cr.mk
