# Copyright (c) 2001, Stanford University
# All rights reserved.
#
# See the file LICENSE.txt for information on redistributing this software.


import sys,os;
import cPickle;
import string;
import re;

sys.path.append( "../opengl_stub" )
parsed_file = open( "../glapi_parser/gl_header.parsed", "rb" )
gl_mapping = cPickle.load( parsed_file )

import stub_common;

stub_common.CopyrightDef()

print """DESCRIPTION ""
EXPORTS
"""

keys = gl_mapping.keys()
keys.sort();

for func_name in stub_common.AllSpecials( 'state' ):
	print "crState%s" % func_name

print """crStateInit
crStateCreateContext
crStateDestroyContext
crStateDiffContext
crStateSwitchContext
crStateMakeCurrent
crStateSetCurrent
crStateFlushFunc
crStateFlushArg
crStateDiffAPI
crStateSetCurrentPointers
crStateCurrentRecover
crStateTransformUpdateTransform
crStateColorMaterialRecover
crStateError
crStateUpdateColorBits
crStateClientInit
crStateGetCurrent
crStateLimitsInit
crStateMergeExtensions
__currentBits
crStateFeedbackVertex2d
crStateFeedbackVertex2dv
crStateFeedbackVertex2f
crStateFeedbackVertex2fv
crStateFeedbackVertex2i
crStateFeedbackVertex2iv
crStateFeedbackVertex2s
crStateFeedbackVertex2sv
crStateFeedbackVertex3d
crStateFeedbackVertex3dv
crStateFeedbackVertex3f
crStateFeedbackVertex3fv
crStateFeedbackVertex3i
crStateFeedbackVertex3iv
crStateFeedbackVertex3s
crStateFeedbackVertex3sv
crStateFeedbackVertex4d
crStateFeedbackVertex4dv
crStateFeedbackVertex4f
crStateFeedbackVertex4fv
crStateFeedbackVertex4i
crStateFeedbackVertex4iv
crStateFeedbackVertex4s
crStateFeedbackVertex4sv
crStateSelectVertex2d
crStateSelectVertex2dv
crStateSelectVertex2f
crStateSelectVertex2fv
crStateSelectVertex2i
crStateSelectVertex2iv
crStateSelectVertex2s
crStateSelectVertex2sv
crStateSelectVertex3d
crStateSelectVertex3dv
crStateSelectVertex3f
crStateSelectVertex3fv
crStateSelectVertex3i
crStateSelectVertex3iv
crStateSelectVertex3s
crStateSelectVertex3sv
crStateSelectVertex4d
crStateSelectVertex4dv
crStateSelectVertex4f
crStateSelectVertex4fv
crStateSelectVertex4i
crStateSelectVertex4iv
crStateSelectVertex4s
crStateSelectVertex4sv
crStateSelectRasterPos2d
crStateSelectRasterPos2dv
crStateSelectRasterPos2f
crStateSelectRasterPos2fv
crStateSelectRasterPos2i
crStateSelectRasterPos2iv
crStateSelectRasterPos2s
crStateSelectRasterPos2sv
crStateSelectRasterPos3d
crStateSelectRasterPos3dv
crStateSelectRasterPos3f
crStateSelectRasterPos3fv
crStateSelectRasterPos3i
crStateSelectRasterPos3iv
crStateSelectRasterPos3s
crStateSelectRasterPos3sv
crStateSelectRasterPos4d
crStateSelectRasterPos4dv
crStateSelectRasterPos4f
crStateSelectRasterPos4fv
crStateSelectRasterPos4i
crStateSelectRasterPos4iv
crStateSelectRasterPos4s
crStateSelectRasterPos4sv
crStateFeedbackRasterPos2d
crStateFeedbackRasterPos2dv
crStateFeedbackRasterPos2f
crStateFeedbackRasterPos2fv
crStateFeedbackRasterPos2i
crStateFeedbackRasterPos2iv
crStateFeedbackRasterPos2s
crStateFeedbackRasterPos2sv
crStateFeedbackRasterPos3d
crStateFeedbackRasterPos3dv
crStateFeedbackRasterPos3f
crStateFeedbackRasterPos3fv
crStateFeedbackRasterPos3i
crStateFeedbackRasterPos3iv
crStateFeedbackRasterPos3s
crStateFeedbackRasterPos3sv
crStateFeedbackRasterPos4d
crStateFeedbackRasterPos4dv
crStateFeedbackRasterPos4f
crStateFeedbackRasterPos4fv
crStateFeedbackRasterPos4i
crStateFeedbackRasterPos4iv
crStateFeedbackRasterPos4s
crStateFeedbackRasterPos4sv
crStateFeedbackTexCoord1d
crStateFeedbackTexCoord1dv
crStateFeedbackTexCoord1f
crStateFeedbackTexCoord1fv
crStateFeedbackTexCoord1i
crStateFeedbackTexCoord1iv
crStateFeedbackTexCoord1s
crStateFeedbackTexCoord1sv
crStateFeedbackTexCoord2d
crStateFeedbackTexCoord2dv
crStateFeedbackTexCoord2f
crStateFeedbackTexCoord2fv
crStateFeedbackTexCoord2i
crStateFeedbackTexCoord2iv
crStateFeedbackTexCoord2s
crStateFeedbackTexCoord2sv
crStateFeedbackTexCoord3d
crStateFeedbackTexCoord3dv
crStateFeedbackTexCoord3f
crStateFeedbackTexCoord3fv
crStateFeedbackTexCoord3i
crStateFeedbackTexCoord3iv
crStateFeedbackTexCoord3s
crStateFeedbackTexCoord3sv
crStateFeedbackTexCoord4d
crStateFeedbackTexCoord4dv
crStateFeedbackTexCoord4f
crStateFeedbackTexCoord4fv
crStateFeedbackTexCoord4i
crStateFeedbackTexCoord4iv
crStateFeedbackTexCoord4s
crStateFeedbackTexCoord4sv
crStateFeedbackBegin
crStateFeedbackEnd
crStateFeedbackBitmap
crStateFeedbackCopyPixels
crStateFeedbackDrawPixels
crStateFeedbackGetBooleanv
crStateFeedbackGetDoublev
crStateFeedbackGetFloatv
crStateFeedbackGetIntegerv
"""
