# Copyright (c) 2001, Stanford University
# All rights reserved.
#
# See the file LICENSE.txt for information on redistributing this software.

TOP = ../..

PROGRAM = packperf
FILES = packperf

LIBRARIES = crpacker crutil

include ${TOP}/cr.mk
