# Copyright (c) 2001, Stanford University
# All rights reserved.
#
# See the file LICENSE.txt for information on redistributing this software.

TOP = ../../..

PROGRAM = plybbox
FILES = ../plyfile bbox
LIBRARIES = crutil

CFLAGS += -I..

include ${TOP}/cr.mk
