# Copyright (c) 2001, Stanford University
# All rights reserved.
#
# See the file LICENSE.txt for information on redistributing this software.

TOP = ../..

PROGRAM = tiletest
OPENGL = 1
GLUT = 1

FILES = tiletest

include ${TOP}/cr.mk
