# Copyright (c) 2001, Stanford University
# All rights reserved.
#
# See the file LICENSE.txt for information on redistributing this software.

TOP = ../..

PROGRAM = psubmit
FILES = psubmit
MATH = 1

LIBRARIES = crutil crfaker

include ${TOP}/cr.mk
