# Copyright (c) 2001, Stanford University
# All rights reserved.
#
# See the file LICENSE.txt for information on redistributing this software.


import sys;
import cPickle;
import types;
import string;
import re;

import stub_common;

parsed_file = open( "../glapi_parser/gl_header.parsed", "rb" )
gl_mapping = cPickle.load( parsed_file )

keys = gl_mapping.keys()
keys.sort();

stub_common.CopyrightC()

print """
/* DO NOT EDIT - THIS FILE GENERATED BY THE NULLfuncs.py SCRIPT */

#include "stub.h"
"""

for func_name in keys:
	( return_type, arg_names, arg_types ) = gl_mapping[func_name]

	print "static %s SPULOAD_APIENTRY NULL_%s%s" % (return_type, func_name, stub_common.ArgumentString( arg_names, arg_types ) )
	print "{"
	print "\t/* do nothing */"
	for vars in arg_names:
		if len(vars) > 0:
			print "\t(void) %s;" % vars
	if return_type != "void":
		print "\treturn 0;"
	print "}"
	print ""


print "SPUDispatchTable stubNULLDispatch = {"

for func_name in keys:
	( return_type, arg_names, arg_types ) = gl_mapping[func_name]

	print "\tNULL_%s," % (func_name)

print "};"
