/* Copyright (c) 2001, Stanford University
	All rights reserved.

	See the file LICENSE.txt for information on redistributing this software. */
	

/* DO NOT EDIT - THIS FILE GENERATED BY THE glloader.py SCRIPT */
#include "cr_error.h"
#include "cr_dll.h"
#include "cr_spu.h"
#include "cr_string.h"
#include "cr_error.h"
#include "cr_environment.h"


#if defined(WINDOWS)
#define SYSTEM_GL "opengl32.dll"
#elif defined(IRIX) || defined(IRIX64) || defined(Linux) || defined(FreeBSD) || defined(__APPLE__)
#define SYSTEM_GL "libGL.so"
typedef void (*glxfuncptr)();
extern glxfuncptr glxGetProcAddressARB( const GLubyte *name );
#else
#error I don't know where your system's GL lives.  Too bad.
#endif

static CRDLL *glDll = NULL;


static int
__fillin( SPUNamedFunctionTable *entry, const char *funcName, SPUGenericFunction funcPtr )
{
	if (funcPtr) {
		entry->name = crStrdup( funcName );
		entry->fn = funcPtr;
		return 1;
	}
	return 0;
}


#define FILLIN( funcName, funcPtr ) \
	if (__fillin(entry, funcName, funcPtr)) \
		entry++;

#define FILLIN_OPT( funcName, funcPtr, nopName ) \
	f = funcPtr; \
	if (!f) \
		f = nopName; \
	(void) __fillin(entry, funcName, f); \
	entry++;


static CRDLL *
__findSystemGL( char *provided_system_path )
{
	CRDLL *dll;
	char system_path[8096];
	if (provided_system_path)
	{
		crStrcpy( system_path, provided_system_path );
	}
	else
	{
#if defined(WINDOWS)
		GetSystemDirectory(system_path, MAX_PATH);
#elif defined(IRIX) || defined(IRIX64)
		crStrcpy( system_path, "/usr/lib32" );
#else
		crStrcpy( system_path, "/usr/lib" ); 
#endif
	}
	crStrcat( system_path, "/" );
	crStrcat( system_path, SYSTEM_GL );
	dll = crDLLOpen( system_path );
	return dll;
}

static SPUGenericFunction
__findExtFunction( const crOpenGLInterface *interface, const char *funcName )
{
#ifdef WINDOWS
	if (interface->wglGetProcAddress)
		return (SPUGenericFunction) interface->wglGetProcAddress( funcName );
	else
		return (SPUGenericFunction) NULL;
#else
	/* XXX for some reason, the NVIDIA glXGetProcAddressARB() function
	 * returns pointers that cause Chromium to crash.  If we use the
	 * pointer returned by crDLLGetNoError() instead, we're OK.
	 */
	SPUGenericFunction f = crDLLGetNoError(glDll, funcName);
	if (f)
		return f;
	else if (interface->glXGetProcAddressARB)
		return interface->glXGetProcAddressARB( funcName );
	else
		return NULL;
#endif
}

static void NopActiveTextureARB( GLenum texture )
{
	(void) texture;
}

static void NopBlendColorEXT( GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha )
{
	(void) red;
	(void) green;
	(void) blue;
	(void) alpha;
}

static void NopBlendEquationEXT( GLenum mode )
{
	(void) mode;
}

static void NopClientActiveTextureARB( GLenum texture )
{
	(void) texture;
}

static void NopCombinerInputNV( GLenum stage, GLenum portion, GLenum variable, GLenum input, GLenum mapping, GLenum componentUsage )
{
	(void) stage;
	(void) portion;
	(void) variable;
	(void) input;
	(void) mapping;
	(void) componentUsage;
}

static void NopCombinerOutputNV( GLenum stage, GLenum portion, GLenum abOutput, GLenum cdOutput, GLenum sumOutput, GLenum scale, GLenum bias, GLboolean abDotProduct, GLboolean cdDotProduct, GLboolean muxSum )
{
	(void) stage;
	(void) portion;
	(void) abOutput;
	(void) cdOutput;
	(void) sumOutput;
	(void) scale;
	(void) bias;
	(void) abDotProduct;
	(void) cdDotProduct;
	(void) muxSum;
}

static void NopCombinerParameterfNV( GLenum pname, GLfloat param )
{
	(void) pname;
	(void) param;
}

static void NopCombinerParameterfvNV( GLenum pname, const GLfloat *params )
{
	(void) pname;
	(void) params;
}

static void NopCombinerParameteriNV( GLenum pname, GLint param )
{
	(void) pname;
	(void) param;
}

static void NopCombinerParameterivNV( GLenum pname, const GLint *params )
{
	(void) pname;
	(void) params;
}

static void NopCombinerStageParameterfvNV( GLenum stage, GLenum pname, const GLfloat *params )
{
	(void) stage;
	(void) pname;
	(void) params;
}

static void NopFinalCombinerInputNV( GLenum variable, GLenum input, GLenum mapping, GLenum componentUsage )
{
	(void) variable;
	(void) input;
	(void) mapping;
	(void) componentUsage;
}

static void NopGetCombinerStageParameterfvNV( GLenum stage, GLenum pname, GLfloat *params )
{
	(void) stage;
	(void) pname;
	(void) params;
}

static void NopMultiTexCoord1dARB( GLenum texture, GLdouble s )
{
	(void) texture;
	(void) s;
}

static void NopMultiTexCoord1dvARB( GLenum texture, const GLdouble *t )
{
	(void) texture;
	(void) t;
}

static void NopMultiTexCoord1fARB( GLenum texture, GLfloat s )
{
	(void) texture;
	(void) s;
}

static void NopMultiTexCoord1fvARB( GLenum texture, const GLfloat *t )
{
	(void) texture;
	(void) t;
}

static void NopMultiTexCoord1iARB( GLenum texture, GLint s )
{
	(void) texture;
	(void) s;
}

static void NopMultiTexCoord1ivARB( GLenum texture, const GLint *t )
{
	(void) texture;
	(void) t;
}

static void NopMultiTexCoord1sARB( GLenum texture, GLshort s )
{
	(void) texture;
	(void) s;
}

static void NopMultiTexCoord1svARB( GLenum texture, const GLshort *t )
{
	(void) texture;
	(void) t;
}

static void NopMultiTexCoord2dARB( GLenum texture, GLdouble s, GLdouble t )
{
	(void) texture;
	(void) s;
	(void) t;
}

static void NopMultiTexCoord2dvARB( GLenum texture, const GLdouble *t )
{
	(void) texture;
	(void) t;
}

static void NopMultiTexCoord2fARB( GLenum texture, GLfloat s, GLfloat t )
{
	(void) texture;
	(void) s;
	(void) t;
}

static void NopMultiTexCoord2fvARB( GLenum texture, const GLfloat *t )
{
	(void) texture;
	(void) t;
}

static void NopMultiTexCoord2iARB( GLenum texture, GLint s, GLint t )
{
	(void) texture;
	(void) s;
	(void) t;
}

static void NopMultiTexCoord2ivARB( GLenum texture, const GLint *t )
{
	(void) texture;
	(void) t;
}

static void NopMultiTexCoord2sARB( GLenum texture, GLshort s, GLshort t )
{
	(void) texture;
	(void) s;
	(void) t;
}

static void NopMultiTexCoord2svARB( GLenum texture, const GLshort *t )
{
	(void) texture;
	(void) t;
}

static void NopMultiTexCoord3dARB( GLenum texture, GLdouble s, GLdouble t, GLdouble r )
{
	(void) texture;
	(void) s;
	(void) t;
	(void) r;
}

static void NopMultiTexCoord3dvARB( GLenum texture, const GLdouble *t )
{
	(void) texture;
	(void) t;
}

static void NopMultiTexCoord3fARB( GLenum texture, GLfloat s, GLfloat t, GLfloat r )
{
	(void) texture;
	(void) s;
	(void) t;
	(void) r;
}

static void NopMultiTexCoord3fvARB( GLenum texture, const GLfloat *t )
{
	(void) texture;
	(void) t;
}

static void NopMultiTexCoord3iARB( GLenum texture, GLint s, GLint t, GLint r )
{
	(void) texture;
	(void) s;
	(void) t;
	(void) r;
}

static void NopMultiTexCoord3ivARB( GLenum texture, const GLint *t )
{
	(void) texture;
	(void) t;
}

static void NopMultiTexCoord3sARB( GLenum texture, GLshort s, GLshort t, GLshort r )
{
	(void) texture;
	(void) s;
	(void) t;
	(void) r;
}

static void NopMultiTexCoord3svARB( GLenum texture, const GLshort *t )
{
	(void) texture;
	(void) t;
}

static void NopMultiTexCoord4dARB( GLenum texture, GLdouble s, GLdouble t, GLdouble r, GLdouble q )
{
	(void) texture;
	(void) s;
	(void) t;
	(void) r;
	(void) q;
}

static void NopMultiTexCoord4dvARB( GLenum texture, const GLdouble *t )
{
	(void) texture;
	(void) t;
}

static void NopMultiTexCoord4fARB( GLenum texture, GLfloat s, GLfloat t, GLfloat r, GLfloat q )
{
	(void) texture;
	(void) s;
	(void) t;
	(void) r;
	(void) q;
}

static void NopMultiTexCoord4fvARB( GLenum texture, const GLfloat *t )
{
	(void) texture;
	(void) t;
}

static void NopMultiTexCoord4iARB( GLenum texture, GLint s, GLint t, GLint r, GLint q )
{
	(void) texture;
	(void) s;
	(void) t;
	(void) r;
	(void) q;
}

static void NopMultiTexCoord4ivARB( GLenum texture, const GLint *t )
{
	(void) texture;
	(void) t;
}

static void NopMultiTexCoord4sARB( GLenum texture, GLshort s, GLshort t, GLshort r, GLshort q )
{
	(void) texture;
	(void) s;
	(void) t;
	(void) r;
	(void) q;
}

static void NopMultiTexCoord4svARB( GLenum texture, const GLshort *t )
{
	(void) texture;
	(void) t;
}

static void NopSecondaryColor3bEXT( GLbyte red, GLbyte green, GLbyte blue )
{
	(void) red;
	(void) green;
	(void) blue;
}

static void NopSecondaryColor3bvEXT( const GLbyte *v )
{
	(void) v;
}

static void NopSecondaryColor3dEXT( GLdouble red, GLdouble green, GLdouble blue )
{
	(void) red;
	(void) green;
	(void) blue;
}

static void NopSecondaryColor3dvEXT( const GLdouble *v )
{
	(void) v;
}

static void NopSecondaryColor3fEXT( GLfloat red, GLfloat green, GLfloat blue )
{
	(void) red;
	(void) green;
	(void) blue;
}

static void NopSecondaryColor3fvEXT( const GLfloat *v )
{
	(void) v;
}

static void NopSecondaryColor3iEXT( GLint red, GLint green, GLint blue )
{
	(void) red;
	(void) green;
	(void) blue;
}

static void NopSecondaryColor3ivEXT( const GLint *v )
{
	(void) v;
}

static void NopSecondaryColor3sEXT( GLshort red, GLshort green, GLshort blue )
{
	(void) red;
	(void) green;
	(void) blue;
}

static void NopSecondaryColor3svEXT( const GLshort *v )
{
	(void) v;
}

static void NopSecondaryColor3ubEXT( GLubyte red, GLubyte green, GLubyte blue )
{
	(void) red;
	(void) green;
	(void) blue;
}

static void NopSecondaryColor3ubvEXT( const GLubyte *v )
{
	(void) v;
}

static void NopSecondaryColor3uiEXT( GLuint red, GLuint green, GLuint blue )
{
	(void) red;
	(void) green;
	(void) blue;
}

static void NopSecondaryColor3uivEXT( const GLuint *v )
{
	(void) v;
}

static void NopSecondaryColor3usEXT( GLushort red, GLushort green, GLushort blue )
{
	(void) red;
	(void) green;
	(void) blue;
}

static void NopSecondaryColor3usvEXT( const GLushort *v )
{
	(void) v;
}

static void NopSecondaryColorPointerEXT( GLint size, GLenum type, GLsizei stride, const GLvoid *pointer )
{
	(void) size;
	(void) type;
	(void) stride;
	(void) pointer;
}


/*
 * Initialize the 'interface' structure with the WGL or GLX window system
 * interface functions.
 * Then, fill in the table with (name, pointer) pairs for all the core
 * OpenGL entrypoint functions.
 */
int
crLoadOpenGL( crOpenGLInterface *interface, SPUNamedFunctionTable table[] )
{
	SPUNamedFunctionTable *entry = table;
	
	crDebug( "Looking for the system's OpenGL library..." );
	glDll = __findSystemGL( crGetenv( "CR_SYSTEM_GL_PATH" ) );
	if (!glDll)
	{
		crError("Unable to find system OpenGL!");
		return 0;
	}
	crDebug( "Found it." );

#ifdef WINDOWS
	interface->wglGetProcAddress = (wglGetProcAddressFunc_t) crDLLGetNoError( glDll, "wglGetProcAddress" );
	interface->wglMakeCurrent = (wglMakeCurrentFunc_t) crDLLGetNoError( glDll, "wglMakeCurrent" );
	interface->wglSwapBuffers = (wglSwapBuffersFunc_t) crDLLGetNoError( glDll, "wglSwapBuffers" );
	interface->wglCreateContext = (wglCreateContextFunc_t) crDLLGetNoError( glDll, "wglCreateContext" );
	interface->wglDeleteContext = (wglDeleteContextFunc_t) crDLLGetNoError( glDll, "wglDeleteContext" );
	interface->wglGetCurrentContext = (wglGetCurrentContextFunc_t) crDLLGetNoError( glDll, "wglGetCurrentContext" );
	interface->wglChoosePixelFormat = (wglChoosePixelFormatFunc_t) crDLLGetNoError( glDll, "wglChoosePixelFormat" );
	interface->wglSetPixelFormat = (wglSetPixelFormatFunc_t) crDLLGetNoError( glDll, "wglSetPixelFormat" );
#else
	interface->glXGetConfig = (glXGetConfigFunc_t) crDLLGetNoError( glDll, "glXGetConfig" );
	interface->glXQueryExtension = (glXQueryExtensionFunc_t) crDLLGetNoError( glDll, "glXQueryExtension" );
	interface->glXChooseVisual = (glXChooseVisualFunc_t) crDLLGetNoError( glDll, "glXChooseVisual" );
	interface->glXCreateContext = (glXCreateContextFunc_t) crDLLGetNoError( glDll, "glXCreateContext" );
	interface->glXDestroyContext = (glXDestroyContextFunc_t) crDLLGetNoError( glDll, "glXDestroyContext" );
	interface->glXIsDirect = (glXIsDirectFunc_t) crDLLGetNoError( glDll, "glXIsDirect" );
	interface->glXMakeCurrent = (glXMakeCurrentFunc_t) crDLLGetNoError( glDll, "glXMakeCurrent" );
	interface->glGetString = (glGetStringFunc_t) crDLLGetNoError( glDll, "glGetString" );
	interface->glXSwapBuffers = (glXSwapBuffersFunc_t) crDLLGetNoError( glDll, "glXSwapBuffers" );
	interface->glXGetCurrentDisplay = (glXGetCurrentDisplayFunc_t) crDLLGetNoError( glDll, "glXGetCurrentDisplay" );
	interface->glXGetProcAddressARB = (glXGetProcAddressARBFunc_t) crDLLGetNoError( glDll, "glXGetProcAddressARB" );
#endif
	FILLIN( "Accum", crDLLGetNoError(glDll, "glAccum"));
	FILLIN( "AlphaFunc", crDLLGetNoError(glDll, "glAlphaFunc"));
	FILLIN( "AreTexturesResident", crDLLGetNoError(glDll, "glAreTexturesResident"));
	FILLIN( "ArrayElement", crDLLGetNoError(glDll, "glArrayElement"));
	FILLIN( "BarrierCreate", crDLLGetNoError(glDll, "glBarrierCreate"));
	FILLIN( "BarrierDestroy", crDLLGetNoError(glDll, "glBarrierDestroy"));
	FILLIN( "BarrierExec", crDLLGetNoError(glDll, "glBarrierExec"));
	FILLIN( "Begin", crDLLGetNoError(glDll, "glBegin"));
	FILLIN( "BindTexture", crDLLGetNoError(glDll, "glBindTexture"));
	FILLIN( "Bitmap", crDLLGetNoError(glDll, "glBitmap"));
	FILLIN( "BlendFunc", crDLLGetNoError(glDll, "glBlendFunc"));
	FILLIN( "BoundsInfo", crDLLGetNoError(glDll, "glBoundsInfo"));
	FILLIN( "CallList", crDLLGetNoError(glDll, "glCallList"));
	FILLIN( "CallLists", crDLLGetNoError(glDll, "glCallLists"));
	FILLIN( "ChromiumParameterfCR", crDLLGetNoError(glDll, "glChromiumParameterfCR"));
	FILLIN( "ChromiumParameteriCR", crDLLGetNoError(glDll, "glChromiumParameteriCR"));
	FILLIN( "ChromiumParametervCR", crDLLGetNoError(glDll, "glChromiumParametervCR"));
	FILLIN( "Clear", crDLLGetNoError(glDll, "glClear"));
	FILLIN( "ClearAccum", crDLLGetNoError(glDll, "glClearAccum"));
	FILLIN( "ClearColor", crDLLGetNoError(glDll, "glClearColor"));
	FILLIN( "ClearDepth", crDLLGetNoError(glDll, "glClearDepth"));
	FILLIN( "ClearIndex", crDLLGetNoError(glDll, "glClearIndex"));
	FILLIN( "ClearStencil", crDLLGetNoError(glDll, "glClearStencil"));
	FILLIN( "ClipPlane", crDLLGetNoError(glDll, "glClipPlane"));
	FILLIN( "Color3b", crDLLGetNoError(glDll, "glColor3b"));
	FILLIN( "Color3bv", crDLLGetNoError(glDll, "glColor3bv"));
	FILLIN( "Color3d", crDLLGetNoError(glDll, "glColor3d"));
	FILLIN( "Color3dv", crDLLGetNoError(glDll, "glColor3dv"));
	FILLIN( "Color3f", crDLLGetNoError(glDll, "glColor3f"));
	FILLIN( "Color3fv", crDLLGetNoError(glDll, "glColor3fv"));
	FILLIN( "Color3i", crDLLGetNoError(glDll, "glColor3i"));
	FILLIN( "Color3iv", crDLLGetNoError(glDll, "glColor3iv"));
	FILLIN( "Color3s", crDLLGetNoError(glDll, "glColor3s"));
	FILLIN( "Color3sv", crDLLGetNoError(glDll, "glColor3sv"));
	FILLIN( "Color3ub", crDLLGetNoError(glDll, "glColor3ub"));
	FILLIN( "Color3ubv", crDLLGetNoError(glDll, "glColor3ubv"));
	FILLIN( "Color3ui", crDLLGetNoError(glDll, "glColor3ui"));
	FILLIN( "Color3uiv", crDLLGetNoError(glDll, "glColor3uiv"));
	FILLIN( "Color3us", crDLLGetNoError(glDll, "glColor3us"));
	FILLIN( "Color3usv", crDLLGetNoError(glDll, "glColor3usv"));
	FILLIN( "Color4b", crDLLGetNoError(glDll, "glColor4b"));
	FILLIN( "Color4bv", crDLLGetNoError(glDll, "glColor4bv"));
	FILLIN( "Color4d", crDLLGetNoError(glDll, "glColor4d"));
	FILLIN( "Color4dv", crDLLGetNoError(glDll, "glColor4dv"));
	FILLIN( "Color4f", crDLLGetNoError(glDll, "glColor4f"));
	FILLIN( "Color4fv", crDLLGetNoError(glDll, "glColor4fv"));
	FILLIN( "Color4i", crDLLGetNoError(glDll, "glColor4i"));
	FILLIN( "Color4iv", crDLLGetNoError(glDll, "glColor4iv"));
	FILLIN( "Color4s", crDLLGetNoError(glDll, "glColor4s"));
	FILLIN( "Color4sv", crDLLGetNoError(glDll, "glColor4sv"));
	FILLIN( "Color4ub", crDLLGetNoError(glDll, "glColor4ub"));
	FILLIN( "Color4ubv", crDLLGetNoError(glDll, "glColor4ubv"));
	FILLIN( "Color4ui", crDLLGetNoError(glDll, "glColor4ui"));
	FILLIN( "Color4uiv", crDLLGetNoError(glDll, "glColor4uiv"));
	FILLIN( "Color4us", crDLLGetNoError(glDll, "glColor4us"));
	FILLIN( "Color4usv", crDLLGetNoError(glDll, "glColor4usv"));
	FILLIN( "ColorMask", crDLLGetNoError(glDll, "glColorMask"));
	FILLIN( "ColorMaterial", crDLLGetNoError(glDll, "glColorMaterial"));
	FILLIN( "ColorPointer", crDLLGetNoError(glDll, "glColorPointer"));
	FILLIN( "CopyPixels", crDLLGetNoError(glDll, "glCopyPixels"));
	FILLIN( "CopyTexImage1D", crDLLGetNoError(glDll, "glCopyTexImage1D"));
	FILLIN( "CopyTexImage2D", crDLLGetNoError(glDll, "glCopyTexImage2D"));
	FILLIN( "CopyTexSubImage1D", crDLLGetNoError(glDll, "glCopyTexSubImage1D"));
	FILLIN( "CopyTexSubImage2D", crDLLGetNoError(glDll, "glCopyTexSubImage2D"));
	FILLIN( "CreateContext", crDLLGetNoError(glDll, "glCreateContext"));
	FILLIN( "CullFace", crDLLGetNoError(glDll, "glCullFace"));
	FILLIN( "DeleteLists", crDLLGetNoError(glDll, "glDeleteLists"));
	FILLIN( "DeleteTextures", crDLLGetNoError(glDll, "glDeleteTextures"));
	FILLIN( "DepthFunc", crDLLGetNoError(glDll, "glDepthFunc"));
	FILLIN( "DepthMask", crDLLGetNoError(glDll, "glDepthMask"));
	FILLIN( "DepthRange", crDLLGetNoError(glDll, "glDepthRange"));
	FILLIN( "DestroyContext", crDLLGetNoError(glDll, "glDestroyContext"));
	FILLIN( "Disable", crDLLGetNoError(glDll, "glDisable"));
	FILLIN( "DisableClientState", crDLLGetNoError(glDll, "glDisableClientState"));
	FILLIN( "DrawArrays", crDLLGetNoError(glDll, "glDrawArrays"));
	FILLIN( "DrawBuffer", crDLLGetNoError(glDll, "glDrawBuffer"));
	FILLIN( "DrawElements", crDLLGetNoError(glDll, "glDrawElements"));
	FILLIN( "DrawPixels", crDLLGetNoError(glDll, "glDrawPixels"));
	FILLIN( "DrawRangeElements", crDLLGetNoError(glDll, "glDrawRangeElements"));
	FILLIN( "EdgeFlag", crDLLGetNoError(glDll, "glEdgeFlag"));
	FILLIN( "EdgeFlagPointer", crDLLGetNoError(glDll, "glEdgeFlagPointer"));
	FILLIN( "EdgeFlagv", crDLLGetNoError(glDll, "glEdgeFlagv"));
	FILLIN( "Enable", crDLLGetNoError(glDll, "glEnable"));
	FILLIN( "EnableClientState", crDLLGetNoError(glDll, "glEnableClientState"));
	FILLIN( "End", crDLLGetNoError(glDll, "glEnd"));
	FILLIN( "EndList", crDLLGetNoError(glDll, "glEndList"));
	FILLIN( "EvalCoord1d", crDLLGetNoError(glDll, "glEvalCoord1d"));
	FILLIN( "EvalCoord1dv", crDLLGetNoError(glDll, "glEvalCoord1dv"));
	FILLIN( "EvalCoord1f", crDLLGetNoError(glDll, "glEvalCoord1f"));
	FILLIN( "EvalCoord1fv", crDLLGetNoError(glDll, "glEvalCoord1fv"));
	FILLIN( "EvalCoord2d", crDLLGetNoError(glDll, "glEvalCoord2d"));
	FILLIN( "EvalCoord2dv", crDLLGetNoError(glDll, "glEvalCoord2dv"));
	FILLIN( "EvalCoord2f", crDLLGetNoError(glDll, "glEvalCoord2f"));
	FILLIN( "EvalCoord2fv", crDLLGetNoError(glDll, "glEvalCoord2fv"));
	FILLIN( "EvalMesh1", crDLLGetNoError(glDll, "glEvalMesh1"));
	FILLIN( "EvalMesh2", crDLLGetNoError(glDll, "glEvalMesh2"));
	FILLIN( "EvalPoint1", crDLLGetNoError(glDll, "glEvalPoint1"));
	FILLIN( "EvalPoint2", crDLLGetNoError(glDll, "glEvalPoint2"));
	FILLIN( "FeedbackBuffer", crDLLGetNoError(glDll, "glFeedbackBuffer"));
	FILLIN( "Finish", crDLLGetNoError(glDll, "glFinish"));
	FILLIN( "Flush", crDLLGetNoError(glDll, "glFlush"));
	FILLIN( "Fogf", crDLLGetNoError(glDll, "glFogf"));
	FILLIN( "Fogfv", crDLLGetNoError(glDll, "glFogfv"));
	FILLIN( "Fogi", crDLLGetNoError(glDll, "glFogi"));
	FILLIN( "Fogiv", crDLLGetNoError(glDll, "glFogiv"));
	FILLIN( "FrontFace", crDLLGetNoError(glDll, "glFrontFace"));
	FILLIN( "Frustum", crDLLGetNoError(glDll, "glFrustum"));
	FILLIN( "GenLists", crDLLGetNoError(glDll, "glGenLists"));
	FILLIN( "GenTextures", crDLLGetNoError(glDll, "glGenTextures"));
	FILLIN( "GetBooleanv", crDLLGetNoError(glDll, "glGetBooleanv"));
	FILLIN( "GetChromiumParametervCR", crDLLGetNoError(glDll, "glGetChromiumParametervCR"));
	FILLIN( "GetClipPlane", crDLLGetNoError(glDll, "glGetClipPlane"));
	FILLIN( "GetCombinerInputParameterfvNV", crDLLGetNoError(glDll, "glGetCombinerInputParameterfvNV"));
	FILLIN( "GetCombinerInputParameterivNV", crDLLGetNoError(glDll, "glGetCombinerInputParameterivNV"));
	FILLIN( "GetCombinerOutputParameterfvNV", crDLLGetNoError(glDll, "glGetCombinerOutputParameterfvNV"));
	FILLIN( "GetCombinerOutputParameterivNV", crDLLGetNoError(glDll, "glGetCombinerOutputParameterivNV"));
	FILLIN( "GetDoublev", crDLLGetNoError(glDll, "glGetDoublev"));
	FILLIN( "GetError", crDLLGetNoError(glDll, "glGetError"));
	FILLIN( "GetFinalCombinerInputParameterfvNV", crDLLGetNoError(glDll, "glGetFinalCombinerInputParameterfvNV"));
	FILLIN( "GetFinalCombinerInputParameterivNV", crDLLGetNoError(glDll, "glGetFinalCombinerInputParameterivNV"));
	FILLIN( "GetFloatv", crDLLGetNoError(glDll, "glGetFloatv"));
	FILLIN( "GetIntegerv", crDLLGetNoError(glDll, "glGetIntegerv"));
	FILLIN( "GetLightfv", crDLLGetNoError(glDll, "glGetLightfv"));
	FILLIN( "GetLightiv", crDLLGetNoError(glDll, "glGetLightiv"));
	FILLIN( "GetMapdv", crDLLGetNoError(glDll, "glGetMapdv"));
	FILLIN( "GetMapfv", crDLLGetNoError(glDll, "glGetMapfv"));
	FILLIN( "GetMapiv", crDLLGetNoError(glDll, "glGetMapiv"));
	FILLIN( "GetMaterialfv", crDLLGetNoError(glDll, "glGetMaterialfv"));
	FILLIN( "GetMaterialiv", crDLLGetNoError(glDll, "glGetMaterialiv"));
	FILLIN( "GetPixelMapfv", crDLLGetNoError(glDll, "glGetPixelMapfv"));
	FILLIN( "GetPixelMapuiv", crDLLGetNoError(glDll, "glGetPixelMapuiv"));
	FILLIN( "GetPixelMapusv", crDLLGetNoError(glDll, "glGetPixelMapusv"));
	FILLIN( "GetPointerv", crDLLGetNoError(glDll, "glGetPointerv"));
	FILLIN( "GetPolygonStipple", crDLLGetNoError(glDll, "glGetPolygonStipple"));
	FILLIN( "GetString", crDLLGetNoError(glDll, "glGetString"));
	FILLIN( "GetTexEnvfv", crDLLGetNoError(glDll, "glGetTexEnvfv"));
	FILLIN( "GetTexEnviv", crDLLGetNoError(glDll, "glGetTexEnviv"));
	FILLIN( "GetTexGendv", crDLLGetNoError(glDll, "glGetTexGendv"));
	FILLIN( "GetTexGenfv", crDLLGetNoError(glDll, "glGetTexGenfv"));
	FILLIN( "GetTexGeniv", crDLLGetNoError(glDll, "glGetTexGeniv"));
	FILLIN( "GetTexImage", crDLLGetNoError(glDll, "glGetTexImage"));
	FILLIN( "GetTexLevelParameterfv", crDLLGetNoError(glDll, "glGetTexLevelParameterfv"));
	FILLIN( "GetTexLevelParameteriv", crDLLGetNoError(glDll, "glGetTexLevelParameteriv"));
	FILLIN( "GetTexParameterfv", crDLLGetNoError(glDll, "glGetTexParameterfv"));
	FILLIN( "GetTexParameteriv", crDLLGetNoError(glDll, "glGetTexParameteriv"));
	FILLIN( "Hint", crDLLGetNoError(glDll, "glHint"));
	FILLIN( "IndexMask", crDLLGetNoError(glDll, "glIndexMask"));
	FILLIN( "IndexPointer", crDLLGetNoError(glDll, "glIndexPointer"));
	FILLIN( "Indexd", crDLLGetNoError(glDll, "glIndexd"));
	FILLIN( "Indexdv", crDLLGetNoError(glDll, "glIndexdv"));
	FILLIN( "Indexf", crDLLGetNoError(glDll, "glIndexf"));
	FILLIN( "Indexfv", crDLLGetNoError(glDll, "glIndexfv"));
	FILLIN( "Indexi", crDLLGetNoError(glDll, "glIndexi"));
	FILLIN( "Indexiv", crDLLGetNoError(glDll, "glIndexiv"));
	FILLIN( "Indexs", crDLLGetNoError(glDll, "glIndexs"));
	FILLIN( "Indexsv", crDLLGetNoError(glDll, "glIndexsv"));
	FILLIN( "Indexub", crDLLGetNoError(glDll, "glIndexub"));
	FILLIN( "Indexubv", crDLLGetNoError(glDll, "glIndexubv"));
	FILLIN( "InitNames", crDLLGetNoError(glDll, "glInitNames"));
	FILLIN( "InterleavedArrays", crDLLGetNoError(glDll, "glInterleavedArrays"));
	FILLIN( "IsEnabled", crDLLGetNoError(glDll, "glIsEnabled"));
	FILLIN( "IsList", crDLLGetNoError(glDll, "glIsList"));
	FILLIN( "IsTexture", crDLLGetNoError(glDll, "glIsTexture"));
	FILLIN( "LightModelf", crDLLGetNoError(glDll, "glLightModelf"));
	FILLIN( "LightModelfv", crDLLGetNoError(glDll, "glLightModelfv"));
	FILLIN( "LightModeli", crDLLGetNoError(glDll, "glLightModeli"));
	FILLIN( "LightModeliv", crDLLGetNoError(glDll, "glLightModeliv"));
	FILLIN( "Lightf", crDLLGetNoError(glDll, "glLightf"));
	FILLIN( "Lightfv", crDLLGetNoError(glDll, "glLightfv"));
	FILLIN( "Lighti", crDLLGetNoError(glDll, "glLighti"));
	FILLIN( "Lightiv", crDLLGetNoError(glDll, "glLightiv"));
	FILLIN( "LineStipple", crDLLGetNoError(glDll, "glLineStipple"));
	FILLIN( "LineWidth", crDLLGetNoError(glDll, "glLineWidth"));
	FILLIN( "ListBase", crDLLGetNoError(glDll, "glListBase"));
	FILLIN( "LoadIdentity", crDLLGetNoError(glDll, "glLoadIdentity"));
	FILLIN( "LoadMatrixd", crDLLGetNoError(glDll, "glLoadMatrixd"));
	FILLIN( "LoadMatrixf", crDLLGetNoError(glDll, "glLoadMatrixf"));
	FILLIN( "LoadName", crDLLGetNoError(glDll, "glLoadName"));
	FILLIN( "LogicOp", crDLLGetNoError(glDll, "glLogicOp"));
	FILLIN( "MakeCurrent", crDLLGetNoError(glDll, "glMakeCurrent"));
	FILLIN( "Map1d", crDLLGetNoError(glDll, "glMap1d"));
	FILLIN( "Map1f", crDLLGetNoError(glDll, "glMap1f"));
	FILLIN( "Map2d", crDLLGetNoError(glDll, "glMap2d"));
	FILLIN( "Map2f", crDLLGetNoError(glDll, "glMap2f"));
	FILLIN( "MapGrid1d", crDLLGetNoError(glDll, "glMapGrid1d"));
	FILLIN( "MapGrid1f", crDLLGetNoError(glDll, "glMapGrid1f"));
	FILLIN( "MapGrid2d", crDLLGetNoError(glDll, "glMapGrid2d"));
	FILLIN( "MapGrid2f", crDLLGetNoError(glDll, "glMapGrid2f"));
	FILLIN( "Materialf", crDLLGetNoError(glDll, "glMaterialf"));
	FILLIN( "Materialfv", crDLLGetNoError(glDll, "glMaterialfv"));
	FILLIN( "Materiali", crDLLGetNoError(glDll, "glMateriali"));
	FILLIN( "Materialiv", crDLLGetNoError(glDll, "glMaterialiv"));
	FILLIN( "MatrixMode", crDLLGetNoError(glDll, "glMatrixMode"));
	FILLIN( "MultMatrixd", crDLLGetNoError(glDll, "glMultMatrixd"));
	FILLIN( "MultMatrixf", crDLLGetNoError(glDll, "glMultMatrixf"));
	FILLIN( "NewList", crDLLGetNoError(glDll, "glNewList"));
	FILLIN( "Normal3b", crDLLGetNoError(glDll, "glNormal3b"));
	FILLIN( "Normal3bv", crDLLGetNoError(glDll, "glNormal3bv"));
	FILLIN( "Normal3d", crDLLGetNoError(glDll, "glNormal3d"));
	FILLIN( "Normal3dv", crDLLGetNoError(glDll, "glNormal3dv"));
	FILLIN( "Normal3f", crDLLGetNoError(glDll, "glNormal3f"));
	FILLIN( "Normal3fv", crDLLGetNoError(glDll, "glNormal3fv"));
	FILLIN( "Normal3i", crDLLGetNoError(glDll, "glNormal3i"));
	FILLIN( "Normal3iv", crDLLGetNoError(glDll, "glNormal3iv"));
	FILLIN( "Normal3s", crDLLGetNoError(glDll, "glNormal3s"));
	FILLIN( "Normal3sv", crDLLGetNoError(glDll, "glNormal3sv"));
	FILLIN( "NormalPointer", crDLLGetNoError(glDll, "glNormalPointer"));
	FILLIN( "Ortho", crDLLGetNoError(glDll, "glOrtho"));
	FILLIN( "PassThrough", crDLLGetNoError(glDll, "glPassThrough"));
	FILLIN( "PixelMapfv", crDLLGetNoError(glDll, "glPixelMapfv"));
	FILLIN( "PixelMapuiv", crDLLGetNoError(glDll, "glPixelMapuiv"));
	FILLIN( "PixelMapusv", crDLLGetNoError(glDll, "glPixelMapusv"));
	FILLIN( "PixelStoref", crDLLGetNoError(glDll, "glPixelStoref"));
	FILLIN( "PixelStorei", crDLLGetNoError(glDll, "glPixelStorei"));
	FILLIN( "PixelTransferf", crDLLGetNoError(glDll, "glPixelTransferf"));
	FILLIN( "PixelTransferi", crDLLGetNoError(glDll, "glPixelTransferi"));
	FILLIN( "PixelZoom", crDLLGetNoError(glDll, "glPixelZoom"));
	FILLIN( "PointSize", crDLLGetNoError(glDll, "glPointSize"));
	FILLIN( "PolygonMode", crDLLGetNoError(glDll, "glPolygonMode"));
	FILLIN( "PolygonOffset", crDLLGetNoError(glDll, "glPolygonOffset"));
	FILLIN( "PolygonStipple", crDLLGetNoError(glDll, "glPolygonStipple"));
	FILLIN( "PopAttrib", crDLLGetNoError(glDll, "glPopAttrib"));
	FILLIN( "PopClientAttrib", crDLLGetNoError(glDll, "glPopClientAttrib"));
	FILLIN( "PopMatrix", crDLLGetNoError(glDll, "glPopMatrix"));
	FILLIN( "PopName", crDLLGetNoError(glDll, "glPopName"));
	FILLIN( "PrioritizeTextures", crDLLGetNoError(glDll, "glPrioritizeTextures"));
	FILLIN( "PushAttrib", crDLLGetNoError(glDll, "glPushAttrib"));
	FILLIN( "PushClientAttrib", crDLLGetNoError(glDll, "glPushClientAttrib"));
	FILLIN( "PushMatrix", crDLLGetNoError(glDll, "glPushMatrix"));
	FILLIN( "PushName", crDLLGetNoError(glDll, "glPushName"));
	FILLIN( "RasterPos2d", crDLLGetNoError(glDll, "glRasterPos2d"));
	FILLIN( "RasterPos2dv", crDLLGetNoError(glDll, "glRasterPos2dv"));
	FILLIN( "RasterPos2f", crDLLGetNoError(glDll, "glRasterPos2f"));
	FILLIN( "RasterPos2fv", crDLLGetNoError(glDll, "glRasterPos2fv"));
	FILLIN( "RasterPos2i", crDLLGetNoError(glDll, "glRasterPos2i"));
	FILLIN( "RasterPos2iv", crDLLGetNoError(glDll, "glRasterPos2iv"));
	FILLIN( "RasterPos2s", crDLLGetNoError(glDll, "glRasterPos2s"));
	FILLIN( "RasterPos2sv", crDLLGetNoError(glDll, "glRasterPos2sv"));
	FILLIN( "RasterPos3d", crDLLGetNoError(glDll, "glRasterPos3d"));
	FILLIN( "RasterPos3dv", crDLLGetNoError(glDll, "glRasterPos3dv"));
	FILLIN( "RasterPos3f", crDLLGetNoError(glDll, "glRasterPos3f"));
	FILLIN( "RasterPos3fv", crDLLGetNoError(glDll, "glRasterPos3fv"));
	FILLIN( "RasterPos3i", crDLLGetNoError(glDll, "glRasterPos3i"));
	FILLIN( "RasterPos3iv", crDLLGetNoError(glDll, "glRasterPos3iv"));
	FILLIN( "RasterPos3s", crDLLGetNoError(glDll, "glRasterPos3s"));
	FILLIN( "RasterPos3sv", crDLLGetNoError(glDll, "glRasterPos3sv"));
	FILLIN( "RasterPos4d", crDLLGetNoError(glDll, "glRasterPos4d"));
	FILLIN( "RasterPos4dv", crDLLGetNoError(glDll, "glRasterPos4dv"));
	FILLIN( "RasterPos4f", crDLLGetNoError(glDll, "glRasterPos4f"));
	FILLIN( "RasterPos4fv", crDLLGetNoError(glDll, "glRasterPos4fv"));
	FILLIN( "RasterPos4i", crDLLGetNoError(glDll, "glRasterPos4i"));
	FILLIN( "RasterPos4iv", crDLLGetNoError(glDll, "glRasterPos4iv"));
	FILLIN( "RasterPos4s", crDLLGetNoError(glDll, "glRasterPos4s"));
	FILLIN( "RasterPos4sv", crDLLGetNoError(glDll, "glRasterPos4sv"));
	FILLIN( "ReadBuffer", crDLLGetNoError(glDll, "glReadBuffer"));
	FILLIN( "ReadPixels", crDLLGetNoError(glDll, "glReadPixels"));
	FILLIN( "Rectd", crDLLGetNoError(glDll, "glRectd"));
	FILLIN( "Rectdv", crDLLGetNoError(glDll, "glRectdv"));
	FILLIN( "Rectf", crDLLGetNoError(glDll, "glRectf"));
	FILLIN( "Rectfv", crDLLGetNoError(glDll, "glRectfv"));
	FILLIN( "Recti", crDLLGetNoError(glDll, "glRecti"));
	FILLIN( "Rectiv", crDLLGetNoError(glDll, "glRectiv"));
	FILLIN( "Rects", crDLLGetNoError(glDll, "glRects"));
	FILLIN( "Rectsv", crDLLGetNoError(glDll, "glRectsv"));
	FILLIN( "RenderMode", crDLLGetNoError(glDll, "glRenderMode"));
	FILLIN( "Rotated", crDLLGetNoError(glDll, "glRotated"));
	FILLIN( "Rotatef", crDLLGetNoError(glDll, "glRotatef"));
	FILLIN( "Scaled", crDLLGetNoError(glDll, "glScaled"));
	FILLIN( "Scalef", crDLLGetNoError(glDll, "glScalef"));
	FILLIN( "Scissor", crDLLGetNoError(glDll, "glScissor"));
	FILLIN( "SelectBuffer", crDLLGetNoError(glDll, "glSelectBuffer"));
	FILLIN( "SemaphoreCreate", crDLLGetNoError(glDll, "glSemaphoreCreate"));
	FILLIN( "SemaphoreDestroy", crDLLGetNoError(glDll, "glSemaphoreDestroy"));
	FILLIN( "SemaphoreP", crDLLGetNoError(glDll, "glSemaphoreP"));
	FILLIN( "SemaphoreV", crDLLGetNoError(glDll, "glSemaphoreV"));
	FILLIN( "ShadeModel", crDLLGetNoError(glDll, "glShadeModel"));
	FILLIN( "StencilFunc", crDLLGetNoError(glDll, "glStencilFunc"));
	FILLIN( "StencilMask", crDLLGetNoError(glDll, "glStencilMask"));
	FILLIN( "StencilOp", crDLLGetNoError(glDll, "glStencilOp"));
	FILLIN( "SwapBuffers", crDLLGetNoError(glDll, "glSwapBuffers"));
	FILLIN( "TexCoord1d", crDLLGetNoError(glDll, "glTexCoord1d"));
	FILLIN( "TexCoord1dv", crDLLGetNoError(glDll, "glTexCoord1dv"));
	FILLIN( "TexCoord1f", crDLLGetNoError(glDll, "glTexCoord1f"));
	FILLIN( "TexCoord1fv", crDLLGetNoError(glDll, "glTexCoord1fv"));
	FILLIN( "TexCoord1i", crDLLGetNoError(glDll, "glTexCoord1i"));
	FILLIN( "TexCoord1iv", crDLLGetNoError(glDll, "glTexCoord1iv"));
	FILLIN( "TexCoord1s", crDLLGetNoError(glDll, "glTexCoord1s"));
	FILLIN( "TexCoord1sv", crDLLGetNoError(glDll, "glTexCoord1sv"));
	FILLIN( "TexCoord2d", crDLLGetNoError(glDll, "glTexCoord2d"));
	FILLIN( "TexCoord2dv", crDLLGetNoError(glDll, "glTexCoord2dv"));
	FILLIN( "TexCoord2f", crDLLGetNoError(glDll, "glTexCoord2f"));
	FILLIN( "TexCoord2fv", crDLLGetNoError(glDll, "glTexCoord2fv"));
	FILLIN( "TexCoord2i", crDLLGetNoError(glDll, "glTexCoord2i"));
	FILLIN( "TexCoord2iv", crDLLGetNoError(glDll, "glTexCoord2iv"));
	FILLIN( "TexCoord2s", crDLLGetNoError(glDll, "glTexCoord2s"));
	FILLIN( "TexCoord2sv", crDLLGetNoError(glDll, "glTexCoord2sv"));
	FILLIN( "TexCoord3d", crDLLGetNoError(glDll, "glTexCoord3d"));
	FILLIN( "TexCoord3dv", crDLLGetNoError(glDll, "glTexCoord3dv"));
	FILLIN( "TexCoord3f", crDLLGetNoError(glDll, "glTexCoord3f"));
	FILLIN( "TexCoord3fv", crDLLGetNoError(glDll, "glTexCoord3fv"));
	FILLIN( "TexCoord3i", crDLLGetNoError(glDll, "glTexCoord3i"));
	FILLIN( "TexCoord3iv", crDLLGetNoError(glDll, "glTexCoord3iv"));
	FILLIN( "TexCoord3s", crDLLGetNoError(glDll, "glTexCoord3s"));
	FILLIN( "TexCoord3sv", crDLLGetNoError(glDll, "glTexCoord3sv"));
	FILLIN( "TexCoord4d", crDLLGetNoError(glDll, "glTexCoord4d"));
	FILLIN( "TexCoord4dv", crDLLGetNoError(glDll, "glTexCoord4dv"));
	FILLIN( "TexCoord4f", crDLLGetNoError(glDll, "glTexCoord4f"));
	FILLIN( "TexCoord4fv", crDLLGetNoError(glDll, "glTexCoord4fv"));
	FILLIN( "TexCoord4i", crDLLGetNoError(glDll, "glTexCoord4i"));
	FILLIN( "TexCoord4iv", crDLLGetNoError(glDll, "glTexCoord4iv"));
	FILLIN( "TexCoord4s", crDLLGetNoError(glDll, "glTexCoord4s"));
	FILLIN( "TexCoord4sv", crDLLGetNoError(glDll, "glTexCoord4sv"));
	FILLIN( "TexCoordPointer", crDLLGetNoError(glDll, "glTexCoordPointer"));
	FILLIN( "TexEnvf", crDLLGetNoError(glDll, "glTexEnvf"));
	FILLIN( "TexEnvfv", crDLLGetNoError(glDll, "glTexEnvfv"));
	FILLIN( "TexEnvi", crDLLGetNoError(glDll, "glTexEnvi"));
	FILLIN( "TexEnviv", crDLLGetNoError(glDll, "glTexEnviv"));
	FILLIN( "TexGend", crDLLGetNoError(glDll, "glTexGend"));
	FILLIN( "TexGendv", crDLLGetNoError(glDll, "glTexGendv"));
	FILLIN( "TexGenf", crDLLGetNoError(glDll, "glTexGenf"));
	FILLIN( "TexGenfv", crDLLGetNoError(glDll, "glTexGenfv"));
	FILLIN( "TexGeni", crDLLGetNoError(glDll, "glTexGeni"));
	FILLIN( "TexGeniv", crDLLGetNoError(glDll, "glTexGeniv"));
	FILLIN( "TexImage1D", crDLLGetNoError(glDll, "glTexImage1D"));
	FILLIN( "TexImage2D", crDLLGetNoError(glDll, "glTexImage2D"));
	FILLIN( "TexParameterf", crDLLGetNoError(glDll, "glTexParameterf"));
	FILLIN( "TexParameterfv", crDLLGetNoError(glDll, "glTexParameterfv"));
	FILLIN( "TexParameteri", crDLLGetNoError(glDll, "glTexParameteri"));
	FILLIN( "TexParameteriv", crDLLGetNoError(glDll, "glTexParameteriv"));
	FILLIN( "TexSubImage1D", crDLLGetNoError(glDll, "glTexSubImage1D"));
	FILLIN( "TexSubImage2D", crDLLGetNoError(glDll, "glTexSubImage2D"));
	FILLIN( "Translated", crDLLGetNoError(glDll, "glTranslated"));
	FILLIN( "Translatef", crDLLGetNoError(glDll, "glTranslatef"));
	FILLIN( "Vertex2d", crDLLGetNoError(glDll, "glVertex2d"));
	FILLIN( "Vertex2dv", crDLLGetNoError(glDll, "glVertex2dv"));
	FILLIN( "Vertex2f", crDLLGetNoError(glDll, "glVertex2f"));
	FILLIN( "Vertex2fv", crDLLGetNoError(glDll, "glVertex2fv"));
	FILLIN( "Vertex2i", crDLLGetNoError(glDll, "glVertex2i"));
	FILLIN( "Vertex2iv", crDLLGetNoError(glDll, "glVertex2iv"));
	FILLIN( "Vertex2s", crDLLGetNoError(glDll, "glVertex2s"));
	FILLIN( "Vertex2sv", crDLLGetNoError(glDll, "glVertex2sv"));
	FILLIN( "Vertex3d", crDLLGetNoError(glDll, "glVertex3d"));
	FILLIN( "Vertex3dv", crDLLGetNoError(glDll, "glVertex3dv"));
	FILLIN( "Vertex3f", crDLLGetNoError(glDll, "glVertex3f"));
	FILLIN( "Vertex3fv", crDLLGetNoError(glDll, "glVertex3fv"));
	FILLIN( "Vertex3i", crDLLGetNoError(glDll, "glVertex3i"));
	FILLIN( "Vertex3iv", crDLLGetNoError(glDll, "glVertex3iv"));
	FILLIN( "Vertex3s", crDLLGetNoError(glDll, "glVertex3s"));
	FILLIN( "Vertex3sv", crDLLGetNoError(glDll, "glVertex3sv"));
	FILLIN( "Vertex4d", crDLLGetNoError(glDll, "glVertex4d"));
	FILLIN( "Vertex4dv", crDLLGetNoError(glDll, "glVertex4dv"));
	FILLIN( "Vertex4f", crDLLGetNoError(glDll, "glVertex4f"));
	FILLIN( "Vertex4fv", crDLLGetNoError(glDll, "glVertex4fv"));
	FILLIN( "Vertex4i", crDLLGetNoError(glDll, "glVertex4i"));
	FILLIN( "Vertex4iv", crDLLGetNoError(glDll, "glVertex4iv"));
	FILLIN( "Vertex4s", crDLLGetNoError(glDll, "glVertex4s"));
	FILLIN( "Vertex4sv", crDLLGetNoError(glDll, "glVertex4sv"));
	FILLIN( "VertexPointer", crDLLGetNoError(glDll, "glVertexPointer"));
	FILLIN( "Viewport", crDLLGetNoError(glDll, "glViewport"));
	FILLIN( "Writeback", crDLLGetNoError(glDll, "glWriteback"));
	entry->name = NULL;
	entry->fn = NULL;
	return entry - table;  /* number of entries filled */
}

int
crLoadOpenGLExtensions( const crOpenGLInterface *interface, SPUNamedFunctionTable table[] )
{
	SPUNamedFunctionTable *entry = table;
	SPUGenericFunction f;

#ifdef WINDOWS
	if (interface->wglGetProcAddress == NULL)
		crWarning("Unable to find wglGetProcAddress() in system GL library");
#else
	if (interface->glXGetProcAddressARB == NULL)
		crWarning("Unable to find glXGetProcAddressARB() in system GL library");
#endif

	FILLIN_OPT( "ActiveTextureARB", __findExtFunction(interface, "glActiveTextureARB"), (SPUGenericFunction) NopActiveTextureARB );
	FILLIN_OPT( "BlendColorEXT", __findExtFunction(interface, "glBlendColorEXT"), (SPUGenericFunction) NopBlendColorEXT );
	FILLIN_OPT( "BlendEquationEXT", __findExtFunction(interface, "glBlendEquationEXT"), (SPUGenericFunction) NopBlendEquationEXT );
	FILLIN_OPT( "ClientActiveTextureARB", __findExtFunction(interface, "glClientActiveTextureARB"), (SPUGenericFunction) NopClientActiveTextureARB );
	FILLIN_OPT( "CombinerInputNV", __findExtFunction(interface, "glCombinerInputNV"), (SPUGenericFunction) NopCombinerInputNV );
	FILLIN_OPT( "CombinerOutputNV", __findExtFunction(interface, "glCombinerOutputNV"), (SPUGenericFunction) NopCombinerOutputNV );
	FILLIN_OPT( "CombinerParameterfNV", __findExtFunction(interface, "glCombinerParameterfNV"), (SPUGenericFunction) NopCombinerParameterfNV );
	FILLIN_OPT( "CombinerParameterfvNV", __findExtFunction(interface, "glCombinerParameterfvNV"), (SPUGenericFunction) NopCombinerParameterfvNV );
	FILLIN_OPT( "CombinerParameteriNV", __findExtFunction(interface, "glCombinerParameteriNV"), (SPUGenericFunction) NopCombinerParameteriNV );
	FILLIN_OPT( "CombinerParameterivNV", __findExtFunction(interface, "glCombinerParameterivNV"), (SPUGenericFunction) NopCombinerParameterivNV );
	FILLIN_OPT( "CombinerStageParameterfvNV", __findExtFunction(interface, "glCombinerStageParameterfvNV"), (SPUGenericFunction) NopCombinerStageParameterfvNV );
	FILLIN_OPT( "FinalCombinerInputNV", __findExtFunction(interface, "glFinalCombinerInputNV"), (SPUGenericFunction) NopFinalCombinerInputNV );
	FILLIN_OPT( "GetCombinerStageParameterfvNV", __findExtFunction(interface, "glGetCombinerStageParameterfvNV"), (SPUGenericFunction) NopGetCombinerStageParameterfvNV );
	FILLIN_OPT( "MultiTexCoord1dARB", __findExtFunction(interface, "glMultiTexCoord1dARB"), (SPUGenericFunction) NopMultiTexCoord1dARB );
	FILLIN_OPT( "MultiTexCoord1dvARB", __findExtFunction(interface, "glMultiTexCoord1dvARB"), (SPUGenericFunction) NopMultiTexCoord1dvARB );
	FILLIN_OPT( "MultiTexCoord1fARB", __findExtFunction(interface, "glMultiTexCoord1fARB"), (SPUGenericFunction) NopMultiTexCoord1fARB );
	FILLIN_OPT( "MultiTexCoord1fvARB", __findExtFunction(interface, "glMultiTexCoord1fvARB"), (SPUGenericFunction) NopMultiTexCoord1fvARB );
	FILLIN_OPT( "MultiTexCoord1iARB", __findExtFunction(interface, "glMultiTexCoord1iARB"), (SPUGenericFunction) NopMultiTexCoord1iARB );
	FILLIN_OPT( "MultiTexCoord1ivARB", __findExtFunction(interface, "glMultiTexCoord1ivARB"), (SPUGenericFunction) NopMultiTexCoord1ivARB );
	FILLIN_OPT( "MultiTexCoord1sARB", __findExtFunction(interface, "glMultiTexCoord1sARB"), (SPUGenericFunction) NopMultiTexCoord1sARB );
	FILLIN_OPT( "MultiTexCoord1svARB", __findExtFunction(interface, "glMultiTexCoord1svARB"), (SPUGenericFunction) NopMultiTexCoord1svARB );
	FILLIN_OPT( "MultiTexCoord2dARB", __findExtFunction(interface, "glMultiTexCoord2dARB"), (SPUGenericFunction) NopMultiTexCoord2dARB );
	FILLIN_OPT( "MultiTexCoord2dvARB", __findExtFunction(interface, "glMultiTexCoord2dvARB"), (SPUGenericFunction) NopMultiTexCoord2dvARB );
	FILLIN_OPT( "MultiTexCoord2fARB", __findExtFunction(interface, "glMultiTexCoord2fARB"), (SPUGenericFunction) NopMultiTexCoord2fARB );
	FILLIN_OPT( "MultiTexCoord2fvARB", __findExtFunction(interface, "glMultiTexCoord2fvARB"), (SPUGenericFunction) NopMultiTexCoord2fvARB );
	FILLIN_OPT( "MultiTexCoord2iARB", __findExtFunction(interface, "glMultiTexCoord2iARB"), (SPUGenericFunction) NopMultiTexCoord2iARB );
	FILLIN_OPT( "MultiTexCoord2ivARB", __findExtFunction(interface, "glMultiTexCoord2ivARB"), (SPUGenericFunction) NopMultiTexCoord2ivARB );
	FILLIN_OPT( "MultiTexCoord2sARB", __findExtFunction(interface, "glMultiTexCoord2sARB"), (SPUGenericFunction) NopMultiTexCoord2sARB );
	FILLIN_OPT( "MultiTexCoord2svARB", __findExtFunction(interface, "glMultiTexCoord2svARB"), (SPUGenericFunction) NopMultiTexCoord2svARB );
	FILLIN_OPT( "MultiTexCoord3dARB", __findExtFunction(interface, "glMultiTexCoord3dARB"), (SPUGenericFunction) NopMultiTexCoord3dARB );
	FILLIN_OPT( "MultiTexCoord3dvARB", __findExtFunction(interface, "glMultiTexCoord3dvARB"), (SPUGenericFunction) NopMultiTexCoord3dvARB );
	FILLIN_OPT( "MultiTexCoord3fARB", __findExtFunction(interface, "glMultiTexCoord3fARB"), (SPUGenericFunction) NopMultiTexCoord3fARB );
	FILLIN_OPT( "MultiTexCoord3fvARB", __findExtFunction(interface, "glMultiTexCoord3fvARB"), (SPUGenericFunction) NopMultiTexCoord3fvARB );
	FILLIN_OPT( "MultiTexCoord3iARB", __findExtFunction(interface, "glMultiTexCoord3iARB"), (SPUGenericFunction) NopMultiTexCoord3iARB );
	FILLIN_OPT( "MultiTexCoord3ivARB", __findExtFunction(interface, "glMultiTexCoord3ivARB"), (SPUGenericFunction) NopMultiTexCoord3ivARB );
	FILLIN_OPT( "MultiTexCoord3sARB", __findExtFunction(interface, "glMultiTexCoord3sARB"), (SPUGenericFunction) NopMultiTexCoord3sARB );
	FILLIN_OPT( "MultiTexCoord3svARB", __findExtFunction(interface, "glMultiTexCoord3svARB"), (SPUGenericFunction) NopMultiTexCoord3svARB );
	FILLIN_OPT( "MultiTexCoord4dARB", __findExtFunction(interface, "glMultiTexCoord4dARB"), (SPUGenericFunction) NopMultiTexCoord4dARB );
	FILLIN_OPT( "MultiTexCoord4dvARB", __findExtFunction(interface, "glMultiTexCoord4dvARB"), (SPUGenericFunction) NopMultiTexCoord4dvARB );
	FILLIN_OPT( "MultiTexCoord4fARB", __findExtFunction(interface, "glMultiTexCoord4fARB"), (SPUGenericFunction) NopMultiTexCoord4fARB );
	FILLIN_OPT( "MultiTexCoord4fvARB", __findExtFunction(interface, "glMultiTexCoord4fvARB"), (SPUGenericFunction) NopMultiTexCoord4fvARB );
	FILLIN_OPT( "MultiTexCoord4iARB", __findExtFunction(interface, "glMultiTexCoord4iARB"), (SPUGenericFunction) NopMultiTexCoord4iARB );
	FILLIN_OPT( "MultiTexCoord4ivARB", __findExtFunction(interface, "glMultiTexCoord4ivARB"), (SPUGenericFunction) NopMultiTexCoord4ivARB );
	FILLIN_OPT( "MultiTexCoord4sARB", __findExtFunction(interface, "glMultiTexCoord4sARB"), (SPUGenericFunction) NopMultiTexCoord4sARB );
	FILLIN_OPT( "MultiTexCoord4svARB", __findExtFunction(interface, "glMultiTexCoord4svARB"), (SPUGenericFunction) NopMultiTexCoord4svARB );
	FILLIN_OPT( "SecondaryColor3bEXT", __findExtFunction(interface, "glSecondaryColor3bEXT"), (SPUGenericFunction) NopSecondaryColor3bEXT );
	FILLIN_OPT( "SecondaryColor3bvEXT", __findExtFunction(interface, "glSecondaryColor3bvEXT"), (SPUGenericFunction) NopSecondaryColor3bvEXT );
	FILLIN_OPT( "SecondaryColor3dEXT", __findExtFunction(interface, "glSecondaryColor3dEXT"), (SPUGenericFunction) NopSecondaryColor3dEXT );
	FILLIN_OPT( "SecondaryColor3dvEXT", __findExtFunction(interface, "glSecondaryColor3dvEXT"), (SPUGenericFunction) NopSecondaryColor3dvEXT );
	FILLIN_OPT( "SecondaryColor3fEXT", __findExtFunction(interface, "glSecondaryColor3fEXT"), (SPUGenericFunction) NopSecondaryColor3fEXT );
	FILLIN_OPT( "SecondaryColor3fvEXT", __findExtFunction(interface, "glSecondaryColor3fvEXT"), (SPUGenericFunction) NopSecondaryColor3fvEXT );
	FILLIN_OPT( "SecondaryColor3iEXT", __findExtFunction(interface, "glSecondaryColor3iEXT"), (SPUGenericFunction) NopSecondaryColor3iEXT );
	FILLIN_OPT( "SecondaryColor3ivEXT", __findExtFunction(interface, "glSecondaryColor3ivEXT"), (SPUGenericFunction) NopSecondaryColor3ivEXT );
	FILLIN_OPT( "SecondaryColor3sEXT", __findExtFunction(interface, "glSecondaryColor3sEXT"), (SPUGenericFunction) NopSecondaryColor3sEXT );
	FILLIN_OPT( "SecondaryColor3svEXT", __findExtFunction(interface, "glSecondaryColor3svEXT"), (SPUGenericFunction) NopSecondaryColor3svEXT );
	FILLIN_OPT( "SecondaryColor3ubEXT", __findExtFunction(interface, "glSecondaryColor3ubEXT"), (SPUGenericFunction) NopSecondaryColor3ubEXT );
	FILLIN_OPT( "SecondaryColor3ubvEXT", __findExtFunction(interface, "glSecondaryColor3ubvEXT"), (SPUGenericFunction) NopSecondaryColor3ubvEXT );
	FILLIN_OPT( "SecondaryColor3uiEXT", __findExtFunction(interface, "glSecondaryColor3uiEXT"), (SPUGenericFunction) NopSecondaryColor3uiEXT );
	FILLIN_OPT( "SecondaryColor3uivEXT", __findExtFunction(interface, "glSecondaryColor3uivEXT"), (SPUGenericFunction) NopSecondaryColor3uivEXT );
	FILLIN_OPT( "SecondaryColor3usEXT", __findExtFunction(interface, "glSecondaryColor3usEXT"), (SPUGenericFunction) NopSecondaryColor3usEXT );
	FILLIN_OPT( "SecondaryColor3usvEXT", __findExtFunction(interface, "glSecondaryColor3usvEXT"), (SPUGenericFunction) NopSecondaryColor3usvEXT );
	FILLIN_OPT( "SecondaryColorPointerEXT", __findExtFunction(interface, "glSecondaryColorPointerEXT"), (SPUGenericFunction) NopSecondaryColorPointerEXT );

	/* end of list */
	entry->name = NULL;
	entry->fn = NULL;
	return entry - table;  /* number of entries filled */
}

