/* Copyright (c) 2001, Stanford University
	All rights reserved.

	See the file LICENSE.txt for information on redistributing this software. */
	


/* DO NOT EDIT - THIS FILE AUTOMATICALLY GENERATED BY spuchange.py SCRIPT */

#include "cr_spu.h"
#include "cr_error.h"

void crSPUChangeInterface( SPUDispatchTable *table, void *orig_func, void *new_func )
{
	struct _copy_list_node *temp;
	if (table->mark == 1)
	{
		return;
	}
	if (orig_func == new_func) 
	{
		return;
	}
	table->mark = 1;

	if (table->Accum == orig_func)
	{
		table->Accum = (AccumFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->ActiveTextureARB == orig_func)
	{
		table->ActiveTextureARB = (ActiveTextureARBFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->AlphaFunc == orig_func)
	{
		table->AlphaFunc = (AlphaFuncFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->AreTexturesResident == orig_func)
	{
		table->AreTexturesResident = (AreTexturesResidentFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->ArrayElement == orig_func)
	{
		table->ArrayElement = (ArrayElementFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->BarrierCreate == orig_func)
	{
		table->BarrierCreate = (BarrierCreateFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->BarrierDestroy == orig_func)
	{
		table->BarrierDestroy = (BarrierDestroyFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->BarrierExec == orig_func)
	{
		table->BarrierExec = (BarrierExecFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Begin == orig_func)
	{
		table->Begin = (BeginFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->BindTexture == orig_func)
	{
		table->BindTexture = (BindTextureFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Bitmap == orig_func)
	{
		table->Bitmap = (BitmapFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->BlendColorEXT == orig_func)
	{
		table->BlendColorEXT = (BlendColorEXTFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->BlendEquationEXT == orig_func)
	{
		table->BlendEquationEXT = (BlendEquationEXTFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->BlendFunc == orig_func)
	{
		table->BlendFunc = (BlendFuncFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->BoundsInfo == orig_func)
	{
		table->BoundsInfo = (BoundsInfoFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->CallList == orig_func)
	{
		table->CallList = (CallListFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->CallLists == orig_func)
	{
		table->CallLists = (CallListsFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->ChromiumParameterfCR == orig_func)
	{
		table->ChromiumParameterfCR = (ChromiumParameterfCRFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->ChromiumParameteriCR == orig_func)
	{
		table->ChromiumParameteriCR = (ChromiumParameteriCRFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->ChromiumParametervCR == orig_func)
	{
		table->ChromiumParametervCR = (ChromiumParametervCRFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Clear == orig_func)
	{
		table->Clear = (ClearFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->ClearAccum == orig_func)
	{
		table->ClearAccum = (ClearAccumFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->ClearColor == orig_func)
	{
		table->ClearColor = (ClearColorFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->ClearDepth == orig_func)
	{
		table->ClearDepth = (ClearDepthFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->ClearIndex == orig_func)
	{
		table->ClearIndex = (ClearIndexFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->ClearStencil == orig_func)
	{
		table->ClearStencil = (ClearStencilFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->ClientActiveTextureARB == orig_func)
	{
		table->ClientActiveTextureARB = (ClientActiveTextureARBFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->ClipPlane == orig_func)
	{
		table->ClipPlane = (ClipPlaneFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Color3b == orig_func)
	{
		table->Color3b = (Color3bFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Color3bv == orig_func)
	{
		table->Color3bv = (Color3bvFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Color3d == orig_func)
	{
		table->Color3d = (Color3dFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Color3dv == orig_func)
	{
		table->Color3dv = (Color3dvFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Color3f == orig_func)
	{
		table->Color3f = (Color3fFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Color3fv == orig_func)
	{
		table->Color3fv = (Color3fvFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Color3i == orig_func)
	{
		table->Color3i = (Color3iFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Color3iv == orig_func)
	{
		table->Color3iv = (Color3ivFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Color3s == orig_func)
	{
		table->Color3s = (Color3sFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Color3sv == orig_func)
	{
		table->Color3sv = (Color3svFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Color3ub == orig_func)
	{
		table->Color3ub = (Color3ubFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Color3ubv == orig_func)
	{
		table->Color3ubv = (Color3ubvFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Color3ui == orig_func)
	{
		table->Color3ui = (Color3uiFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Color3uiv == orig_func)
	{
		table->Color3uiv = (Color3uivFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Color3us == orig_func)
	{
		table->Color3us = (Color3usFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Color3usv == orig_func)
	{
		table->Color3usv = (Color3usvFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Color4b == orig_func)
	{
		table->Color4b = (Color4bFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Color4bv == orig_func)
	{
		table->Color4bv = (Color4bvFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Color4d == orig_func)
	{
		table->Color4d = (Color4dFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Color4dv == orig_func)
	{
		table->Color4dv = (Color4dvFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Color4f == orig_func)
	{
		table->Color4f = (Color4fFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Color4fv == orig_func)
	{
		table->Color4fv = (Color4fvFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Color4i == orig_func)
	{
		table->Color4i = (Color4iFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Color4iv == orig_func)
	{
		table->Color4iv = (Color4ivFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Color4s == orig_func)
	{
		table->Color4s = (Color4sFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Color4sv == orig_func)
	{
		table->Color4sv = (Color4svFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Color4ub == orig_func)
	{
		table->Color4ub = (Color4ubFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Color4ubv == orig_func)
	{
		table->Color4ubv = (Color4ubvFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Color4ui == orig_func)
	{
		table->Color4ui = (Color4uiFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Color4uiv == orig_func)
	{
		table->Color4uiv = (Color4uivFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Color4us == orig_func)
	{
		table->Color4us = (Color4usFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Color4usv == orig_func)
	{
		table->Color4usv = (Color4usvFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->ColorMask == orig_func)
	{
		table->ColorMask = (ColorMaskFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->ColorMaterial == orig_func)
	{
		table->ColorMaterial = (ColorMaterialFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->ColorPointer == orig_func)
	{
		table->ColorPointer = (ColorPointerFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->CombinerInputNV == orig_func)
	{
		table->CombinerInputNV = (CombinerInputNVFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->CombinerOutputNV == orig_func)
	{
		table->CombinerOutputNV = (CombinerOutputNVFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->CombinerParameterfNV == orig_func)
	{
		table->CombinerParameterfNV = (CombinerParameterfNVFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->CombinerParameterfvNV == orig_func)
	{
		table->CombinerParameterfvNV = (CombinerParameterfvNVFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->CombinerParameteriNV == orig_func)
	{
		table->CombinerParameteriNV = (CombinerParameteriNVFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->CombinerParameterivNV == orig_func)
	{
		table->CombinerParameterivNV = (CombinerParameterivNVFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->CombinerStageParameterfvNV == orig_func)
	{
		table->CombinerStageParameterfvNV = (CombinerStageParameterfvNVFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->CopyPixels == orig_func)
	{
		table->CopyPixels = (CopyPixelsFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->CopyTexImage1D == orig_func)
	{
		table->CopyTexImage1D = (CopyTexImage1DFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->CopyTexImage2D == orig_func)
	{
		table->CopyTexImage2D = (CopyTexImage2DFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->CopyTexSubImage1D == orig_func)
	{
		table->CopyTexSubImage1D = (CopyTexSubImage1DFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->CopyTexSubImage2D == orig_func)
	{
		table->CopyTexSubImage2D = (CopyTexSubImage2DFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->CreateContext == orig_func)
	{
		table->CreateContext = (CreateContextFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->CullFace == orig_func)
	{
		table->CullFace = (CullFaceFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->DeleteLists == orig_func)
	{
		table->DeleteLists = (DeleteListsFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->DeleteTextures == orig_func)
	{
		table->DeleteTextures = (DeleteTexturesFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->DepthFunc == orig_func)
	{
		table->DepthFunc = (DepthFuncFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->DepthMask == orig_func)
	{
		table->DepthMask = (DepthMaskFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->DepthRange == orig_func)
	{
		table->DepthRange = (DepthRangeFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->DestroyContext == orig_func)
	{
		table->DestroyContext = (DestroyContextFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Disable == orig_func)
	{
		table->Disable = (DisableFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->DisableClientState == orig_func)
	{
		table->DisableClientState = (DisableClientStateFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->DrawArrays == orig_func)
	{
		table->DrawArrays = (DrawArraysFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->DrawBuffer == orig_func)
	{
		table->DrawBuffer = (DrawBufferFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->DrawElements == orig_func)
	{
		table->DrawElements = (DrawElementsFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->DrawPixels == orig_func)
	{
		table->DrawPixels = (DrawPixelsFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->DrawRangeElements == orig_func)
	{
		table->DrawRangeElements = (DrawRangeElementsFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->EdgeFlag == orig_func)
	{
		table->EdgeFlag = (EdgeFlagFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->EdgeFlagPointer == orig_func)
	{
		table->EdgeFlagPointer = (EdgeFlagPointerFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->EdgeFlagv == orig_func)
	{
		table->EdgeFlagv = (EdgeFlagvFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Enable == orig_func)
	{
		table->Enable = (EnableFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->EnableClientState == orig_func)
	{
		table->EnableClientState = (EnableClientStateFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->End == orig_func)
	{
		table->End = (EndFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->EndList == orig_func)
	{
		table->EndList = (EndListFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->EvalCoord1d == orig_func)
	{
		table->EvalCoord1d = (EvalCoord1dFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->EvalCoord1dv == orig_func)
	{
		table->EvalCoord1dv = (EvalCoord1dvFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->EvalCoord1f == orig_func)
	{
		table->EvalCoord1f = (EvalCoord1fFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->EvalCoord1fv == orig_func)
	{
		table->EvalCoord1fv = (EvalCoord1fvFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->EvalCoord2d == orig_func)
	{
		table->EvalCoord2d = (EvalCoord2dFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->EvalCoord2dv == orig_func)
	{
		table->EvalCoord2dv = (EvalCoord2dvFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->EvalCoord2f == orig_func)
	{
		table->EvalCoord2f = (EvalCoord2fFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->EvalCoord2fv == orig_func)
	{
		table->EvalCoord2fv = (EvalCoord2fvFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->EvalMesh1 == orig_func)
	{
		table->EvalMesh1 = (EvalMesh1Func_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->EvalMesh2 == orig_func)
	{
		table->EvalMesh2 = (EvalMesh2Func_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->EvalPoint1 == orig_func)
	{
		table->EvalPoint1 = (EvalPoint1Func_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->EvalPoint2 == orig_func)
	{
		table->EvalPoint2 = (EvalPoint2Func_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->FeedbackBuffer == orig_func)
	{
		table->FeedbackBuffer = (FeedbackBufferFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->FinalCombinerInputNV == orig_func)
	{
		table->FinalCombinerInputNV = (FinalCombinerInputNVFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Finish == orig_func)
	{
		table->Finish = (FinishFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Flush == orig_func)
	{
		table->Flush = (FlushFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Fogf == orig_func)
	{
		table->Fogf = (FogfFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Fogfv == orig_func)
	{
		table->Fogfv = (FogfvFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Fogi == orig_func)
	{
		table->Fogi = (FogiFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Fogiv == orig_func)
	{
		table->Fogiv = (FogivFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->FrontFace == orig_func)
	{
		table->FrontFace = (FrontFaceFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Frustum == orig_func)
	{
		table->Frustum = (FrustumFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->GenLists == orig_func)
	{
		table->GenLists = (GenListsFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->GenTextures == orig_func)
	{
		table->GenTextures = (GenTexturesFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->GetBooleanv == orig_func)
	{
		table->GetBooleanv = (GetBooleanvFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->GetChromiumParametervCR == orig_func)
	{
		table->GetChromiumParametervCR = (GetChromiumParametervCRFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->GetClipPlane == orig_func)
	{
		table->GetClipPlane = (GetClipPlaneFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->GetCombinerInputParameterfvNV == orig_func)
	{
		table->GetCombinerInputParameterfvNV = (GetCombinerInputParameterfvNVFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->GetCombinerInputParameterivNV == orig_func)
	{
		table->GetCombinerInputParameterivNV = (GetCombinerInputParameterivNVFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->GetCombinerOutputParameterfvNV == orig_func)
	{
		table->GetCombinerOutputParameterfvNV = (GetCombinerOutputParameterfvNVFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->GetCombinerOutputParameterivNV == orig_func)
	{
		table->GetCombinerOutputParameterivNV = (GetCombinerOutputParameterivNVFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->GetCombinerStageParameterfvNV == orig_func)
	{
		table->GetCombinerStageParameterfvNV = (GetCombinerStageParameterfvNVFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->GetDoublev == orig_func)
	{
		table->GetDoublev = (GetDoublevFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->GetError == orig_func)
	{
		table->GetError = (GetErrorFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->GetFinalCombinerInputParameterfvNV == orig_func)
	{
		table->GetFinalCombinerInputParameterfvNV = (GetFinalCombinerInputParameterfvNVFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->GetFinalCombinerInputParameterivNV == orig_func)
	{
		table->GetFinalCombinerInputParameterivNV = (GetFinalCombinerInputParameterivNVFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->GetFloatv == orig_func)
	{
		table->GetFloatv = (GetFloatvFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->GetIntegerv == orig_func)
	{
		table->GetIntegerv = (GetIntegervFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->GetLightfv == orig_func)
	{
		table->GetLightfv = (GetLightfvFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->GetLightiv == orig_func)
	{
		table->GetLightiv = (GetLightivFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->GetMapdv == orig_func)
	{
		table->GetMapdv = (GetMapdvFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->GetMapfv == orig_func)
	{
		table->GetMapfv = (GetMapfvFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->GetMapiv == orig_func)
	{
		table->GetMapiv = (GetMapivFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->GetMaterialfv == orig_func)
	{
		table->GetMaterialfv = (GetMaterialfvFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->GetMaterialiv == orig_func)
	{
		table->GetMaterialiv = (GetMaterialivFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->GetPixelMapfv == orig_func)
	{
		table->GetPixelMapfv = (GetPixelMapfvFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->GetPixelMapuiv == orig_func)
	{
		table->GetPixelMapuiv = (GetPixelMapuivFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->GetPixelMapusv == orig_func)
	{
		table->GetPixelMapusv = (GetPixelMapusvFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->GetPointerv == orig_func)
	{
		table->GetPointerv = (GetPointervFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->GetPolygonStipple == orig_func)
	{
		table->GetPolygonStipple = (GetPolygonStippleFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->GetString == orig_func)
	{
		table->GetString = (GetStringFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->GetTexEnvfv == orig_func)
	{
		table->GetTexEnvfv = (GetTexEnvfvFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->GetTexEnviv == orig_func)
	{
		table->GetTexEnviv = (GetTexEnvivFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->GetTexGendv == orig_func)
	{
		table->GetTexGendv = (GetTexGendvFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->GetTexGenfv == orig_func)
	{
		table->GetTexGenfv = (GetTexGenfvFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->GetTexGeniv == orig_func)
	{
		table->GetTexGeniv = (GetTexGenivFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->GetTexImage == orig_func)
	{
		table->GetTexImage = (GetTexImageFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->GetTexLevelParameterfv == orig_func)
	{
		table->GetTexLevelParameterfv = (GetTexLevelParameterfvFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->GetTexLevelParameteriv == orig_func)
	{
		table->GetTexLevelParameteriv = (GetTexLevelParameterivFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->GetTexParameterfv == orig_func)
	{
		table->GetTexParameterfv = (GetTexParameterfvFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->GetTexParameteriv == orig_func)
	{
		table->GetTexParameteriv = (GetTexParameterivFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Hint == orig_func)
	{
		table->Hint = (HintFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->IndexMask == orig_func)
	{
		table->IndexMask = (IndexMaskFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->IndexPointer == orig_func)
	{
		table->IndexPointer = (IndexPointerFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Indexd == orig_func)
	{
		table->Indexd = (IndexdFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Indexdv == orig_func)
	{
		table->Indexdv = (IndexdvFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Indexf == orig_func)
	{
		table->Indexf = (IndexfFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Indexfv == orig_func)
	{
		table->Indexfv = (IndexfvFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Indexi == orig_func)
	{
		table->Indexi = (IndexiFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Indexiv == orig_func)
	{
		table->Indexiv = (IndexivFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Indexs == orig_func)
	{
		table->Indexs = (IndexsFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Indexsv == orig_func)
	{
		table->Indexsv = (IndexsvFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Indexub == orig_func)
	{
		table->Indexub = (IndexubFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Indexubv == orig_func)
	{
		table->Indexubv = (IndexubvFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->InitNames == orig_func)
	{
		table->InitNames = (InitNamesFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->InterleavedArrays == orig_func)
	{
		table->InterleavedArrays = (InterleavedArraysFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->IsEnabled == orig_func)
	{
		table->IsEnabled = (IsEnabledFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->IsList == orig_func)
	{
		table->IsList = (IsListFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->IsTexture == orig_func)
	{
		table->IsTexture = (IsTextureFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->LightModelf == orig_func)
	{
		table->LightModelf = (LightModelfFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->LightModelfv == orig_func)
	{
		table->LightModelfv = (LightModelfvFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->LightModeli == orig_func)
	{
		table->LightModeli = (LightModeliFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->LightModeliv == orig_func)
	{
		table->LightModeliv = (LightModelivFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Lightf == orig_func)
	{
		table->Lightf = (LightfFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Lightfv == orig_func)
	{
		table->Lightfv = (LightfvFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Lighti == orig_func)
	{
		table->Lighti = (LightiFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Lightiv == orig_func)
	{
		table->Lightiv = (LightivFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->LineStipple == orig_func)
	{
		table->LineStipple = (LineStippleFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->LineWidth == orig_func)
	{
		table->LineWidth = (LineWidthFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->ListBase == orig_func)
	{
		table->ListBase = (ListBaseFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->LoadIdentity == orig_func)
	{
		table->LoadIdentity = (LoadIdentityFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->LoadMatrixd == orig_func)
	{
		table->LoadMatrixd = (LoadMatrixdFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->LoadMatrixf == orig_func)
	{
		table->LoadMatrixf = (LoadMatrixfFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->LoadName == orig_func)
	{
		table->LoadName = (LoadNameFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->LogicOp == orig_func)
	{
		table->LogicOp = (LogicOpFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->MakeCurrent == orig_func)
	{
		table->MakeCurrent = (MakeCurrentFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Map1d == orig_func)
	{
		table->Map1d = (Map1dFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Map1f == orig_func)
	{
		table->Map1f = (Map1fFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Map2d == orig_func)
	{
		table->Map2d = (Map2dFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Map2f == orig_func)
	{
		table->Map2f = (Map2fFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->MapGrid1d == orig_func)
	{
		table->MapGrid1d = (MapGrid1dFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->MapGrid1f == orig_func)
	{
		table->MapGrid1f = (MapGrid1fFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->MapGrid2d == orig_func)
	{
		table->MapGrid2d = (MapGrid2dFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->MapGrid2f == orig_func)
	{
		table->MapGrid2f = (MapGrid2fFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Materialf == orig_func)
	{
		table->Materialf = (MaterialfFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Materialfv == orig_func)
	{
		table->Materialfv = (MaterialfvFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Materiali == orig_func)
	{
		table->Materiali = (MaterialiFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Materialiv == orig_func)
	{
		table->Materialiv = (MaterialivFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->MatrixMode == orig_func)
	{
		table->MatrixMode = (MatrixModeFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->MultMatrixd == orig_func)
	{
		table->MultMatrixd = (MultMatrixdFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->MultMatrixf == orig_func)
	{
		table->MultMatrixf = (MultMatrixfFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->MultiTexCoord1dARB == orig_func)
	{
		table->MultiTexCoord1dARB = (MultiTexCoord1dARBFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->MultiTexCoord1dvARB == orig_func)
	{
		table->MultiTexCoord1dvARB = (MultiTexCoord1dvARBFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->MultiTexCoord1fARB == orig_func)
	{
		table->MultiTexCoord1fARB = (MultiTexCoord1fARBFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->MultiTexCoord1fvARB == orig_func)
	{
		table->MultiTexCoord1fvARB = (MultiTexCoord1fvARBFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->MultiTexCoord1iARB == orig_func)
	{
		table->MultiTexCoord1iARB = (MultiTexCoord1iARBFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->MultiTexCoord1ivARB == orig_func)
	{
		table->MultiTexCoord1ivARB = (MultiTexCoord1ivARBFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->MultiTexCoord1sARB == orig_func)
	{
		table->MultiTexCoord1sARB = (MultiTexCoord1sARBFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->MultiTexCoord1svARB == orig_func)
	{
		table->MultiTexCoord1svARB = (MultiTexCoord1svARBFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->MultiTexCoord2dARB == orig_func)
	{
		table->MultiTexCoord2dARB = (MultiTexCoord2dARBFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->MultiTexCoord2dvARB == orig_func)
	{
		table->MultiTexCoord2dvARB = (MultiTexCoord2dvARBFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->MultiTexCoord2fARB == orig_func)
	{
		table->MultiTexCoord2fARB = (MultiTexCoord2fARBFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->MultiTexCoord2fvARB == orig_func)
	{
		table->MultiTexCoord2fvARB = (MultiTexCoord2fvARBFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->MultiTexCoord2iARB == orig_func)
	{
		table->MultiTexCoord2iARB = (MultiTexCoord2iARBFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->MultiTexCoord2ivARB == orig_func)
	{
		table->MultiTexCoord2ivARB = (MultiTexCoord2ivARBFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->MultiTexCoord2sARB == orig_func)
	{
		table->MultiTexCoord2sARB = (MultiTexCoord2sARBFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->MultiTexCoord2svARB == orig_func)
	{
		table->MultiTexCoord2svARB = (MultiTexCoord2svARBFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->MultiTexCoord3dARB == orig_func)
	{
		table->MultiTexCoord3dARB = (MultiTexCoord3dARBFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->MultiTexCoord3dvARB == orig_func)
	{
		table->MultiTexCoord3dvARB = (MultiTexCoord3dvARBFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->MultiTexCoord3fARB == orig_func)
	{
		table->MultiTexCoord3fARB = (MultiTexCoord3fARBFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->MultiTexCoord3fvARB == orig_func)
	{
		table->MultiTexCoord3fvARB = (MultiTexCoord3fvARBFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->MultiTexCoord3iARB == orig_func)
	{
		table->MultiTexCoord3iARB = (MultiTexCoord3iARBFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->MultiTexCoord3ivARB == orig_func)
	{
		table->MultiTexCoord3ivARB = (MultiTexCoord3ivARBFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->MultiTexCoord3sARB == orig_func)
	{
		table->MultiTexCoord3sARB = (MultiTexCoord3sARBFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->MultiTexCoord3svARB == orig_func)
	{
		table->MultiTexCoord3svARB = (MultiTexCoord3svARBFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->MultiTexCoord4dARB == orig_func)
	{
		table->MultiTexCoord4dARB = (MultiTexCoord4dARBFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->MultiTexCoord4dvARB == orig_func)
	{
		table->MultiTexCoord4dvARB = (MultiTexCoord4dvARBFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->MultiTexCoord4fARB == orig_func)
	{
		table->MultiTexCoord4fARB = (MultiTexCoord4fARBFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->MultiTexCoord4fvARB == orig_func)
	{
		table->MultiTexCoord4fvARB = (MultiTexCoord4fvARBFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->MultiTexCoord4iARB == orig_func)
	{
		table->MultiTexCoord4iARB = (MultiTexCoord4iARBFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->MultiTexCoord4ivARB == orig_func)
	{
		table->MultiTexCoord4ivARB = (MultiTexCoord4ivARBFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->MultiTexCoord4sARB == orig_func)
	{
		table->MultiTexCoord4sARB = (MultiTexCoord4sARBFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->MultiTexCoord4svARB == orig_func)
	{
		table->MultiTexCoord4svARB = (MultiTexCoord4svARBFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->NewList == orig_func)
	{
		table->NewList = (NewListFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Normal3b == orig_func)
	{
		table->Normal3b = (Normal3bFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Normal3bv == orig_func)
	{
		table->Normal3bv = (Normal3bvFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Normal3d == orig_func)
	{
		table->Normal3d = (Normal3dFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Normal3dv == orig_func)
	{
		table->Normal3dv = (Normal3dvFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Normal3f == orig_func)
	{
		table->Normal3f = (Normal3fFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Normal3fv == orig_func)
	{
		table->Normal3fv = (Normal3fvFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Normal3i == orig_func)
	{
		table->Normal3i = (Normal3iFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Normal3iv == orig_func)
	{
		table->Normal3iv = (Normal3ivFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Normal3s == orig_func)
	{
		table->Normal3s = (Normal3sFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Normal3sv == orig_func)
	{
		table->Normal3sv = (Normal3svFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->NormalPointer == orig_func)
	{
		table->NormalPointer = (NormalPointerFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Ortho == orig_func)
	{
		table->Ortho = (OrthoFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->PassThrough == orig_func)
	{
		table->PassThrough = (PassThroughFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->PixelMapfv == orig_func)
	{
		table->PixelMapfv = (PixelMapfvFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->PixelMapuiv == orig_func)
	{
		table->PixelMapuiv = (PixelMapuivFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->PixelMapusv == orig_func)
	{
		table->PixelMapusv = (PixelMapusvFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->PixelStoref == orig_func)
	{
		table->PixelStoref = (PixelStorefFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->PixelStorei == orig_func)
	{
		table->PixelStorei = (PixelStoreiFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->PixelTransferf == orig_func)
	{
		table->PixelTransferf = (PixelTransferfFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->PixelTransferi == orig_func)
	{
		table->PixelTransferi = (PixelTransferiFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->PixelZoom == orig_func)
	{
		table->PixelZoom = (PixelZoomFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->PointSize == orig_func)
	{
		table->PointSize = (PointSizeFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->PolygonMode == orig_func)
	{
		table->PolygonMode = (PolygonModeFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->PolygonOffset == orig_func)
	{
		table->PolygonOffset = (PolygonOffsetFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->PolygonStipple == orig_func)
	{
		table->PolygonStipple = (PolygonStippleFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->PopAttrib == orig_func)
	{
		table->PopAttrib = (PopAttribFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->PopClientAttrib == orig_func)
	{
		table->PopClientAttrib = (PopClientAttribFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->PopMatrix == orig_func)
	{
		table->PopMatrix = (PopMatrixFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->PopName == orig_func)
	{
		table->PopName = (PopNameFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->PrioritizeTextures == orig_func)
	{
		table->PrioritizeTextures = (PrioritizeTexturesFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->PushAttrib == orig_func)
	{
		table->PushAttrib = (PushAttribFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->PushClientAttrib == orig_func)
	{
		table->PushClientAttrib = (PushClientAttribFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->PushMatrix == orig_func)
	{
		table->PushMatrix = (PushMatrixFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->PushName == orig_func)
	{
		table->PushName = (PushNameFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->RasterPos2d == orig_func)
	{
		table->RasterPos2d = (RasterPos2dFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->RasterPos2dv == orig_func)
	{
		table->RasterPos2dv = (RasterPos2dvFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->RasterPos2f == orig_func)
	{
		table->RasterPos2f = (RasterPos2fFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->RasterPos2fv == orig_func)
	{
		table->RasterPos2fv = (RasterPos2fvFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->RasterPos2i == orig_func)
	{
		table->RasterPos2i = (RasterPos2iFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->RasterPos2iv == orig_func)
	{
		table->RasterPos2iv = (RasterPos2ivFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->RasterPos2s == orig_func)
	{
		table->RasterPos2s = (RasterPos2sFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->RasterPos2sv == orig_func)
	{
		table->RasterPos2sv = (RasterPos2svFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->RasterPos3d == orig_func)
	{
		table->RasterPos3d = (RasterPos3dFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->RasterPos3dv == orig_func)
	{
		table->RasterPos3dv = (RasterPos3dvFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->RasterPos3f == orig_func)
	{
		table->RasterPos3f = (RasterPos3fFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->RasterPos3fv == orig_func)
	{
		table->RasterPos3fv = (RasterPos3fvFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->RasterPos3i == orig_func)
	{
		table->RasterPos3i = (RasterPos3iFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->RasterPos3iv == orig_func)
	{
		table->RasterPos3iv = (RasterPos3ivFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->RasterPos3s == orig_func)
	{
		table->RasterPos3s = (RasterPos3sFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->RasterPos3sv == orig_func)
	{
		table->RasterPos3sv = (RasterPos3svFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->RasterPos4d == orig_func)
	{
		table->RasterPos4d = (RasterPos4dFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->RasterPos4dv == orig_func)
	{
		table->RasterPos4dv = (RasterPos4dvFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->RasterPos4f == orig_func)
	{
		table->RasterPos4f = (RasterPos4fFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->RasterPos4fv == orig_func)
	{
		table->RasterPos4fv = (RasterPos4fvFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->RasterPos4i == orig_func)
	{
		table->RasterPos4i = (RasterPos4iFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->RasterPos4iv == orig_func)
	{
		table->RasterPos4iv = (RasterPos4ivFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->RasterPos4s == orig_func)
	{
		table->RasterPos4s = (RasterPos4sFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->RasterPos4sv == orig_func)
	{
		table->RasterPos4sv = (RasterPos4svFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->ReadBuffer == orig_func)
	{
		table->ReadBuffer = (ReadBufferFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->ReadPixels == orig_func)
	{
		table->ReadPixels = (ReadPixelsFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Rectd == orig_func)
	{
		table->Rectd = (RectdFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Rectdv == orig_func)
	{
		table->Rectdv = (RectdvFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Rectf == orig_func)
	{
		table->Rectf = (RectfFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Rectfv == orig_func)
	{
		table->Rectfv = (RectfvFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Recti == orig_func)
	{
		table->Recti = (RectiFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Rectiv == orig_func)
	{
		table->Rectiv = (RectivFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Rects == orig_func)
	{
		table->Rects = (RectsFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Rectsv == orig_func)
	{
		table->Rectsv = (RectsvFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->RenderMode == orig_func)
	{
		table->RenderMode = (RenderModeFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Rotated == orig_func)
	{
		table->Rotated = (RotatedFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Rotatef == orig_func)
	{
		table->Rotatef = (RotatefFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Scaled == orig_func)
	{
		table->Scaled = (ScaledFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Scalef == orig_func)
	{
		table->Scalef = (ScalefFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Scissor == orig_func)
	{
		table->Scissor = (ScissorFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->SecondaryColor3bEXT == orig_func)
	{
		table->SecondaryColor3bEXT = (SecondaryColor3bEXTFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->SecondaryColor3bvEXT == orig_func)
	{
		table->SecondaryColor3bvEXT = (SecondaryColor3bvEXTFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->SecondaryColor3dEXT == orig_func)
	{
		table->SecondaryColor3dEXT = (SecondaryColor3dEXTFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->SecondaryColor3dvEXT == orig_func)
	{
		table->SecondaryColor3dvEXT = (SecondaryColor3dvEXTFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->SecondaryColor3fEXT == orig_func)
	{
		table->SecondaryColor3fEXT = (SecondaryColor3fEXTFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->SecondaryColor3fvEXT == orig_func)
	{
		table->SecondaryColor3fvEXT = (SecondaryColor3fvEXTFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->SecondaryColor3iEXT == orig_func)
	{
		table->SecondaryColor3iEXT = (SecondaryColor3iEXTFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->SecondaryColor3ivEXT == orig_func)
	{
		table->SecondaryColor3ivEXT = (SecondaryColor3ivEXTFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->SecondaryColor3sEXT == orig_func)
	{
		table->SecondaryColor3sEXT = (SecondaryColor3sEXTFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->SecondaryColor3svEXT == orig_func)
	{
		table->SecondaryColor3svEXT = (SecondaryColor3svEXTFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->SecondaryColor3ubEXT == orig_func)
	{
		table->SecondaryColor3ubEXT = (SecondaryColor3ubEXTFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->SecondaryColor3ubvEXT == orig_func)
	{
		table->SecondaryColor3ubvEXT = (SecondaryColor3ubvEXTFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->SecondaryColor3uiEXT == orig_func)
	{
		table->SecondaryColor3uiEXT = (SecondaryColor3uiEXTFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->SecondaryColor3uivEXT == orig_func)
	{
		table->SecondaryColor3uivEXT = (SecondaryColor3uivEXTFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->SecondaryColor3usEXT == orig_func)
	{
		table->SecondaryColor3usEXT = (SecondaryColor3usEXTFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->SecondaryColor3usvEXT == orig_func)
	{
		table->SecondaryColor3usvEXT = (SecondaryColor3usvEXTFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->SecondaryColorPointerEXT == orig_func)
	{
		table->SecondaryColorPointerEXT = (SecondaryColorPointerEXTFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->SelectBuffer == orig_func)
	{
		table->SelectBuffer = (SelectBufferFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->SemaphoreCreate == orig_func)
	{
		table->SemaphoreCreate = (SemaphoreCreateFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->SemaphoreDestroy == orig_func)
	{
		table->SemaphoreDestroy = (SemaphoreDestroyFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->SemaphoreP == orig_func)
	{
		table->SemaphoreP = (SemaphorePFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->SemaphoreV == orig_func)
	{
		table->SemaphoreV = (SemaphoreVFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->ShadeModel == orig_func)
	{
		table->ShadeModel = (ShadeModelFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->StencilFunc == orig_func)
	{
		table->StencilFunc = (StencilFuncFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->StencilMask == orig_func)
	{
		table->StencilMask = (StencilMaskFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->StencilOp == orig_func)
	{
		table->StencilOp = (StencilOpFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->SwapBuffers == orig_func)
	{
		table->SwapBuffers = (SwapBuffersFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->TexCoord1d == orig_func)
	{
		table->TexCoord1d = (TexCoord1dFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->TexCoord1dv == orig_func)
	{
		table->TexCoord1dv = (TexCoord1dvFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->TexCoord1f == orig_func)
	{
		table->TexCoord1f = (TexCoord1fFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->TexCoord1fv == orig_func)
	{
		table->TexCoord1fv = (TexCoord1fvFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->TexCoord1i == orig_func)
	{
		table->TexCoord1i = (TexCoord1iFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->TexCoord1iv == orig_func)
	{
		table->TexCoord1iv = (TexCoord1ivFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->TexCoord1s == orig_func)
	{
		table->TexCoord1s = (TexCoord1sFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->TexCoord1sv == orig_func)
	{
		table->TexCoord1sv = (TexCoord1svFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->TexCoord2d == orig_func)
	{
		table->TexCoord2d = (TexCoord2dFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->TexCoord2dv == orig_func)
	{
		table->TexCoord2dv = (TexCoord2dvFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->TexCoord2f == orig_func)
	{
		table->TexCoord2f = (TexCoord2fFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->TexCoord2fv == orig_func)
	{
		table->TexCoord2fv = (TexCoord2fvFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->TexCoord2i == orig_func)
	{
		table->TexCoord2i = (TexCoord2iFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->TexCoord2iv == orig_func)
	{
		table->TexCoord2iv = (TexCoord2ivFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->TexCoord2s == orig_func)
	{
		table->TexCoord2s = (TexCoord2sFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->TexCoord2sv == orig_func)
	{
		table->TexCoord2sv = (TexCoord2svFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->TexCoord3d == orig_func)
	{
		table->TexCoord3d = (TexCoord3dFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->TexCoord3dv == orig_func)
	{
		table->TexCoord3dv = (TexCoord3dvFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->TexCoord3f == orig_func)
	{
		table->TexCoord3f = (TexCoord3fFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->TexCoord3fv == orig_func)
	{
		table->TexCoord3fv = (TexCoord3fvFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->TexCoord3i == orig_func)
	{
		table->TexCoord3i = (TexCoord3iFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->TexCoord3iv == orig_func)
	{
		table->TexCoord3iv = (TexCoord3ivFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->TexCoord3s == orig_func)
	{
		table->TexCoord3s = (TexCoord3sFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->TexCoord3sv == orig_func)
	{
		table->TexCoord3sv = (TexCoord3svFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->TexCoord4d == orig_func)
	{
		table->TexCoord4d = (TexCoord4dFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->TexCoord4dv == orig_func)
	{
		table->TexCoord4dv = (TexCoord4dvFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->TexCoord4f == orig_func)
	{
		table->TexCoord4f = (TexCoord4fFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->TexCoord4fv == orig_func)
	{
		table->TexCoord4fv = (TexCoord4fvFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->TexCoord4i == orig_func)
	{
		table->TexCoord4i = (TexCoord4iFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->TexCoord4iv == orig_func)
	{
		table->TexCoord4iv = (TexCoord4ivFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->TexCoord4s == orig_func)
	{
		table->TexCoord4s = (TexCoord4sFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->TexCoord4sv == orig_func)
	{
		table->TexCoord4sv = (TexCoord4svFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->TexCoordPointer == orig_func)
	{
		table->TexCoordPointer = (TexCoordPointerFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->TexEnvf == orig_func)
	{
		table->TexEnvf = (TexEnvfFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->TexEnvfv == orig_func)
	{
		table->TexEnvfv = (TexEnvfvFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->TexEnvi == orig_func)
	{
		table->TexEnvi = (TexEnviFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->TexEnviv == orig_func)
	{
		table->TexEnviv = (TexEnvivFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->TexGend == orig_func)
	{
		table->TexGend = (TexGendFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->TexGendv == orig_func)
	{
		table->TexGendv = (TexGendvFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->TexGenf == orig_func)
	{
		table->TexGenf = (TexGenfFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->TexGenfv == orig_func)
	{
		table->TexGenfv = (TexGenfvFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->TexGeni == orig_func)
	{
		table->TexGeni = (TexGeniFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->TexGeniv == orig_func)
	{
		table->TexGeniv = (TexGenivFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->TexImage1D == orig_func)
	{
		table->TexImage1D = (TexImage1DFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->TexImage2D == orig_func)
	{
		table->TexImage2D = (TexImage2DFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->TexParameterf == orig_func)
	{
		table->TexParameterf = (TexParameterfFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->TexParameterfv == orig_func)
	{
		table->TexParameterfv = (TexParameterfvFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->TexParameteri == orig_func)
	{
		table->TexParameteri = (TexParameteriFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->TexParameteriv == orig_func)
	{
		table->TexParameteriv = (TexParameterivFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->TexSubImage1D == orig_func)
	{
		table->TexSubImage1D = (TexSubImage1DFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->TexSubImage2D == orig_func)
	{
		table->TexSubImage2D = (TexSubImage2DFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Translated == orig_func)
	{
		table->Translated = (TranslatedFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Translatef == orig_func)
	{
		table->Translatef = (TranslatefFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Vertex2d == orig_func)
	{
		table->Vertex2d = (Vertex2dFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Vertex2dv == orig_func)
	{
		table->Vertex2dv = (Vertex2dvFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Vertex2f == orig_func)
	{
		table->Vertex2f = (Vertex2fFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Vertex2fv == orig_func)
	{
		table->Vertex2fv = (Vertex2fvFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Vertex2i == orig_func)
	{
		table->Vertex2i = (Vertex2iFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Vertex2iv == orig_func)
	{
		table->Vertex2iv = (Vertex2ivFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Vertex2s == orig_func)
	{
		table->Vertex2s = (Vertex2sFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Vertex2sv == orig_func)
	{
		table->Vertex2sv = (Vertex2svFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Vertex3d == orig_func)
	{
		table->Vertex3d = (Vertex3dFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Vertex3dv == orig_func)
	{
		table->Vertex3dv = (Vertex3dvFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Vertex3f == orig_func)
	{
		table->Vertex3f = (Vertex3fFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Vertex3fv == orig_func)
	{
		table->Vertex3fv = (Vertex3fvFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Vertex3i == orig_func)
	{
		table->Vertex3i = (Vertex3iFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Vertex3iv == orig_func)
	{
		table->Vertex3iv = (Vertex3ivFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Vertex3s == orig_func)
	{
		table->Vertex3s = (Vertex3sFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Vertex3sv == orig_func)
	{
		table->Vertex3sv = (Vertex3svFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Vertex4d == orig_func)
	{
		table->Vertex4d = (Vertex4dFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Vertex4dv == orig_func)
	{
		table->Vertex4dv = (Vertex4dvFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Vertex4f == orig_func)
	{
		table->Vertex4f = (Vertex4fFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Vertex4fv == orig_func)
	{
		table->Vertex4fv = (Vertex4fvFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Vertex4i == orig_func)
	{
		table->Vertex4i = (Vertex4iFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Vertex4iv == orig_func)
	{
		table->Vertex4iv = (Vertex4ivFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Vertex4s == orig_func)
	{
		table->Vertex4s = (Vertex4sFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Vertex4sv == orig_func)
	{
		table->Vertex4sv = (Vertex4svFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->VertexPointer == orig_func)
	{
		table->VertexPointer = (VertexPointerFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Viewport == orig_func)
	{
		table->Viewport = (ViewportFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}
	if (table->Writeback == orig_func)
	{
		table->Writeback = (WritebackFunc_t)new_func;
		for (temp = table->copyList ; temp ; temp = temp->next)
		{
			crSPUChangeInterface( temp->copy, orig_func, new_func );
		}
	}

	if (table->copy_of != NULL)
	{
		crSPUChangeInterface( table->copy_of, orig_func, new_func );
	}
	for (temp = table->copyList ; temp ; temp = temp->next)
	{
		crSPUChangeInterface( temp->copy, orig_func, new_func );
	}
	table->mark = 0;

}
