# Written By Dale Beermann (beermann@cs.virginia.edu)

TOP = ..

PROGRAM = crutproxy
FILES = main

PRECOMP = 
SLOP = ${PRECOMP}

ifndef WINDOWS
LIBRARIES = crutil crmothership crutapi
endif

include $(TOP)/cr.mk
