# Copyright (c) 2001, Stanford University
# All rights reserved.
#
# See the file LICENSE.txt for information on redistributing this software.

import sys

sys.path.append( "../../glapi_parser" )
import apiutil

keys = apiutil.GetDispatchedFunctions("../../glapi_parser/APIspec.txt")

apiutil.CopyrightC()

print """
/* DO NOT EDIT - THIS FILE GENERATED BY THE stateapi.py SCRIPT */
#include "cr_spu.h"
#include "cr_packfunctions.h"
#include "replicatespu.h"
#include "replicatespu_proto.h"

void replicatespuCreateStateAPI( void )
{
"""

for func_name in keys:
	# These functions are special to the state API
	if func_name in ['CallList', 'CallLists']:
	    print '\treplicate_spu.state_dispatch.%s = (%sFunc_t) replicatespu_State%s;' % (func_name, func_name, func_name)
	elif apiutil.SetsTrackedState(func_name):
	    print '\treplicate_spu.state_dispatch.%s = (%sFunc_t) crState%s;' % (func_name, func_name, func_name)
	else:
	    print '\treplicate_spu.state_dispatch.%s = NULL;' % (func_name)
print '}'
