# Copyright (c) 2001, Stanford University
# All rights reserved.
#
# See the file LICENSE.txt for information on redistributing this software.

TOP = ../../..

PROGRAM = ARB_multitexture
OPENGL = 1
GLUT = 1

FILES = main 
LIBRARIES = crutil crextensionscommon

include ${TOP}/cr.mk
