# Copyright (c) 2001, Stanford University
# All rights reserved.
#
# See the file LICENSE.txt for information on redistributing this software.

TOP = ../..
PROGRAM = statecopytest
FILES = statecopytest
TRACKS_STATE = 1

LIBRARIES = crutil

include ${TOP}/cr.mk
