# Copyright (c) 2001, Stanford University
# All rights reserved.
#
# See the file LICENSE.txt for information on redistributing this software.

TOP = ../..

PROGRAM = fonttest
OPENGL = 1
GLUT = 1

FILES = fonttest

LDFLAGS = -rdynamic

include ${TOP}/cr.mk
