TOP = ../..

SUBDIRS = common \
	ARB_multitexture \
	ARB_multitexture2 \
	EXT_blend_color \
	EXT_blend_minmax \
	EXT_blend_subtract \
	EXT_texture_edge_clamp \
	EXT_texture_filter_anisotropic \
	NV_fog_distance

include ${TOP}/cr.mk
