# Copyright (c) 2001, Stanford University
# All rights reserved.
#
# See the file LICENSE.txt for information on redistributing this software.

TOP = ../..

MOTHERSHIP=1

include ${TOP}/arch.mk

SHARED = 1
LIBRARY = crmothership
LIBRARIES = crutil
FILES = client
LIB_DEFS = client.def

include $(TOP)/cr.mk
