# Copyright (c) 2001, Stanford University
# All rights reserved.
#
# See the file LICENSE.txt for information on redistributing this software.

TOP = ../../..

PROGRAM = ARB_texture_cube_map
OPENGL = 1
GLUT = 1
MATH = 1

FILES = exec main
LIBRARIES = crutil crextensionscommon

include ${TOP}/cr.mk
