TOP = ../..

SHARED = 1
LIBRARY = templatespu
FILES = templatespu \
	templatespu_config \
	templatespu_init

LIBRARIES = spuload crutil crmothership

SLOP = $(PRECOMP)

LIB_DEFS += templatespu.def
include ${TOP}/cr.mk
