# Copyright (c) 2001, Stanford University
# All rights reserved.
#
# See the file LICENSE.txt for information on redistributing this software.

# This function generates a prototype for each special function

import sys
sys.path.append( "../../glapi_parser" )
import apiutil

apiutil.CopyrightC()

print """
/* DO NOT EDIT - THIS FILE AUTOMATICALLY GENERATED BY templatespu_proto.py SCRIPT */

#ifndef TEMPLATESPU_FUNCTIONS_H
#define TEMPLATESPU_FUNCTIONS_H 1
"""

# make apiutil load the GL function info
d = apiutil.GetFunctionDict("../../glapi_parser/APIspec.txt")

# Emit a C prototype for each special function
functions = apiutil.AllSpecials("template")
for func_name in functions:
	return_type = apiutil.ReturnType(func_name)
	params = apiutil.Parameters(func_name)
	print 'extern %s TEMPLATESPU_APIENTRY templatespu%s( %s );' % ( return_type, func_name, apiutil.MakeDeclarationString(params) )

print "#endif"

