/* Copyright (c) 2001, Stanford University
	All rights reserved.

	See the file LICENSE.txt for information on redistributing this software. */
	
/* DO NOT EDIT - THIS FILE GENERATED BY THE opcodes.py SCRIPT */



#define GL_GLEXT_PROTOTYPES
#include <GL/gl.h>
#include <GL/glext.h>
#include <GL/glut.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "chromium.h"
#include "cr_error.h"
#include "packertest.h"

extern int errChk;
extern int verbose;
void printError(char *name);

void crPackTestDeleteFencesNV(void)
{
	GLubyte fences[100000];/* VECP2 */
	crDebug ( "DeleteFencesNV is a stub and needs to be special cased  0!");
	return;
	glDeleteFencesNV((unsigned) 10, 	(const GLuint *)fences /* VEC3 */
);
	if(errChk)
		printError("glDeleteFencesNV((unsigned) 10, )");
	if (verbose)
		crDebug("glDeleteFencesNV( (unsigned) 10,  )");
}
void crPackTestGenFencesNV(void)
{
	GLubyte fences[100000];/* VECP */
	crDebug ( "GenFencesNV is a stub and needs to be special cased  1!");
	return;
	glGenFencesNV((unsigned) 10, 	(GLuint *)fences /* VEC3 */
);
	if(errChk)
		printError("glGenFencesNV((unsigned) 10, )");
	if (verbose)
		crDebug("glGenFencesNV( (unsigned) 10,  )");
}
void crPackTestGetFenceivNV(void)
{
	GLubyte params[100000];/* VECP */
	crDebug ( "GetFenceivNV is a stub and needs to be special cased  1!");
	return;
	glGetFenceivNV((unsigned) 3, GL_FENCE_STATUS_NV, 	(GLint *)params /* VEC3 */
);
	if(errChk)
		printError("glGetFenceivNV((unsigned) 3, GL_FENCE_STATUS_NV, )");
	if (verbose)
		crDebug("glGetFenceivNV( (unsigned) 3, GL_FENCE_STATUS_NV,  )");
	glGetFenceivNV((unsigned) 3, GL_FENCE_CONDITION_NV, 	(GLint *)params /* VEC3 */
);
	if(errChk)
		printError("glGetFenceivNV((unsigned) 3, GL_FENCE_CONDITION_NV, )");
	if (verbose)
		crDebug("glGetFenceivNV( (unsigned) 3, GL_FENCE_CONDITION_NV,  )");
}
void crPackTestIsFenceNV(void)
{
	GLboolean return_val;
	crDebug ( "IsFenceNV is a stub and needs to be special cased  1!");
	return;
	return_val = glIsFenceNV((unsigned) 3);
	if(errChk)
		printError("glIsFenceNV((unsigned) 3)");
	if (verbose)
		crDebug("glIsFenceNV( (unsigned) 3 )");
}
void crPackTestTestFenceNV(void)
{
	GLboolean return_val;
	crDebug ( "TestFenceNV is a stub and needs to be special cased  1!");
	return;
	return_val = glTestFenceNV((unsigned) 3);
	if(errChk)
		printError("glTestFenceNV((unsigned) 3)");
	if (verbose)
		crDebug("glTestFenceNV( (unsigned) 3 )");
}
