/* Copyright (c) 2001, Stanford University
	All rights reserved.

	See the file LICENSE.txt for information on redistributing this software. */
	
/* DO NOT EDIT - THIS FILE GENERATED BY THE opcodes.py SCRIPT */



#define GL_GLEXT_PROTOTYPES
#include <GL/gl.h>
#include <GL/glext.h>
#include <GL/glut.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "chromium.h"
#include "cr_error.h"
#include "packertest.h"

int errChk;
int verbose;
void printError(char *name);

void crPackTestSwapBuffers(void)
{
	crDebug ( "SwapBuffers is a stub and needs to be special cased  0!");
	return;
	glSwapBuffers((int) 1, (int) 1);
	if(errChk)
		printError("glSwapBuffers((int) 1, (int) 1)");
	if (verbose)
		crDebug("glSwapBuffers( (int) 1, (int) 1 )");
}
void crPackTestCreateContext(void)
{
	GLubyte dpyName[100000];/* VECP */
	GLint return_val;
	crDebug ( "CreateContext is a stub and needs to be special cased  1!");
	return;
	return_val = glCreateContext(	(const char *)dpyName /* VEC3 */
, (int) 1);
	if(errChk)
		printError("glCreateContext(, (int) 1)");
	if (verbose)
		crDebug("glCreateContext( , (int) 1 )");
}
void crPackTestDestroyContext(void)
{
	crDebug ( "DestroyContext is a stub and needs to be special cased  0!");
	return;
	glDestroyContext((int) 1);
	if(errChk)
		printError("glDestroyContext((int) 1)");
	if (verbose)
		crDebug("glDestroyContext( (int) 1 )");
}
void crPackTestMakeCurrent(void)
{
	crDebug ( "MakeCurrent is a stub and needs to be special cased  0!");
	return;
	glMakeCurrent((int) 1, (int) 1, (int) 1);
	if(errChk)
		printError("glMakeCurrent((int) 1, (int) 1, (int) 1)");
	if (verbose)
		crDebug("glMakeCurrent( (int) 1, (int) 1, (int) 1 )");
}
void crPackTestWindowCreate(void)
{
	GLubyte dpyName[100000];/* VECP */
	GLint return_val;
	crDebug ( "WindowCreate is a stub and needs to be special cased  1!");
	return;
	return_val = glWindowCreate(	(const char *)dpyName /* VEC3 */
, (int) 1);
	if(errChk)
		printError("glWindowCreate(, (int) 1)");
	if (verbose)
		crDebug("glWindowCreate( , (int) 1 )");
}
void crPackTestWindowDestroy(void)
{
	crDebug ( "WindowDestroy is a stub and needs to be special cased  0!");
	return;
	glWindowDestroy((int) 1);
	if(errChk)
		printError("glWindowDestroy((int) 1)");
	if (verbose)
		crDebug("glWindowDestroy( (int) 1 )");
}
void crPackTestWindowPosition(void)
{
	crDebug ( "WindowPosition is a stub and needs to be special cased  0!");
	return;
	glWindowPosition((int) 1, (int) 1, (int) 1);
	if(errChk)
		printError("glWindowPosition((int) 1, (int) 1, (int) 1)");
	if (verbose)
		crDebug("glWindowPosition( (int) 1, (int) 1, (int) 1 )");
}
void crPackTestWindowShow(void)
{
	crDebug ( "WindowShow is a stub and needs to be special cased  0!");
	return;
	glWindowShow((int) 1, (int) 1);
	if(errChk)
		printError("glWindowShow((int) 1, (int) 1)");
	if (verbose)
		crDebug("glWindowShow( (int) 1, (int) 1 )");
}
void crPackTestWindowSize(void)
{
	crDebug ( "WindowSize is a stub and needs to be special cased  0!");
	return;
	glWindowSize((int) 1, (int) 1, (int) 1);
	if(errChk)
		printError("glWindowSize((int) 1, (int) 1, (int) 1)");
	if (verbose)
		crDebug("glWindowSize( (int) 1, (int) 1, (int) 1 )");
}
void crPackTestWriteback(void)
{
	GLubyte writeback[100000];/* VECP */
	crDebug ( "Writeback is a stub and needs to be special cased  1!");
	return;
	glWriteback(	(GLint *)writeback /* VEC3 */
);
	if(errChk)
		printError("glWriteback()");
	if (verbose)
		crDebug("glWriteback(  )");
}
