/* Copyright (c) 2001, Stanford University
	All rights reserved.

	See the file LICENSE.txt for information on redistributing this software. */
	
/* DO NOT EDIT - THIS FILE GENERATED BY THE opcodes.py SCRIPT */



#define GL_GLEXT_PROTOTYPES
#include <GL/gl.h>
#include <GL/glext.h>
#include <GL/glut.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "chromium.h"
#include "cr_error.h"
#include "packertest.h"

extern int errChk;
extern int verbose;
void printError(char *name);

void crPackTestAreProgramsResidentNV(void)
{
	GLubyte ids[100000];/* VECP */
	GLubyte residences[100000];/* VECP */
	GLboolean return_val;
	crDebug ( "AreProgramsResidentNV is a stub and needs to be special cased  1!");
	return;
	return_val = glAreProgramsResidentNV((unsigned) 10, 	(const GLuint *)ids /* VEC3 */
, 	(GLboolean *)residences /* VEC3 */
);
	if(errChk)
		printError("glAreProgramsResidentNV((unsigned) 10, , )");
	if (verbose)
		crDebug("glAreProgramsResidentNV( (unsigned) 10, ,  )");
}
void crPackTestExecuteProgramNV(void)
{
	GLubyte params[100000];/* VECP2 */
	crDebug ( "ExecuteProgramNV is a stub and needs to be special cased  0!");
	return;
	glExecuteProgramNV(GL_VERTEX_PROGRAM_NV, (unsigned) 3, 	(const GLfloat *)params /* VEC3 */
);
	if(errChk)
		printError("glExecuteProgramNV(GL_VERTEX_PROGRAM_NV, (unsigned) 3, )");
	if (verbose)
		crDebug("glExecuteProgramNV( GL_VERTEX_PROGRAM_NV, (unsigned) 3,  )");
	glExecuteProgramNV(GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, 	(const GLfloat *)params /* VEC3 */
);
	if(errChk)
		printError("glExecuteProgramNV(GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, )");
	if (verbose)
		crDebug("glExecuteProgramNV( GL_FRAGMENT_PROGRAM_NV, (unsigned) 3,  )");
}
void crPackTestGenProgramsNV(void)
{
	GLubyte ids[100000];/* VECP */
	crDebug ( "GenProgramsNV is a stub and needs to be special cased  1!");
	return;
	glGenProgramsNV((unsigned) 10, 	(GLuint *)ids /* VEC3 */
);
	if(errChk)
		printError("glGenProgramsNV((unsigned) 10, )");
	if (verbose)
		crDebug("glGenProgramsNV( (unsigned) 10,  )");
}
void crPackTestGetProgramivNV(void)
{
	GLubyte params[100000];/* VECP */
	crDebug ( "GetProgramivNV is a stub and needs to be special cased  1!");
	return;
	glGetProgramivNV((unsigned) 3, 3, 	(GLint *)params /* VEC3 */
);
	if(errChk)
		printError("glGetProgramivNV((unsigned) 3, 3, )");
	if (verbose)
		crDebug("glGetProgramivNV( (unsigned) 3, 3,  )");
}
void crPackTestGetProgramNamedParameterdvNV(void)
{
	GLubyte name[100000];/* VECP */
	GLdouble  params[4];
	crDebug ( "GetProgramNamedParameterdvNV is a stub and needs to be special cased  1!");
	return;
	glGetProgramNamedParameterdvNV((unsigned) 3, (unsigned) 10, 	(const GLubyte *)name /* VEC3 */
, params);
	if(errChk)
		printError("glGetProgramNamedParameterdvNV((unsigned) 3, (unsigned) 10, , )");
	if (verbose)
		crDebug("glGetProgramNamedParameterdvNV( (unsigned) 3, (unsigned) 10, ,  )");
	glGetProgramNamedParameterdvNV((unsigned) 3, (unsigned) 10, 	(const GLubyte *)name /* VEC3 */
, params);
	if(errChk)
		printError("glGetProgramNamedParameterdvNV((unsigned) 3, (unsigned) 10, , )");
	if (verbose)
		crDebug("glGetProgramNamedParameterdvNV( (unsigned) 3, (unsigned) 10, ,  )");
	glGetProgramNamedParameterdvNV((unsigned) 3, (unsigned) 10, 	(const GLubyte *)name /* VEC3 */
, params);
	if(errChk)
		printError("glGetProgramNamedParameterdvNV((unsigned) 3, (unsigned) 10, , )");
	if (verbose)
		crDebug("glGetProgramNamedParameterdvNV( (unsigned) 3, (unsigned) 10, ,  )");
	glGetProgramNamedParameterdvNV((unsigned) 3, (unsigned) 10, 	(const GLubyte *)name /* VEC3 */
, params);
	if(errChk)
		printError("glGetProgramNamedParameterdvNV((unsigned) 3, (unsigned) 10, , )");
	if (verbose)
		crDebug("glGetProgramNamedParameterdvNV( (unsigned) 3, (unsigned) 10, ,  )");
	glGetProgramNamedParameterdvNV((unsigned) 3, (unsigned) 10, 	(const GLubyte *)name /* VEC3 */
, params);
	if(errChk)
		printError("glGetProgramNamedParameterdvNV((unsigned) 3, (unsigned) 10, , )");
	if (verbose)
		crDebug("glGetProgramNamedParameterdvNV( (unsigned) 3, (unsigned) 10, ,  )");
	glGetProgramNamedParameterdvNV((unsigned) 3, (unsigned) 10, 	(const GLubyte *)name /* VEC3 */
, params);
	if(errChk)
		printError("glGetProgramNamedParameterdvNV((unsigned) 3, (unsigned) 10, , )");
	if (verbose)
		crDebug("glGetProgramNamedParameterdvNV( (unsigned) 3, (unsigned) 10, ,  )");
}
void crPackTestGetProgramNamedParameterfvNV(void)
{
	GLubyte name[100000];/* VECP */
	GLfloat  params[4];
	crDebug ( "GetProgramNamedParameterfvNV is a stub and needs to be special cased  1!");
	return;
	glGetProgramNamedParameterfvNV((unsigned) 3, (unsigned) 10, 	(const GLubyte *)name /* VEC3 */
, params);
	if(errChk)
		printError("glGetProgramNamedParameterfvNV((unsigned) 3, (unsigned) 10, , )");
	if (verbose)
		crDebug("glGetProgramNamedParameterfvNV( (unsigned) 3, (unsigned) 10, ,  )");
	glGetProgramNamedParameterfvNV((unsigned) 3, (unsigned) 10, 	(const GLubyte *)name /* VEC3 */
, params);
	if(errChk)
		printError("glGetProgramNamedParameterfvNV((unsigned) 3, (unsigned) 10, , )");
	if (verbose)
		crDebug("glGetProgramNamedParameterfvNV( (unsigned) 3, (unsigned) 10, ,  )");
	glGetProgramNamedParameterfvNV((unsigned) 3, (unsigned) 10, 	(const GLubyte *)name /* VEC3 */
, params);
	if(errChk)
		printError("glGetProgramNamedParameterfvNV((unsigned) 3, (unsigned) 10, , )");
	if (verbose)
		crDebug("glGetProgramNamedParameterfvNV( (unsigned) 3, (unsigned) 10, ,  )");
	glGetProgramNamedParameterfvNV((unsigned) 3, (unsigned) 10, 	(const GLubyte *)name /* VEC3 */
, params);
	if(errChk)
		printError("glGetProgramNamedParameterfvNV((unsigned) 3, (unsigned) 10, , )");
	if (verbose)
		crDebug("glGetProgramNamedParameterfvNV( (unsigned) 3, (unsigned) 10, ,  )");
	glGetProgramNamedParameterfvNV((unsigned) 3, (unsigned) 10, 	(const GLubyte *)name /* VEC3 */
, params);
	if(errChk)
		printError("glGetProgramNamedParameterfvNV((unsigned) 3, (unsigned) 10, , )");
	if (verbose)
		crDebug("glGetProgramNamedParameterfvNV( (unsigned) 3, (unsigned) 10, ,  )");
	glGetProgramNamedParameterfvNV((unsigned) 3, (unsigned) 10, 	(const GLubyte *)name /* VEC3 */
, params);
	if(errChk)
		printError("glGetProgramNamedParameterfvNV((unsigned) 3, (unsigned) 10, , )");
	if (verbose)
		crDebug("glGetProgramNamedParameterfvNV( (unsigned) 3, (unsigned) 10, ,  )");
}
void crPackTestGetProgramParameterdvNV(void)
{
	GLdouble  params[4];
	crDebug ( "GetProgramParameterdvNV is a stub and needs to be special cased  1!");
	return;
	glGetProgramParameterdvNV(GL_VERTEX_PROGRAM_NV, (unsigned) 3, GL_PROGRAM_PARAMETER_NV, params);
	if(errChk)
		printError("glGetProgramParameterdvNV(GL_VERTEX_PROGRAM_NV, (unsigned) 3, GL_PROGRAM_PARAMETER_NV, )");
	if (verbose)
		crDebug("glGetProgramParameterdvNV( GL_VERTEX_PROGRAM_NV, (unsigned) 3, GL_PROGRAM_PARAMETER_NV,  )");
	glGetProgramParameterdvNV(GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, GL_PROGRAM_PARAMETER_NV, params);
	if(errChk)
		printError("glGetProgramParameterdvNV(GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, GL_PROGRAM_PARAMETER_NV, )");
	if (verbose)
		crDebug("glGetProgramParameterdvNV( GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, GL_PROGRAM_PARAMETER_NV,  )");
	glGetProgramParameterdvNV(GL_VERTEX_PROGRAM_NV, (unsigned) 3, GL_PROGRAM_PARAMETER_NV, params);
	if(errChk)
		printError("glGetProgramParameterdvNV(GL_VERTEX_PROGRAM_NV, (unsigned) 3, GL_PROGRAM_PARAMETER_NV, )");
	if (verbose)
		crDebug("glGetProgramParameterdvNV( GL_VERTEX_PROGRAM_NV, (unsigned) 3, GL_PROGRAM_PARAMETER_NV,  )");
	glGetProgramParameterdvNV(GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, GL_PROGRAM_PARAMETER_NV, params);
	if(errChk)
		printError("glGetProgramParameterdvNV(GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, GL_PROGRAM_PARAMETER_NV, )");
	if (verbose)
		crDebug("glGetProgramParameterdvNV( GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, GL_PROGRAM_PARAMETER_NV,  )");
	glGetProgramParameterdvNV(GL_VERTEX_PROGRAM_NV, (unsigned) 3, GL_PROGRAM_PARAMETER_NV, params);
	if(errChk)
		printError("glGetProgramParameterdvNV(GL_VERTEX_PROGRAM_NV, (unsigned) 3, GL_PROGRAM_PARAMETER_NV, )");
	if (verbose)
		crDebug("glGetProgramParameterdvNV( GL_VERTEX_PROGRAM_NV, (unsigned) 3, GL_PROGRAM_PARAMETER_NV,  )");
	glGetProgramParameterdvNV(GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, GL_PROGRAM_PARAMETER_NV, params);
	if(errChk)
		printError("glGetProgramParameterdvNV(GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, GL_PROGRAM_PARAMETER_NV, )");
	if (verbose)
		crDebug("glGetProgramParameterdvNV( GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, GL_PROGRAM_PARAMETER_NV,  )");
	glGetProgramParameterdvNV(GL_VERTEX_PROGRAM_NV, (unsigned) 3, GL_PROGRAM_PARAMETER_NV, params);
	if(errChk)
		printError("glGetProgramParameterdvNV(GL_VERTEX_PROGRAM_NV, (unsigned) 3, GL_PROGRAM_PARAMETER_NV, )");
	if (verbose)
		crDebug("glGetProgramParameterdvNV( GL_VERTEX_PROGRAM_NV, (unsigned) 3, GL_PROGRAM_PARAMETER_NV,  )");
	glGetProgramParameterdvNV(GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, GL_PROGRAM_PARAMETER_NV, params);
	if(errChk)
		printError("glGetProgramParameterdvNV(GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, GL_PROGRAM_PARAMETER_NV, )");
	if (verbose)
		crDebug("glGetProgramParameterdvNV( GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, GL_PROGRAM_PARAMETER_NV,  )");
	glGetProgramParameterdvNV(GL_VERTEX_PROGRAM_NV, (unsigned) 3, GL_PROGRAM_PARAMETER_NV, params);
	if(errChk)
		printError("glGetProgramParameterdvNV(GL_VERTEX_PROGRAM_NV, (unsigned) 3, GL_PROGRAM_PARAMETER_NV, )");
	if (verbose)
		crDebug("glGetProgramParameterdvNV( GL_VERTEX_PROGRAM_NV, (unsigned) 3, GL_PROGRAM_PARAMETER_NV,  )");
	glGetProgramParameterdvNV(GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, GL_PROGRAM_PARAMETER_NV, params);
	if(errChk)
		printError("glGetProgramParameterdvNV(GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, GL_PROGRAM_PARAMETER_NV, )");
	if (verbose)
		crDebug("glGetProgramParameterdvNV( GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, GL_PROGRAM_PARAMETER_NV,  )");
	glGetProgramParameterdvNV(GL_VERTEX_PROGRAM_NV, (unsigned) 3, GL_PROGRAM_PARAMETER_NV, params);
	if(errChk)
		printError("glGetProgramParameterdvNV(GL_VERTEX_PROGRAM_NV, (unsigned) 3, GL_PROGRAM_PARAMETER_NV, )");
	if (verbose)
		crDebug("glGetProgramParameterdvNV( GL_VERTEX_PROGRAM_NV, (unsigned) 3, GL_PROGRAM_PARAMETER_NV,  )");
	glGetProgramParameterdvNV(GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, GL_PROGRAM_PARAMETER_NV, params);
	if(errChk)
		printError("glGetProgramParameterdvNV(GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, GL_PROGRAM_PARAMETER_NV, )");
	if (verbose)
		crDebug("glGetProgramParameterdvNV( GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, GL_PROGRAM_PARAMETER_NV,  )");
}
void crPackTestGetProgramParameterfvNV(void)
{
	GLubyte params[100000];/* VECP */
	crDebug ( "GetProgramParameterfvNV is a stub and needs to be special cased  1!");
	return;
	glGetProgramParameterfvNV(GL_VERTEX_PROGRAM_NV, (unsigned) 3, GL_PROGRAM_PARAMETER_NV, 	(GLfloat *)params /* VEC3 */
);
	if(errChk)
		printError("glGetProgramParameterfvNV(GL_VERTEX_PROGRAM_NV, (unsigned) 3, GL_PROGRAM_PARAMETER_NV, )");
	if (verbose)
		crDebug("glGetProgramParameterfvNV( GL_VERTEX_PROGRAM_NV, (unsigned) 3, GL_PROGRAM_PARAMETER_NV,  )");
	glGetProgramParameterfvNV(GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, GL_PROGRAM_PARAMETER_NV, 	(GLfloat *)params /* VEC3 */
);
	if(errChk)
		printError("glGetProgramParameterfvNV(GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, GL_PROGRAM_PARAMETER_NV, )");
	if (verbose)
		crDebug("glGetProgramParameterfvNV( GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, GL_PROGRAM_PARAMETER_NV,  )");
}
void crPackTestGetProgramStringNV(void)
{
	GLubyte program[100000];/* VECP */
	crDebug ( "GetProgramStringNV is a stub and needs to be special cased  1!");
	return;
	glGetProgramStringNV((unsigned) 3, GL_PROGRAM_STRING_NV, 	(GLubyte *)program /* VEC3 */
);
	if(errChk)
		printError("glGetProgramStringNV((unsigned) 3, GL_PROGRAM_STRING_NV, )");
	if (verbose)
		crDebug("glGetProgramStringNV( (unsigned) 3, GL_PROGRAM_STRING_NV,  )");
}
void crPackTestGetVertexAttribPointervNV(void)
{
	GLubyte pointer[100000];/* VECP */
	crDebug ( "GetVertexAttribPointervNV is a stub and needs to be special cased  1!");
	return;
	glGetVertexAttribPointervNV((unsigned) 3, GL_ATTRIB_ARRAY_POINTER_NV, 	(GLvoid **)pointer /* VEC3 */
);
	if(errChk)
		printError("glGetVertexAttribPointervNV((unsigned) 3, GL_ATTRIB_ARRAY_POINTER_NV, )");
	if (verbose)
		crDebug("glGetVertexAttribPointervNV( (unsigned) 3, GL_ATTRIB_ARRAY_POINTER_NV,  )");
}
void crPackTestLoadProgramNV(void)
{
	GLubyte program[100000];/* VECP2 */
	crDebug ( "LoadProgramNV is a stub and needs to be special cased  0!");
	return;
	glLoadProgramNV(GL_VERTEX_PROGRAM_NV, (unsigned) 3, (unsigned) 10, 	(const GLubyte *)program /* VEC3 */
);
	if(errChk)
		printError("glLoadProgramNV(GL_VERTEX_PROGRAM_NV, (unsigned) 3, (unsigned) 10, )");
	if (verbose)
		crDebug("glLoadProgramNV( GL_VERTEX_PROGRAM_NV, (unsigned) 3, (unsigned) 10,  )");
	glLoadProgramNV(GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, (unsigned) 10, 	(const GLubyte *)program /* VEC3 */
);
	if(errChk)
		printError("glLoadProgramNV(GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, (unsigned) 10, )");
	if (verbose)
		crDebug("glLoadProgramNV( GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, (unsigned) 10,  )");
}
void crPackTestProgramNamedParameter4dNV(void)
{
	GLubyte name[100000];/* VECP2 */
	crDebug ( "ProgramNamedParameter4dNV is a stub and needs to be special cased  0!");
	return;
	glProgramNamedParameter4dNV((unsigned) 3, (unsigned) 10, 	(const GLubyte *)name /* VEC3 */
, (float) 10.79, (float) 10.79, (float) 10.79, (float) 10.79);
	if(errChk)
		printError("glProgramNamedParameter4dNV((unsigned) 3, (unsigned) 10, , (float) 10.79, (float) 10.79, (float) 10.79, (float) 10.79)");
	if (verbose)
		crDebug("glProgramNamedParameter4dNV( (unsigned) 3, (unsigned) 10, , (float) 10.79, (float) 10.79, (float) 10.79, (float) 10.79 )");
}
void crPackTestProgramNamedParameter4dvNV(void)
{
	GLubyte name[100000];/* VECP2 */
	const GLdouble  v[4];
	crDebug ( "ProgramNamedParameter4dvNV is a stub and needs to be special cased  0!");
	return;
	glProgramNamedParameter4dvNV((unsigned) 3, (unsigned) 10, 	(const GLubyte *)name /* VEC3 */
, v);
	if(errChk)
		printError("glProgramNamedParameter4dvNV((unsigned) 3, (unsigned) 10, , )");
	if (verbose)
		crDebug("glProgramNamedParameter4dvNV( (unsigned) 3, (unsigned) 10, ,  )");
}
void crPackTestProgramNamedParameter4fNV(void)
{
	GLubyte name[100000];/* VECP2 */
	crDebug ( "ProgramNamedParameter4fNV is a stub and needs to be special cased  0!");
	return;
	glProgramNamedParameter4fNV((unsigned) 3, (unsigned) 10, 	(const GLubyte *)name /* VEC3 */
, (float) 3.4, (float) 3.4, (float) 3.4, (float) 3.4);
	if(errChk)
		printError("glProgramNamedParameter4fNV((unsigned) 3, (unsigned) 10, , (float) 3.4, (float) 3.4, (float) 3.4, (float) 3.4)");
	if (verbose)
		crDebug("glProgramNamedParameter4fNV( (unsigned) 3, (unsigned) 10, , (float) 3.4, (float) 3.4, (float) 3.4, (float) 3.4 )");
}
void crPackTestProgramNamedParameter4fvNV(void)
{
	GLubyte name[100000];/* VECP2 */
	GLubyte v[100000];/* VECP2 */
	crDebug ( "ProgramNamedParameter4fvNV is a stub and needs to be special cased  0!");
	return;
	glProgramNamedParameter4fvNV((unsigned) 3, (unsigned) 10, 	(const GLubyte *)name /* VEC3 */
, 	(const GLfloat *)v /* VEC3 */
);
	if(errChk)
		printError("glProgramNamedParameter4fvNV((unsigned) 3, (unsigned) 10, , )");
	if (verbose)
		crDebug("glProgramNamedParameter4fvNV( (unsigned) 3, (unsigned) 10, ,  )");
}
void crPackTestProgramParameter4dNV(void)
{
	crDebug ( "ProgramParameter4dNV is a stub and needs to be special cased  0!");
	return;
	glProgramParameter4dNV(GL_VERTEX_PROGRAM_NV, (unsigned) 3, (float) 10.79, (float) 10.79, (float) 10.79, (float) 10.79);
	if(errChk)
		printError("glProgramParameter4dNV(GL_VERTEX_PROGRAM_NV, (unsigned) 3, (float) 10.79, (float) 10.79, (float) 10.79, (float) 10.79)");
	if (verbose)
		crDebug("glProgramParameter4dNV( GL_VERTEX_PROGRAM_NV, (unsigned) 3, (float) 10.79, (float) 10.79, (float) 10.79, (float) 10.79 )");
	glProgramParameter4dNV(GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, (float) 10.79, (float) 10.79, (float) 10.79, (float) 10.79);
	if(errChk)
		printError("glProgramParameter4dNV(GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, (float) 10.79, (float) 10.79, (float) 10.79, (float) 10.79)");
	if (verbose)
		crDebug("glProgramParameter4dNV( GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, (float) 10.79, (float) 10.79, (float) 10.79, (float) 10.79 )");
}
void crPackTestProgramParameter4dvNV(void)
{
	const GLdouble  params[4];
	crDebug ( "ProgramParameter4dvNV is a stub and needs to be special cased  0!");
	return;
	glProgramParameter4dvNV(GL_VERTEX_PROGRAM_NV, (unsigned) 3, params);
	if(errChk)
		printError("glProgramParameter4dvNV(GL_VERTEX_PROGRAM_NV, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramParameter4dvNV( GL_VERTEX_PROGRAM_NV, (unsigned) 3,  )");
	glProgramParameter4dvNV(GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, params);
	if(errChk)
		printError("glProgramParameter4dvNV(GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramParameter4dvNV( GL_FRAGMENT_PROGRAM_NV, (unsigned) 3,  )");
	glProgramParameter4dvNV(GL_VERTEX_PROGRAM_NV, (unsigned) 3, params);
	if(errChk)
		printError("glProgramParameter4dvNV(GL_VERTEX_PROGRAM_NV, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramParameter4dvNV( GL_VERTEX_PROGRAM_NV, (unsigned) 3,  )");
	glProgramParameter4dvNV(GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, params);
	if(errChk)
		printError("glProgramParameter4dvNV(GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramParameter4dvNV( GL_FRAGMENT_PROGRAM_NV, (unsigned) 3,  )");
	glProgramParameter4dvNV(GL_VERTEX_PROGRAM_NV, (unsigned) 3, params);
	if(errChk)
		printError("glProgramParameter4dvNV(GL_VERTEX_PROGRAM_NV, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramParameter4dvNV( GL_VERTEX_PROGRAM_NV, (unsigned) 3,  )");
	glProgramParameter4dvNV(GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, params);
	if(errChk)
		printError("glProgramParameter4dvNV(GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramParameter4dvNV( GL_FRAGMENT_PROGRAM_NV, (unsigned) 3,  )");
	glProgramParameter4dvNV(GL_VERTEX_PROGRAM_NV, (unsigned) 3, params);
	if(errChk)
		printError("glProgramParameter4dvNV(GL_VERTEX_PROGRAM_NV, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramParameter4dvNV( GL_VERTEX_PROGRAM_NV, (unsigned) 3,  )");
	glProgramParameter4dvNV(GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, params);
	if(errChk)
		printError("glProgramParameter4dvNV(GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramParameter4dvNV( GL_FRAGMENT_PROGRAM_NV, (unsigned) 3,  )");
	glProgramParameter4dvNV(GL_VERTEX_PROGRAM_NV, (unsigned) 3, params);
	if(errChk)
		printError("glProgramParameter4dvNV(GL_VERTEX_PROGRAM_NV, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramParameter4dvNV( GL_VERTEX_PROGRAM_NV, (unsigned) 3,  )");
	glProgramParameter4dvNV(GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, params);
	if(errChk)
		printError("glProgramParameter4dvNV(GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramParameter4dvNV( GL_FRAGMENT_PROGRAM_NV, (unsigned) 3,  )");
	glProgramParameter4dvNV(GL_VERTEX_PROGRAM_NV, (unsigned) 3, params);
	if(errChk)
		printError("glProgramParameter4dvNV(GL_VERTEX_PROGRAM_NV, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramParameter4dvNV( GL_VERTEX_PROGRAM_NV, (unsigned) 3,  )");
	glProgramParameter4dvNV(GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, params);
	if(errChk)
		printError("glProgramParameter4dvNV(GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramParameter4dvNV( GL_FRAGMENT_PROGRAM_NV, (unsigned) 3,  )");
}
void crPackTestProgramParameter4fNV(void)
{
	crDebug ( "ProgramParameter4fNV is a stub and needs to be special cased  0!");
	return;
	glProgramParameter4fNV(GL_VERTEX_PROGRAM_NV, (unsigned) 3, (float) 3.4, (float) 3.4, (float) 3.4, (float) 3.4);
	if(errChk)
		printError("glProgramParameter4fNV(GL_VERTEX_PROGRAM_NV, (unsigned) 3, (float) 3.4, (float) 3.4, (float) 3.4, (float) 3.4)");
	if (verbose)
		crDebug("glProgramParameter4fNV( GL_VERTEX_PROGRAM_NV, (unsigned) 3, (float) 3.4, (float) 3.4, (float) 3.4, (float) 3.4 )");
	glProgramParameter4fNV(GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, (float) 3.4, (float) 3.4, (float) 3.4, (float) 3.4);
	if(errChk)
		printError("glProgramParameter4fNV(GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, (float) 3.4, (float) 3.4, (float) 3.4, (float) 3.4)");
	if (verbose)
		crDebug("glProgramParameter4fNV( GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, (float) 3.4, (float) 3.4, (float) 3.4, (float) 3.4 )");
}
void crPackTestProgramParameter4fvNV(void)
{
	const GLfloat  params[4];
	crDebug ( "ProgramParameter4fvNV is a stub and needs to be special cased  0!");
	return;
	glProgramParameter4fvNV(GL_VERTEX_PROGRAM_NV, (unsigned) 3, params);
	if(errChk)
		printError("glProgramParameter4fvNV(GL_VERTEX_PROGRAM_NV, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramParameter4fvNV( GL_VERTEX_PROGRAM_NV, (unsigned) 3,  )");
	glProgramParameter4fvNV(GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, params);
	if(errChk)
		printError("glProgramParameter4fvNV(GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramParameter4fvNV( GL_FRAGMENT_PROGRAM_NV, (unsigned) 3,  )");
	glProgramParameter4fvNV(GL_VERTEX_PROGRAM_NV, (unsigned) 3, params);
	if(errChk)
		printError("glProgramParameter4fvNV(GL_VERTEX_PROGRAM_NV, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramParameter4fvNV( GL_VERTEX_PROGRAM_NV, (unsigned) 3,  )");
	glProgramParameter4fvNV(GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, params);
	if(errChk)
		printError("glProgramParameter4fvNV(GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramParameter4fvNV( GL_FRAGMENT_PROGRAM_NV, (unsigned) 3,  )");
	glProgramParameter4fvNV(GL_VERTEX_PROGRAM_NV, (unsigned) 3, params);
	if(errChk)
		printError("glProgramParameter4fvNV(GL_VERTEX_PROGRAM_NV, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramParameter4fvNV( GL_VERTEX_PROGRAM_NV, (unsigned) 3,  )");
	glProgramParameter4fvNV(GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, params);
	if(errChk)
		printError("glProgramParameter4fvNV(GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramParameter4fvNV( GL_FRAGMENT_PROGRAM_NV, (unsigned) 3,  )");
	glProgramParameter4fvNV(GL_VERTEX_PROGRAM_NV, (unsigned) 3, params);
	if(errChk)
		printError("glProgramParameter4fvNV(GL_VERTEX_PROGRAM_NV, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramParameter4fvNV( GL_VERTEX_PROGRAM_NV, (unsigned) 3,  )");
	glProgramParameter4fvNV(GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, params);
	if(errChk)
		printError("glProgramParameter4fvNV(GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramParameter4fvNV( GL_FRAGMENT_PROGRAM_NV, (unsigned) 3,  )");
	glProgramParameter4fvNV(GL_VERTEX_PROGRAM_NV, (unsigned) 3, params);
	if(errChk)
		printError("glProgramParameter4fvNV(GL_VERTEX_PROGRAM_NV, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramParameter4fvNV( GL_VERTEX_PROGRAM_NV, (unsigned) 3,  )");
	glProgramParameter4fvNV(GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, params);
	if(errChk)
		printError("glProgramParameter4fvNV(GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramParameter4fvNV( GL_FRAGMENT_PROGRAM_NV, (unsigned) 3,  )");
	glProgramParameter4fvNV(GL_VERTEX_PROGRAM_NV, (unsigned) 3, params);
	if(errChk)
		printError("glProgramParameter4fvNV(GL_VERTEX_PROGRAM_NV, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramParameter4fvNV( GL_VERTEX_PROGRAM_NV, (unsigned) 3,  )");
	glProgramParameter4fvNV(GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, params);
	if(errChk)
		printError("glProgramParameter4fvNV(GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramParameter4fvNV( GL_FRAGMENT_PROGRAM_NV, (unsigned) 3,  )");
}
void crPackTestProgramParameters4dvNV(void)
{
	const GLdouble  params[4];
	crDebug ( "ProgramParameters4dvNV is a stub and needs to be special cased  0!");
	return;
	glProgramParameters4dvNV(GL_VERTEX_PROGRAM_NV, (unsigned) 3, (unsigned) 3, params);
	if(errChk)
		printError("glProgramParameters4dvNV(GL_VERTEX_PROGRAM_NV, (unsigned) 3, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramParameters4dvNV( GL_VERTEX_PROGRAM_NV, (unsigned) 3, (unsigned) 3,  )");
	glProgramParameters4dvNV(GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, (unsigned) 3, params);
	if(errChk)
		printError("glProgramParameters4dvNV(GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramParameters4dvNV( GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, (unsigned) 3,  )");
	glProgramParameters4dvNV(GL_VERTEX_PROGRAM_NV, (unsigned) 3, (unsigned) 3, params);
	if(errChk)
		printError("glProgramParameters4dvNV(GL_VERTEX_PROGRAM_NV, (unsigned) 3, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramParameters4dvNV( GL_VERTEX_PROGRAM_NV, (unsigned) 3, (unsigned) 3,  )");
	glProgramParameters4dvNV(GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, (unsigned) 3, params);
	if(errChk)
		printError("glProgramParameters4dvNV(GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramParameters4dvNV( GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, (unsigned) 3,  )");
	glProgramParameters4dvNV(GL_VERTEX_PROGRAM_NV, (unsigned) 3, (unsigned) 3, params);
	if(errChk)
		printError("glProgramParameters4dvNV(GL_VERTEX_PROGRAM_NV, (unsigned) 3, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramParameters4dvNV( GL_VERTEX_PROGRAM_NV, (unsigned) 3, (unsigned) 3,  )");
	glProgramParameters4dvNV(GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, (unsigned) 3, params);
	if(errChk)
		printError("glProgramParameters4dvNV(GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramParameters4dvNV( GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, (unsigned) 3,  )");
	glProgramParameters4dvNV(GL_VERTEX_PROGRAM_NV, (unsigned) 3, (unsigned) 3, params);
	if(errChk)
		printError("glProgramParameters4dvNV(GL_VERTEX_PROGRAM_NV, (unsigned) 3, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramParameters4dvNV( GL_VERTEX_PROGRAM_NV, (unsigned) 3, (unsigned) 3,  )");
	glProgramParameters4dvNV(GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, (unsigned) 3, params);
	if(errChk)
		printError("glProgramParameters4dvNV(GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramParameters4dvNV( GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, (unsigned) 3,  )");
	glProgramParameters4dvNV(GL_VERTEX_PROGRAM_NV, (unsigned) 3, (unsigned) 3, params);
	if(errChk)
		printError("glProgramParameters4dvNV(GL_VERTEX_PROGRAM_NV, (unsigned) 3, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramParameters4dvNV( GL_VERTEX_PROGRAM_NV, (unsigned) 3, (unsigned) 3,  )");
	glProgramParameters4dvNV(GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, (unsigned) 3, params);
	if(errChk)
		printError("glProgramParameters4dvNV(GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramParameters4dvNV( GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, (unsigned) 3,  )");
	glProgramParameters4dvNV(GL_VERTEX_PROGRAM_NV, (unsigned) 3, (unsigned) 3, params);
	if(errChk)
		printError("glProgramParameters4dvNV(GL_VERTEX_PROGRAM_NV, (unsigned) 3, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramParameters4dvNV( GL_VERTEX_PROGRAM_NV, (unsigned) 3, (unsigned) 3,  )");
	glProgramParameters4dvNV(GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, (unsigned) 3, params);
	if(errChk)
		printError("glProgramParameters4dvNV(GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramParameters4dvNV( GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, (unsigned) 3,  )");
}
void crPackTestProgramParameters4fvNV(void)
{
	const GLfloat  params[4];
	crDebug ( "ProgramParameters4fvNV is a stub and needs to be special cased  0!");
	return;
	glProgramParameters4fvNV(GL_VERTEX_PROGRAM_NV, (unsigned) 3, (unsigned) 3, params);
	if(errChk)
		printError("glProgramParameters4fvNV(GL_VERTEX_PROGRAM_NV, (unsigned) 3, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramParameters4fvNV( GL_VERTEX_PROGRAM_NV, (unsigned) 3, (unsigned) 3,  )");
	glProgramParameters4fvNV(GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, (unsigned) 3, params);
	if(errChk)
		printError("glProgramParameters4fvNV(GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramParameters4fvNV( GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, (unsigned) 3,  )");
	glProgramParameters4fvNV(GL_VERTEX_PROGRAM_NV, (unsigned) 3, (unsigned) 3, params);
	if(errChk)
		printError("glProgramParameters4fvNV(GL_VERTEX_PROGRAM_NV, (unsigned) 3, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramParameters4fvNV( GL_VERTEX_PROGRAM_NV, (unsigned) 3, (unsigned) 3,  )");
	glProgramParameters4fvNV(GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, (unsigned) 3, params);
	if(errChk)
		printError("glProgramParameters4fvNV(GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramParameters4fvNV( GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, (unsigned) 3,  )");
	glProgramParameters4fvNV(GL_VERTEX_PROGRAM_NV, (unsigned) 3, (unsigned) 3, params);
	if(errChk)
		printError("glProgramParameters4fvNV(GL_VERTEX_PROGRAM_NV, (unsigned) 3, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramParameters4fvNV( GL_VERTEX_PROGRAM_NV, (unsigned) 3, (unsigned) 3,  )");
	glProgramParameters4fvNV(GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, (unsigned) 3, params);
	if(errChk)
		printError("glProgramParameters4fvNV(GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramParameters4fvNV( GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, (unsigned) 3,  )");
	glProgramParameters4fvNV(GL_VERTEX_PROGRAM_NV, (unsigned) 3, (unsigned) 3, params);
	if(errChk)
		printError("glProgramParameters4fvNV(GL_VERTEX_PROGRAM_NV, (unsigned) 3, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramParameters4fvNV( GL_VERTEX_PROGRAM_NV, (unsigned) 3, (unsigned) 3,  )");
	glProgramParameters4fvNV(GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, (unsigned) 3, params);
	if(errChk)
		printError("glProgramParameters4fvNV(GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramParameters4fvNV( GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, (unsigned) 3,  )");
	glProgramParameters4fvNV(GL_VERTEX_PROGRAM_NV, (unsigned) 3, (unsigned) 3, params);
	if(errChk)
		printError("glProgramParameters4fvNV(GL_VERTEX_PROGRAM_NV, (unsigned) 3, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramParameters4fvNV( GL_VERTEX_PROGRAM_NV, (unsigned) 3, (unsigned) 3,  )");
	glProgramParameters4fvNV(GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, (unsigned) 3, params);
	if(errChk)
		printError("glProgramParameters4fvNV(GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramParameters4fvNV( GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, (unsigned) 3,  )");
	glProgramParameters4fvNV(GL_VERTEX_PROGRAM_NV, (unsigned) 3, (unsigned) 3, params);
	if(errChk)
		printError("glProgramParameters4fvNV(GL_VERTEX_PROGRAM_NV, (unsigned) 3, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramParameters4fvNV( GL_VERTEX_PROGRAM_NV, (unsigned) 3, (unsigned) 3,  )");
	glProgramParameters4fvNV(GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, (unsigned) 3, params);
	if(errChk)
		printError("glProgramParameters4fvNV(GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramParameters4fvNV( GL_FRAGMENT_PROGRAM_NV, (unsigned) 3, (unsigned) 3,  )");
}
void crPackTestRequestResidentProgramsNV(void)
{
	GLubyte ids[100000];/* VECP2 */
	crDebug ( "RequestResidentProgramsNV is a stub and needs to be special cased  0!");
	return;
	glRequestResidentProgramsNV((unsigned) 10, 	(const GLuint *)ids /* VEC3 */
);
	if(errChk)
		printError("glRequestResidentProgramsNV((unsigned) 10, )");
	if (verbose)
		crDebug("glRequestResidentProgramsNV( (unsigned) 10,  )");
}
void crPackTestGetVertexAttribPointervARB(void)
{
	GLubyte pointer[100000];/* VECP */
	crDebug ( "GetVertexAttribPointervARB is a stub and needs to be special cased  1!");
	return;
	glGetVertexAttribPointervARB((unsigned) 1, GL_VERTEX_ATTRIB_ARRAY_ENABLED_ARB, 	(GLvoid **)pointer /* VEC3 */
);
	if(errChk)
		printError("glGetVertexAttribPointervARB((unsigned) 1, GL_VERTEX_ATTRIB_ARRAY_ENABLED_ARB, )");
	if (verbose)
		crDebug("glGetVertexAttribPointervARB( (unsigned) 1, GL_VERTEX_ATTRIB_ARRAY_ENABLED_ARB,  )");
	glGetVertexAttribPointervARB((unsigned) 2, GL_VERTEX_ATTRIB_ARRAY_ENABLED_ARB, 	(GLvoid **)pointer /* VEC3 */
);
	if(errChk)
		printError("glGetVertexAttribPointervARB((unsigned) 2, GL_VERTEX_ATTRIB_ARRAY_ENABLED_ARB, )");
	if (verbose)
		crDebug("glGetVertexAttribPointervARB( (unsigned) 2, GL_VERTEX_ATTRIB_ARRAY_ENABLED_ARB,  )");
	glGetVertexAttribPointervARB((unsigned) 3, GL_VERTEX_ATTRIB_ARRAY_ENABLED_ARB, 	(GLvoid **)pointer /* VEC3 */
);
	if(errChk)
		printError("glGetVertexAttribPointervARB((unsigned) 3, GL_VERTEX_ATTRIB_ARRAY_ENABLED_ARB, )");
	if (verbose)
		crDebug("glGetVertexAttribPointervARB( (unsigned) 3, GL_VERTEX_ATTRIB_ARRAY_ENABLED_ARB,  )");
	glGetVertexAttribPointervARB((unsigned) 4, GL_VERTEX_ATTRIB_ARRAY_ENABLED_ARB, 	(GLvoid **)pointer /* VEC3 */
);
	if(errChk)
		printError("glGetVertexAttribPointervARB((unsigned) 4, GL_VERTEX_ATTRIB_ARRAY_ENABLED_ARB, )");
	if (verbose)
		crDebug("glGetVertexAttribPointervARB( (unsigned) 4, GL_VERTEX_ATTRIB_ARRAY_ENABLED_ARB,  )");
	glGetVertexAttribPointervARB((unsigned) 5, GL_VERTEX_ATTRIB_ARRAY_ENABLED_ARB, 	(GLvoid **)pointer /* VEC3 */
);
	if(errChk)
		printError("glGetVertexAttribPointervARB((unsigned) 5, GL_VERTEX_ATTRIB_ARRAY_ENABLED_ARB, )");
	if (verbose)
		crDebug("glGetVertexAttribPointervARB( (unsigned) 5, GL_VERTEX_ATTRIB_ARRAY_ENABLED_ARB,  )");
	glGetVertexAttribPointervARB((unsigned) 6, GL_VERTEX_ATTRIB_ARRAY_ENABLED_ARB, 	(GLvoid **)pointer /* VEC3 */
);
	if(errChk)
		printError("glGetVertexAttribPointervARB((unsigned) 6, GL_VERTEX_ATTRIB_ARRAY_ENABLED_ARB, )");
	if (verbose)
		crDebug("glGetVertexAttribPointervARB( (unsigned) 6, GL_VERTEX_ATTRIB_ARRAY_ENABLED_ARB,  )");
	glGetVertexAttribPointervARB((unsigned) 7, GL_VERTEX_ATTRIB_ARRAY_ENABLED_ARB, 	(GLvoid **)pointer /* VEC3 */
);
	if(errChk)
		printError("glGetVertexAttribPointervARB((unsigned) 7, GL_VERTEX_ATTRIB_ARRAY_ENABLED_ARB, )");
	if (verbose)
		crDebug("glGetVertexAttribPointervARB( (unsigned) 7, GL_VERTEX_ATTRIB_ARRAY_ENABLED_ARB,  )");
	glGetVertexAttribPointervARB((unsigned) 1, GL_VERTEX_ATTRIB_ARRAY_SIZE_ARB, 	(GLvoid **)pointer /* VEC3 */
);
	if(errChk)
		printError("glGetVertexAttribPointervARB((unsigned) 1, GL_VERTEX_ATTRIB_ARRAY_SIZE_ARB, )");
	if (verbose)
		crDebug("glGetVertexAttribPointervARB( (unsigned) 1, GL_VERTEX_ATTRIB_ARRAY_SIZE_ARB,  )");
	glGetVertexAttribPointervARB((unsigned) 2, GL_VERTEX_ATTRIB_ARRAY_SIZE_ARB, 	(GLvoid **)pointer /* VEC3 */
);
	if(errChk)
		printError("glGetVertexAttribPointervARB((unsigned) 2, GL_VERTEX_ATTRIB_ARRAY_SIZE_ARB, )");
	if (verbose)
		crDebug("glGetVertexAttribPointervARB( (unsigned) 2, GL_VERTEX_ATTRIB_ARRAY_SIZE_ARB,  )");
	glGetVertexAttribPointervARB((unsigned) 3, GL_VERTEX_ATTRIB_ARRAY_SIZE_ARB, 	(GLvoid **)pointer /* VEC3 */
);
	if(errChk)
		printError("glGetVertexAttribPointervARB((unsigned) 3, GL_VERTEX_ATTRIB_ARRAY_SIZE_ARB, )");
	if (verbose)
		crDebug("glGetVertexAttribPointervARB( (unsigned) 3, GL_VERTEX_ATTRIB_ARRAY_SIZE_ARB,  )");
	glGetVertexAttribPointervARB((unsigned) 4, GL_VERTEX_ATTRIB_ARRAY_SIZE_ARB, 	(GLvoid **)pointer /* VEC3 */
);
	if(errChk)
		printError("glGetVertexAttribPointervARB((unsigned) 4, GL_VERTEX_ATTRIB_ARRAY_SIZE_ARB, )");
	if (verbose)
		crDebug("glGetVertexAttribPointervARB( (unsigned) 4, GL_VERTEX_ATTRIB_ARRAY_SIZE_ARB,  )");
	glGetVertexAttribPointervARB((unsigned) 5, GL_VERTEX_ATTRIB_ARRAY_SIZE_ARB, 	(GLvoid **)pointer /* VEC3 */
);
	if(errChk)
		printError("glGetVertexAttribPointervARB((unsigned) 5, GL_VERTEX_ATTRIB_ARRAY_SIZE_ARB, )");
	if (verbose)
		crDebug("glGetVertexAttribPointervARB( (unsigned) 5, GL_VERTEX_ATTRIB_ARRAY_SIZE_ARB,  )");
	glGetVertexAttribPointervARB((unsigned) 6, GL_VERTEX_ATTRIB_ARRAY_SIZE_ARB, 	(GLvoid **)pointer /* VEC3 */
);
	if(errChk)
		printError("glGetVertexAttribPointervARB((unsigned) 6, GL_VERTEX_ATTRIB_ARRAY_SIZE_ARB, )");
	if (verbose)
		crDebug("glGetVertexAttribPointervARB( (unsigned) 6, GL_VERTEX_ATTRIB_ARRAY_SIZE_ARB,  )");
	glGetVertexAttribPointervARB((unsigned) 7, GL_VERTEX_ATTRIB_ARRAY_SIZE_ARB, 	(GLvoid **)pointer /* VEC3 */
);
	if(errChk)
		printError("glGetVertexAttribPointervARB((unsigned) 7, GL_VERTEX_ATTRIB_ARRAY_SIZE_ARB, )");
	if (verbose)
		crDebug("glGetVertexAttribPointervARB( (unsigned) 7, GL_VERTEX_ATTRIB_ARRAY_SIZE_ARB,  )");
	glGetVertexAttribPointervARB((unsigned) 1, GL_VERTEX_ATTRIB_ARRAY_STRIDE_ARB, 	(GLvoid **)pointer /* VEC3 */
);
	if(errChk)
		printError("glGetVertexAttribPointervARB((unsigned) 1, GL_VERTEX_ATTRIB_ARRAY_STRIDE_ARB, )");
	if (verbose)
		crDebug("glGetVertexAttribPointervARB( (unsigned) 1, GL_VERTEX_ATTRIB_ARRAY_STRIDE_ARB,  )");
	glGetVertexAttribPointervARB((unsigned) 2, GL_VERTEX_ATTRIB_ARRAY_STRIDE_ARB, 	(GLvoid **)pointer /* VEC3 */
);
	if(errChk)
		printError("glGetVertexAttribPointervARB((unsigned) 2, GL_VERTEX_ATTRIB_ARRAY_STRIDE_ARB, )");
	if (verbose)
		crDebug("glGetVertexAttribPointervARB( (unsigned) 2, GL_VERTEX_ATTRIB_ARRAY_STRIDE_ARB,  )");
	glGetVertexAttribPointervARB((unsigned) 3, GL_VERTEX_ATTRIB_ARRAY_STRIDE_ARB, 	(GLvoid **)pointer /* VEC3 */
);
	if(errChk)
		printError("glGetVertexAttribPointervARB((unsigned) 3, GL_VERTEX_ATTRIB_ARRAY_STRIDE_ARB, )");
	if (verbose)
		crDebug("glGetVertexAttribPointervARB( (unsigned) 3, GL_VERTEX_ATTRIB_ARRAY_STRIDE_ARB,  )");
	glGetVertexAttribPointervARB((unsigned) 4, GL_VERTEX_ATTRIB_ARRAY_STRIDE_ARB, 	(GLvoid **)pointer /* VEC3 */
);
	if(errChk)
		printError("glGetVertexAttribPointervARB((unsigned) 4, GL_VERTEX_ATTRIB_ARRAY_STRIDE_ARB, )");
	if (verbose)
		crDebug("glGetVertexAttribPointervARB( (unsigned) 4, GL_VERTEX_ATTRIB_ARRAY_STRIDE_ARB,  )");
	glGetVertexAttribPointervARB((unsigned) 5, GL_VERTEX_ATTRIB_ARRAY_STRIDE_ARB, 	(GLvoid **)pointer /* VEC3 */
);
	if(errChk)
		printError("glGetVertexAttribPointervARB((unsigned) 5, GL_VERTEX_ATTRIB_ARRAY_STRIDE_ARB, )");
	if (verbose)
		crDebug("glGetVertexAttribPointervARB( (unsigned) 5, GL_VERTEX_ATTRIB_ARRAY_STRIDE_ARB,  )");
	glGetVertexAttribPointervARB((unsigned) 6, GL_VERTEX_ATTRIB_ARRAY_STRIDE_ARB, 	(GLvoid **)pointer /* VEC3 */
);
	if(errChk)
		printError("glGetVertexAttribPointervARB((unsigned) 6, GL_VERTEX_ATTRIB_ARRAY_STRIDE_ARB, )");
	if (verbose)
		crDebug("glGetVertexAttribPointervARB( (unsigned) 6, GL_VERTEX_ATTRIB_ARRAY_STRIDE_ARB,  )");
	glGetVertexAttribPointervARB((unsigned) 7, GL_VERTEX_ATTRIB_ARRAY_STRIDE_ARB, 	(GLvoid **)pointer /* VEC3 */
);
	if(errChk)
		printError("glGetVertexAttribPointervARB((unsigned) 7, GL_VERTEX_ATTRIB_ARRAY_STRIDE_ARB, )");
	if (verbose)
		crDebug("glGetVertexAttribPointervARB( (unsigned) 7, GL_VERTEX_ATTRIB_ARRAY_STRIDE_ARB,  )");
	glGetVertexAttribPointervARB((unsigned) 1, GL_VERTEX_ATTRIB_ARRAY_TYPE_ARB, 	(GLvoid **)pointer /* VEC3 */
);
	if(errChk)
		printError("glGetVertexAttribPointervARB((unsigned) 1, GL_VERTEX_ATTRIB_ARRAY_TYPE_ARB, )");
	if (verbose)
		crDebug("glGetVertexAttribPointervARB( (unsigned) 1, GL_VERTEX_ATTRIB_ARRAY_TYPE_ARB,  )");
	glGetVertexAttribPointervARB((unsigned) 2, GL_VERTEX_ATTRIB_ARRAY_TYPE_ARB, 	(GLvoid **)pointer /* VEC3 */
);
	if(errChk)
		printError("glGetVertexAttribPointervARB((unsigned) 2, GL_VERTEX_ATTRIB_ARRAY_TYPE_ARB, )");
	if (verbose)
		crDebug("glGetVertexAttribPointervARB( (unsigned) 2, GL_VERTEX_ATTRIB_ARRAY_TYPE_ARB,  )");
	glGetVertexAttribPointervARB((unsigned) 3, GL_VERTEX_ATTRIB_ARRAY_TYPE_ARB, 	(GLvoid **)pointer /* VEC3 */
);
	if(errChk)
		printError("glGetVertexAttribPointervARB((unsigned) 3, GL_VERTEX_ATTRIB_ARRAY_TYPE_ARB, )");
	if (verbose)
		crDebug("glGetVertexAttribPointervARB( (unsigned) 3, GL_VERTEX_ATTRIB_ARRAY_TYPE_ARB,  )");
	glGetVertexAttribPointervARB((unsigned) 4, GL_VERTEX_ATTRIB_ARRAY_TYPE_ARB, 	(GLvoid **)pointer /* VEC3 */
);
	if(errChk)
		printError("glGetVertexAttribPointervARB((unsigned) 4, GL_VERTEX_ATTRIB_ARRAY_TYPE_ARB, )");
	if (verbose)
		crDebug("glGetVertexAttribPointervARB( (unsigned) 4, GL_VERTEX_ATTRIB_ARRAY_TYPE_ARB,  )");
	glGetVertexAttribPointervARB((unsigned) 5, GL_VERTEX_ATTRIB_ARRAY_TYPE_ARB, 	(GLvoid **)pointer /* VEC3 */
);
	if(errChk)
		printError("glGetVertexAttribPointervARB((unsigned) 5, GL_VERTEX_ATTRIB_ARRAY_TYPE_ARB, )");
	if (verbose)
		crDebug("glGetVertexAttribPointervARB( (unsigned) 5, GL_VERTEX_ATTRIB_ARRAY_TYPE_ARB,  )");
	glGetVertexAttribPointervARB((unsigned) 6, GL_VERTEX_ATTRIB_ARRAY_TYPE_ARB, 	(GLvoid **)pointer /* VEC3 */
);
	if(errChk)
		printError("glGetVertexAttribPointervARB((unsigned) 6, GL_VERTEX_ATTRIB_ARRAY_TYPE_ARB, )");
	if (verbose)
		crDebug("glGetVertexAttribPointervARB( (unsigned) 6, GL_VERTEX_ATTRIB_ARRAY_TYPE_ARB,  )");
	glGetVertexAttribPointervARB((unsigned) 7, GL_VERTEX_ATTRIB_ARRAY_TYPE_ARB, 	(GLvoid **)pointer /* VEC3 */
);
	if(errChk)
		printError("glGetVertexAttribPointervARB((unsigned) 7, GL_VERTEX_ATTRIB_ARRAY_TYPE_ARB, )");
	if (verbose)
		crDebug("glGetVertexAttribPointervARB( (unsigned) 7, GL_VERTEX_ATTRIB_ARRAY_TYPE_ARB,  )");
	glGetVertexAttribPointervARB((unsigned) 1, GL_VERTEX_ATTRIB_ARRAY_NORMALIZED_ARB, 	(GLvoid **)pointer /* VEC3 */
);
	if(errChk)
		printError("glGetVertexAttribPointervARB((unsigned) 1, GL_VERTEX_ATTRIB_ARRAY_NORMALIZED_ARB, )");
	if (verbose)
		crDebug("glGetVertexAttribPointervARB( (unsigned) 1, GL_VERTEX_ATTRIB_ARRAY_NORMALIZED_ARB,  )");
	glGetVertexAttribPointervARB((unsigned) 2, GL_VERTEX_ATTRIB_ARRAY_NORMALIZED_ARB, 	(GLvoid **)pointer /* VEC3 */
);
	if(errChk)
		printError("glGetVertexAttribPointervARB((unsigned) 2, GL_VERTEX_ATTRIB_ARRAY_NORMALIZED_ARB, )");
	if (verbose)
		crDebug("glGetVertexAttribPointervARB( (unsigned) 2, GL_VERTEX_ATTRIB_ARRAY_NORMALIZED_ARB,  )");
	glGetVertexAttribPointervARB((unsigned) 3, GL_VERTEX_ATTRIB_ARRAY_NORMALIZED_ARB, 	(GLvoid **)pointer /* VEC3 */
);
	if(errChk)
		printError("glGetVertexAttribPointervARB((unsigned) 3, GL_VERTEX_ATTRIB_ARRAY_NORMALIZED_ARB, )");
	if (verbose)
		crDebug("glGetVertexAttribPointervARB( (unsigned) 3, GL_VERTEX_ATTRIB_ARRAY_NORMALIZED_ARB,  )");
	glGetVertexAttribPointervARB((unsigned) 4, GL_VERTEX_ATTRIB_ARRAY_NORMALIZED_ARB, 	(GLvoid **)pointer /* VEC3 */
);
	if(errChk)
		printError("glGetVertexAttribPointervARB((unsigned) 4, GL_VERTEX_ATTRIB_ARRAY_NORMALIZED_ARB, )");
	if (verbose)
		crDebug("glGetVertexAttribPointervARB( (unsigned) 4, GL_VERTEX_ATTRIB_ARRAY_NORMALIZED_ARB,  )");
	glGetVertexAttribPointervARB((unsigned) 5, GL_VERTEX_ATTRIB_ARRAY_NORMALIZED_ARB, 	(GLvoid **)pointer /* VEC3 */
);
	if(errChk)
		printError("glGetVertexAttribPointervARB((unsigned) 5, GL_VERTEX_ATTRIB_ARRAY_NORMALIZED_ARB, )");
	if (verbose)
		crDebug("glGetVertexAttribPointervARB( (unsigned) 5, GL_VERTEX_ATTRIB_ARRAY_NORMALIZED_ARB,  )");
	glGetVertexAttribPointervARB((unsigned) 6, GL_VERTEX_ATTRIB_ARRAY_NORMALIZED_ARB, 	(GLvoid **)pointer /* VEC3 */
);
	if(errChk)
		printError("glGetVertexAttribPointervARB((unsigned) 6, GL_VERTEX_ATTRIB_ARRAY_NORMALIZED_ARB, )");
	if (verbose)
		crDebug("glGetVertexAttribPointervARB( (unsigned) 6, GL_VERTEX_ATTRIB_ARRAY_NORMALIZED_ARB,  )");
	glGetVertexAttribPointervARB((unsigned) 7, GL_VERTEX_ATTRIB_ARRAY_NORMALIZED_ARB, 	(GLvoid **)pointer /* VEC3 */
);
	if(errChk)
		printError("glGetVertexAttribPointervARB((unsigned) 7, GL_VERTEX_ATTRIB_ARRAY_NORMALIZED_ARB, )");
	if (verbose)
		crDebug("glGetVertexAttribPointervARB( (unsigned) 7, GL_VERTEX_ATTRIB_ARRAY_NORMALIZED_ARB,  )");
	glGetVertexAttribPointervARB((unsigned) 1, GL_CURRENT_VERTEX_ATTRIB_ARB, 	(GLvoid **)pointer /* VEC3 */
);
	if(errChk)
		printError("glGetVertexAttribPointervARB((unsigned) 1, GL_CURRENT_VERTEX_ATTRIB_ARB, )");
	if (verbose)
		crDebug("glGetVertexAttribPointervARB( (unsigned) 1, GL_CURRENT_VERTEX_ATTRIB_ARB,  )");
	glGetVertexAttribPointervARB((unsigned) 2, GL_CURRENT_VERTEX_ATTRIB_ARB, 	(GLvoid **)pointer /* VEC3 */
);
	if(errChk)
		printError("glGetVertexAttribPointervARB((unsigned) 2, GL_CURRENT_VERTEX_ATTRIB_ARB, )");
	if (verbose)
		crDebug("glGetVertexAttribPointervARB( (unsigned) 2, GL_CURRENT_VERTEX_ATTRIB_ARB,  )");
	glGetVertexAttribPointervARB((unsigned) 3, GL_CURRENT_VERTEX_ATTRIB_ARB, 	(GLvoid **)pointer /* VEC3 */
);
	if(errChk)
		printError("glGetVertexAttribPointervARB((unsigned) 3, GL_CURRENT_VERTEX_ATTRIB_ARB, )");
	if (verbose)
		crDebug("glGetVertexAttribPointervARB( (unsigned) 3, GL_CURRENT_VERTEX_ATTRIB_ARB,  )");
	glGetVertexAttribPointervARB((unsigned) 4, GL_CURRENT_VERTEX_ATTRIB_ARB, 	(GLvoid **)pointer /* VEC3 */
);
	if(errChk)
		printError("glGetVertexAttribPointervARB((unsigned) 4, GL_CURRENT_VERTEX_ATTRIB_ARB, )");
	if (verbose)
		crDebug("glGetVertexAttribPointervARB( (unsigned) 4, GL_CURRENT_VERTEX_ATTRIB_ARB,  )");
	glGetVertexAttribPointervARB((unsigned) 5, GL_CURRENT_VERTEX_ATTRIB_ARB, 	(GLvoid **)pointer /* VEC3 */
);
	if(errChk)
		printError("glGetVertexAttribPointervARB((unsigned) 5, GL_CURRENT_VERTEX_ATTRIB_ARB, )");
	if (verbose)
		crDebug("glGetVertexAttribPointervARB( (unsigned) 5, GL_CURRENT_VERTEX_ATTRIB_ARB,  )");
	glGetVertexAttribPointervARB((unsigned) 6, GL_CURRENT_VERTEX_ATTRIB_ARB, 	(GLvoid **)pointer /* VEC3 */
);
	if(errChk)
		printError("glGetVertexAttribPointervARB((unsigned) 6, GL_CURRENT_VERTEX_ATTRIB_ARB, )");
	if (verbose)
		crDebug("glGetVertexAttribPointervARB( (unsigned) 6, GL_CURRENT_VERTEX_ATTRIB_ARB,  )");
	glGetVertexAttribPointervARB((unsigned) 7, GL_CURRENT_VERTEX_ATTRIB_ARB, 	(GLvoid **)pointer /* VEC3 */
);
	if(errChk)
		printError("glGetVertexAttribPointervARB((unsigned) 7, GL_CURRENT_VERTEX_ATTRIB_ARB, )");
	if (verbose)
		crDebug("glGetVertexAttribPointervARB( (unsigned) 7, GL_CURRENT_VERTEX_ATTRIB_ARB,  )");
}
