/* Copyright (c) 2001, Stanford University
	All rights reserved.

	See the file LICENSE.txt for information on redistributing this software. */
	
/* DO NOT EDIT - THIS FILE GENERATED BY THE opcodes.py SCRIPT */



#define GL_GLEXT_PROTOTYPES
#include <GL/gl.h>
#include <GL/glext.h>
#include <GL/glut.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "chromium.h"
#include "cr_error.h"
#include "packertest.h"

int errChk;
int verbose;
void printError(char *name);

void crPackTestDeleteProgramsARB(void)
{
	GLubyte programs[100000];/* VECP2 */
	crDebug ( "DeleteProgramsARB is a stub and needs to be special cased  0!");
	return;
	glDeleteProgramsARB((unsigned) 10, 	(const GLuint *)programs /* VEC3 */
);
	if(errChk)
		printError("glDeleteProgramsARB((unsigned) 10, )");
	if (verbose)
		crDebug("glDeleteProgramsARB( (unsigned) 10,  )");
}
void crPackTestGenProgramsARB(void)
{
	GLubyte programs[100000];/* VECP */
	crDebug ( "GenProgramsARB is a stub and needs to be special cased  1!");
	return;
	glGenProgramsARB((unsigned) 10, 	(GLuint *)programs /* VEC3 */
);
	if(errChk)
		printError("glGenProgramsARB((unsigned) 10, )");
	if (verbose)
		crDebug("glGenProgramsARB( (unsigned) 10,  )");
}
void crPackTestGetProgramEnvParameterdvARB(void)
{
	GLdouble  params[4];
	crDebug ( "GetProgramEnvParameterdvARB is a stub and needs to be special cased  1!");
	return;
	glGetProgramEnvParameterdvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glGetProgramEnvParameterdvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glGetProgramEnvParameterdvARB( GL_VERTEX_PROGRAM_ARB, (unsigned) 3,  )");
	glGetProgramEnvParameterdvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glGetProgramEnvParameterdvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glGetProgramEnvParameterdvARB( GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3,  )");
	glGetProgramEnvParameterdvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glGetProgramEnvParameterdvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glGetProgramEnvParameterdvARB( GL_VERTEX_PROGRAM_ARB, (unsigned) 3,  )");
	glGetProgramEnvParameterdvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glGetProgramEnvParameterdvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glGetProgramEnvParameterdvARB( GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3,  )");
	glGetProgramEnvParameterdvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glGetProgramEnvParameterdvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glGetProgramEnvParameterdvARB( GL_VERTEX_PROGRAM_ARB, (unsigned) 3,  )");
	glGetProgramEnvParameterdvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glGetProgramEnvParameterdvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glGetProgramEnvParameterdvARB( GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3,  )");
	glGetProgramEnvParameterdvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glGetProgramEnvParameterdvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glGetProgramEnvParameterdvARB( GL_VERTEX_PROGRAM_ARB, (unsigned) 3,  )");
	glGetProgramEnvParameterdvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glGetProgramEnvParameterdvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glGetProgramEnvParameterdvARB( GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3,  )");
	glGetProgramEnvParameterdvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glGetProgramEnvParameterdvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glGetProgramEnvParameterdvARB( GL_VERTEX_PROGRAM_ARB, (unsigned) 3,  )");
	glGetProgramEnvParameterdvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glGetProgramEnvParameterdvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glGetProgramEnvParameterdvARB( GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3,  )");
	glGetProgramEnvParameterdvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glGetProgramEnvParameterdvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glGetProgramEnvParameterdvARB( GL_VERTEX_PROGRAM_ARB, (unsigned) 3,  )");
	glGetProgramEnvParameterdvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glGetProgramEnvParameterdvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glGetProgramEnvParameterdvARB( GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3,  )");
}
void crPackTestGetProgramEnvParameterfvARB(void)
{
	GLfloat  params[4];
	crDebug ( "GetProgramEnvParameterfvARB is a stub and needs to be special cased  1!");
	return;
	glGetProgramEnvParameterfvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glGetProgramEnvParameterfvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glGetProgramEnvParameterfvARB( GL_VERTEX_PROGRAM_ARB, (unsigned) 3,  )");
	glGetProgramEnvParameterfvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glGetProgramEnvParameterfvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glGetProgramEnvParameterfvARB( GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3,  )");
	glGetProgramEnvParameterfvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glGetProgramEnvParameterfvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glGetProgramEnvParameterfvARB( GL_VERTEX_PROGRAM_ARB, (unsigned) 3,  )");
	glGetProgramEnvParameterfvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glGetProgramEnvParameterfvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glGetProgramEnvParameterfvARB( GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3,  )");
	glGetProgramEnvParameterfvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glGetProgramEnvParameterfvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glGetProgramEnvParameterfvARB( GL_VERTEX_PROGRAM_ARB, (unsigned) 3,  )");
	glGetProgramEnvParameterfvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glGetProgramEnvParameterfvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glGetProgramEnvParameterfvARB( GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3,  )");
	glGetProgramEnvParameterfvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glGetProgramEnvParameterfvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glGetProgramEnvParameterfvARB( GL_VERTEX_PROGRAM_ARB, (unsigned) 3,  )");
	glGetProgramEnvParameterfvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glGetProgramEnvParameterfvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glGetProgramEnvParameterfvARB( GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3,  )");
	glGetProgramEnvParameterfvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glGetProgramEnvParameterfvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glGetProgramEnvParameterfvARB( GL_VERTEX_PROGRAM_ARB, (unsigned) 3,  )");
	glGetProgramEnvParameterfvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glGetProgramEnvParameterfvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glGetProgramEnvParameterfvARB( GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3,  )");
	glGetProgramEnvParameterfvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glGetProgramEnvParameterfvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glGetProgramEnvParameterfvARB( GL_VERTEX_PROGRAM_ARB, (unsigned) 3,  )");
	glGetProgramEnvParameterfvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glGetProgramEnvParameterfvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glGetProgramEnvParameterfvARB( GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3,  )");
}
void crPackTestGetProgramivARB(void)
{
	GLubyte params[100000];/* VECP */
	crDebug ( "GetProgramivARB is a stub and needs to be special cased  1!");
	return;
	glGetProgramivARB(GL_VERTEX_PROGRAM_ARB, GL_VERTEX_PROGRAM_ARB, 	(GLint *)params /* VEC3 */
);
	if(errChk)
		printError("glGetProgramivARB(GL_VERTEX_PROGRAM_ARB, GL_VERTEX_PROGRAM_ARB, )");
	if (verbose)
		crDebug("glGetProgramivARB( GL_VERTEX_PROGRAM_ARB, GL_VERTEX_PROGRAM_ARB,  )");
	glGetProgramivARB(GL_FRAGMENT_PROGRAM_ARB, GL_VERTEX_PROGRAM_ARB, 	(GLint *)params /* VEC3 */
);
	if(errChk)
		printError("glGetProgramivARB(GL_FRAGMENT_PROGRAM_ARB, GL_VERTEX_PROGRAM_ARB, )");
	if (verbose)
		crDebug("glGetProgramivARB( GL_FRAGMENT_PROGRAM_ARB, GL_VERTEX_PROGRAM_ARB,  )");
	glGetProgramivARB(GL_VERTEX_PROGRAM_ARB, GL_FRAGMENT_PROGRAM_ARB, 	(GLint *)params /* VEC3 */
);
	if(errChk)
		printError("glGetProgramivARB(GL_VERTEX_PROGRAM_ARB, GL_FRAGMENT_PROGRAM_ARB, )");
	if (verbose)
		crDebug("glGetProgramivARB( GL_VERTEX_PROGRAM_ARB, GL_FRAGMENT_PROGRAM_ARB,  )");
	glGetProgramivARB(GL_FRAGMENT_PROGRAM_ARB, GL_FRAGMENT_PROGRAM_ARB, 	(GLint *)params /* VEC3 */
);
	if(errChk)
		printError("glGetProgramivARB(GL_FRAGMENT_PROGRAM_ARB, GL_FRAGMENT_PROGRAM_ARB, )");
	if (verbose)
		crDebug("glGetProgramivARB( GL_FRAGMENT_PROGRAM_ARB, GL_FRAGMENT_PROGRAM_ARB,  )");
}
void crPackTestGetProgramLocalParameterdvARB(void)
{
	GLdouble  params[4];
	crDebug ( "GetProgramLocalParameterdvARB is a stub and needs to be special cased  1!");
	return;
	glGetProgramLocalParameterdvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glGetProgramLocalParameterdvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glGetProgramLocalParameterdvARB( GL_VERTEX_PROGRAM_ARB, (unsigned) 3,  )");
	glGetProgramLocalParameterdvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glGetProgramLocalParameterdvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glGetProgramLocalParameterdvARB( GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3,  )");
	glGetProgramLocalParameterdvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glGetProgramLocalParameterdvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glGetProgramLocalParameterdvARB( GL_VERTEX_PROGRAM_ARB, (unsigned) 3,  )");
	glGetProgramLocalParameterdvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glGetProgramLocalParameterdvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glGetProgramLocalParameterdvARB( GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3,  )");
	glGetProgramLocalParameterdvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glGetProgramLocalParameterdvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glGetProgramLocalParameterdvARB( GL_VERTEX_PROGRAM_ARB, (unsigned) 3,  )");
	glGetProgramLocalParameterdvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glGetProgramLocalParameterdvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glGetProgramLocalParameterdvARB( GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3,  )");
	glGetProgramLocalParameterdvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glGetProgramLocalParameterdvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glGetProgramLocalParameterdvARB( GL_VERTEX_PROGRAM_ARB, (unsigned) 3,  )");
	glGetProgramLocalParameterdvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glGetProgramLocalParameterdvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glGetProgramLocalParameterdvARB( GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3,  )");
	glGetProgramLocalParameterdvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glGetProgramLocalParameterdvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glGetProgramLocalParameterdvARB( GL_VERTEX_PROGRAM_ARB, (unsigned) 3,  )");
	glGetProgramLocalParameterdvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glGetProgramLocalParameterdvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glGetProgramLocalParameterdvARB( GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3,  )");
	glGetProgramLocalParameterdvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glGetProgramLocalParameterdvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glGetProgramLocalParameterdvARB( GL_VERTEX_PROGRAM_ARB, (unsigned) 3,  )");
	glGetProgramLocalParameterdvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glGetProgramLocalParameterdvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glGetProgramLocalParameterdvARB( GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3,  )");
}
void crPackTestGetProgramLocalParameterfvARB(void)
{
	GLfloat  params[4];
	crDebug ( "GetProgramLocalParameterfvARB is a stub and needs to be special cased  1!");
	return;
	glGetProgramLocalParameterfvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glGetProgramLocalParameterfvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glGetProgramLocalParameterfvARB( GL_VERTEX_PROGRAM_ARB, (unsigned) 3,  )");
	glGetProgramLocalParameterfvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glGetProgramLocalParameterfvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glGetProgramLocalParameterfvARB( GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3,  )");
	glGetProgramLocalParameterfvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glGetProgramLocalParameterfvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glGetProgramLocalParameterfvARB( GL_VERTEX_PROGRAM_ARB, (unsigned) 3,  )");
	glGetProgramLocalParameterfvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glGetProgramLocalParameterfvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glGetProgramLocalParameterfvARB( GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3,  )");
	glGetProgramLocalParameterfvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glGetProgramLocalParameterfvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glGetProgramLocalParameterfvARB( GL_VERTEX_PROGRAM_ARB, (unsigned) 3,  )");
	glGetProgramLocalParameterfvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glGetProgramLocalParameterfvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glGetProgramLocalParameterfvARB( GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3,  )");
	glGetProgramLocalParameterfvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glGetProgramLocalParameterfvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glGetProgramLocalParameterfvARB( GL_VERTEX_PROGRAM_ARB, (unsigned) 3,  )");
	glGetProgramLocalParameterfvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glGetProgramLocalParameterfvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glGetProgramLocalParameterfvARB( GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3,  )");
	glGetProgramLocalParameterfvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glGetProgramLocalParameterfvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glGetProgramLocalParameterfvARB( GL_VERTEX_PROGRAM_ARB, (unsigned) 3,  )");
	glGetProgramLocalParameterfvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glGetProgramLocalParameterfvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glGetProgramLocalParameterfvARB( GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3,  )");
	glGetProgramLocalParameterfvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glGetProgramLocalParameterfvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glGetProgramLocalParameterfvARB( GL_VERTEX_PROGRAM_ARB, (unsigned) 3,  )");
	glGetProgramLocalParameterfvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glGetProgramLocalParameterfvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glGetProgramLocalParameterfvARB( GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3,  )");
}
void crPackTestGetProgramStringARB(void)
{
	GLubyte string[100000];/* VECP */
	crDebug ( "GetProgramStringARB is a stub and needs to be special cased  1!");
	return;
	glGetProgramStringARB(GL_VERTEX_PROGRAM_ARB, GL_PROGRAM_STRING_ARB, 	(GLvoid *)string /* VEC3 */
);
	if(errChk)
		printError("glGetProgramStringARB(GL_VERTEX_PROGRAM_ARB, GL_PROGRAM_STRING_ARB, )");
	if (verbose)
		crDebug("glGetProgramStringARB( GL_VERTEX_PROGRAM_ARB, GL_PROGRAM_STRING_ARB,  )");
	glGetProgramStringARB(GL_FRAGMENT_PROGRAM_ARB, GL_PROGRAM_STRING_ARB, 	(GLvoid *)string /* VEC3 */
);
	if(errChk)
		printError("glGetProgramStringARB(GL_FRAGMENT_PROGRAM_ARB, GL_PROGRAM_STRING_ARB, )");
	if (verbose)
		crDebug("glGetProgramStringARB( GL_FRAGMENT_PROGRAM_ARB, GL_PROGRAM_STRING_ARB,  )");
}
void crPackTestProgramEnvParameter4dARB(void)
{
	crDebug ( "ProgramEnvParameter4dARB is a stub and needs to be special cased  0!");
	return;
	glProgramEnvParameter4dARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, (float) 10.79, (float) 10.79, (float) 10.79, (float) 10.79);
	if(errChk)
		printError("glProgramEnvParameter4dARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, (float) 10.79, (float) 10.79, (float) 10.79, (float) 10.79)");
	if (verbose)
		crDebug("glProgramEnvParameter4dARB( GL_VERTEX_PROGRAM_ARB, (unsigned) 3, (float) 10.79, (float) 10.79, (float) 10.79, (float) 10.79 )");
	glProgramEnvParameter4dARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, (float) 10.79, (float) 10.79, (float) 10.79, (float) 10.79);
	if(errChk)
		printError("glProgramEnvParameter4dARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, (float) 10.79, (float) 10.79, (float) 10.79, (float) 10.79)");
	if (verbose)
		crDebug("glProgramEnvParameter4dARB( GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, (float) 10.79, (float) 10.79, (float) 10.79, (float) 10.79 )");
}
void crPackTestProgramEnvParameter4dvARB(void)
{
	const GLdouble  params[4];
	crDebug ( "ProgramEnvParameter4dvARB is a stub and needs to be special cased  0!");
	return;
	glProgramEnvParameter4dvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glProgramEnvParameter4dvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramEnvParameter4dvARB( GL_VERTEX_PROGRAM_ARB, (unsigned) 3,  )");
	glProgramEnvParameter4dvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glProgramEnvParameter4dvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramEnvParameter4dvARB( GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3,  )");
	glProgramEnvParameter4dvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glProgramEnvParameter4dvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramEnvParameter4dvARB( GL_VERTEX_PROGRAM_ARB, (unsigned) 3,  )");
	glProgramEnvParameter4dvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glProgramEnvParameter4dvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramEnvParameter4dvARB( GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3,  )");
	glProgramEnvParameter4dvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glProgramEnvParameter4dvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramEnvParameter4dvARB( GL_VERTEX_PROGRAM_ARB, (unsigned) 3,  )");
	glProgramEnvParameter4dvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glProgramEnvParameter4dvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramEnvParameter4dvARB( GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3,  )");
	glProgramEnvParameter4dvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glProgramEnvParameter4dvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramEnvParameter4dvARB( GL_VERTEX_PROGRAM_ARB, (unsigned) 3,  )");
	glProgramEnvParameter4dvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glProgramEnvParameter4dvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramEnvParameter4dvARB( GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3,  )");
	glProgramEnvParameter4dvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glProgramEnvParameter4dvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramEnvParameter4dvARB( GL_VERTEX_PROGRAM_ARB, (unsigned) 3,  )");
	glProgramEnvParameter4dvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glProgramEnvParameter4dvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramEnvParameter4dvARB( GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3,  )");
	glProgramEnvParameter4dvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glProgramEnvParameter4dvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramEnvParameter4dvARB( GL_VERTEX_PROGRAM_ARB, (unsigned) 3,  )");
	glProgramEnvParameter4dvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glProgramEnvParameter4dvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramEnvParameter4dvARB( GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3,  )");
}
void crPackTestProgramEnvParameter4fARB(void)
{
	crDebug ( "ProgramEnvParameter4fARB is a stub and needs to be special cased  0!");
	return;
	glProgramEnvParameter4fARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, (float) 3.4, (float) 3.4, (float) 3.4, (float) 3.4);
	if(errChk)
		printError("glProgramEnvParameter4fARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, (float) 3.4, (float) 3.4, (float) 3.4, (float) 3.4)");
	if (verbose)
		crDebug("glProgramEnvParameter4fARB( GL_VERTEX_PROGRAM_ARB, (unsigned) 3, (float) 3.4, (float) 3.4, (float) 3.4, (float) 3.4 )");
	glProgramEnvParameter4fARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, (float) 3.4, (float) 3.4, (float) 3.4, (float) 3.4);
	if(errChk)
		printError("glProgramEnvParameter4fARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, (float) 3.4, (float) 3.4, (float) 3.4, (float) 3.4)");
	if (verbose)
		crDebug("glProgramEnvParameter4fARB( GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, (float) 3.4, (float) 3.4, (float) 3.4, (float) 3.4 )");
}
void crPackTestProgramEnvParameter4fvARB(void)
{
	const GLfloat  params[4];
	crDebug ( "ProgramEnvParameter4fvARB is a stub and needs to be special cased  0!");
	return;
	glProgramEnvParameter4fvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glProgramEnvParameter4fvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramEnvParameter4fvARB( GL_VERTEX_PROGRAM_ARB, (unsigned) 3,  )");
	glProgramEnvParameter4fvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glProgramEnvParameter4fvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramEnvParameter4fvARB( GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3,  )");
	glProgramEnvParameter4fvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glProgramEnvParameter4fvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramEnvParameter4fvARB( GL_VERTEX_PROGRAM_ARB, (unsigned) 3,  )");
	glProgramEnvParameter4fvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glProgramEnvParameter4fvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramEnvParameter4fvARB( GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3,  )");
	glProgramEnvParameter4fvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glProgramEnvParameter4fvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramEnvParameter4fvARB( GL_VERTEX_PROGRAM_ARB, (unsigned) 3,  )");
	glProgramEnvParameter4fvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glProgramEnvParameter4fvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramEnvParameter4fvARB( GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3,  )");
	glProgramEnvParameter4fvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glProgramEnvParameter4fvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramEnvParameter4fvARB( GL_VERTEX_PROGRAM_ARB, (unsigned) 3,  )");
	glProgramEnvParameter4fvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glProgramEnvParameter4fvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramEnvParameter4fvARB( GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3,  )");
	glProgramEnvParameter4fvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glProgramEnvParameter4fvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramEnvParameter4fvARB( GL_VERTEX_PROGRAM_ARB, (unsigned) 3,  )");
	glProgramEnvParameter4fvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glProgramEnvParameter4fvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramEnvParameter4fvARB( GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3,  )");
	glProgramEnvParameter4fvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glProgramEnvParameter4fvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramEnvParameter4fvARB( GL_VERTEX_PROGRAM_ARB, (unsigned) 3,  )");
	glProgramEnvParameter4fvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glProgramEnvParameter4fvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramEnvParameter4fvARB( GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3,  )");
}
void crPackTestProgramLocalParameter4dARB(void)
{
	crDebug ( "ProgramLocalParameter4dARB is a stub and needs to be special cased  0!");
	return;
	glProgramLocalParameter4dARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, (float) 10.79, (float) 10.79, (float) 10.79, (float) 10.79);
	if(errChk)
		printError("glProgramLocalParameter4dARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, (float) 10.79, (float) 10.79, (float) 10.79, (float) 10.79)");
	if (verbose)
		crDebug("glProgramLocalParameter4dARB( GL_VERTEX_PROGRAM_ARB, (unsigned) 3, (float) 10.79, (float) 10.79, (float) 10.79, (float) 10.79 )");
	glProgramLocalParameter4dARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, (float) 10.79, (float) 10.79, (float) 10.79, (float) 10.79);
	if(errChk)
		printError("glProgramLocalParameter4dARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, (float) 10.79, (float) 10.79, (float) 10.79, (float) 10.79)");
	if (verbose)
		crDebug("glProgramLocalParameter4dARB( GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, (float) 10.79, (float) 10.79, (float) 10.79, (float) 10.79 )");
}
void crPackTestProgramLocalParameter4dvARB(void)
{
	const GLdouble  params[4];
	crDebug ( "ProgramLocalParameter4dvARB is a stub and needs to be special cased  0!");
	return;
	glProgramLocalParameter4dvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glProgramLocalParameter4dvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramLocalParameter4dvARB( GL_VERTEX_PROGRAM_ARB, (unsigned) 3,  )");
	glProgramLocalParameter4dvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glProgramLocalParameter4dvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramLocalParameter4dvARB( GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3,  )");
	glProgramLocalParameter4dvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glProgramLocalParameter4dvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramLocalParameter4dvARB( GL_VERTEX_PROGRAM_ARB, (unsigned) 3,  )");
	glProgramLocalParameter4dvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glProgramLocalParameter4dvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramLocalParameter4dvARB( GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3,  )");
	glProgramLocalParameter4dvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glProgramLocalParameter4dvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramLocalParameter4dvARB( GL_VERTEX_PROGRAM_ARB, (unsigned) 3,  )");
	glProgramLocalParameter4dvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glProgramLocalParameter4dvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramLocalParameter4dvARB( GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3,  )");
	glProgramLocalParameter4dvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glProgramLocalParameter4dvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramLocalParameter4dvARB( GL_VERTEX_PROGRAM_ARB, (unsigned) 3,  )");
	glProgramLocalParameter4dvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glProgramLocalParameter4dvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramLocalParameter4dvARB( GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3,  )");
	glProgramLocalParameter4dvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glProgramLocalParameter4dvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramLocalParameter4dvARB( GL_VERTEX_PROGRAM_ARB, (unsigned) 3,  )");
	glProgramLocalParameter4dvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glProgramLocalParameter4dvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramLocalParameter4dvARB( GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3,  )");
	glProgramLocalParameter4dvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glProgramLocalParameter4dvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramLocalParameter4dvARB( GL_VERTEX_PROGRAM_ARB, (unsigned) 3,  )");
	glProgramLocalParameter4dvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glProgramLocalParameter4dvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramLocalParameter4dvARB( GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3,  )");
}
void crPackTestProgramLocalParameter4fARB(void)
{
	crDebug ( "ProgramLocalParameter4fARB is a stub and needs to be special cased  0!");
	return;
	glProgramLocalParameter4fARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, (float) 3.4, (float) 3.4, (float) 3.4, (float) 3.4);
	if(errChk)
		printError("glProgramLocalParameter4fARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, (float) 3.4, (float) 3.4, (float) 3.4, (float) 3.4)");
	if (verbose)
		crDebug("glProgramLocalParameter4fARB( GL_VERTEX_PROGRAM_ARB, (unsigned) 3, (float) 3.4, (float) 3.4, (float) 3.4, (float) 3.4 )");
	glProgramLocalParameter4fARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, (float) 3.4, (float) 3.4, (float) 3.4, (float) 3.4);
	if(errChk)
		printError("glProgramLocalParameter4fARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, (float) 3.4, (float) 3.4, (float) 3.4, (float) 3.4)");
	if (verbose)
		crDebug("glProgramLocalParameter4fARB( GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, (float) 3.4, (float) 3.4, (float) 3.4, (float) 3.4 )");
}
void crPackTestProgramLocalParameter4fvARB(void)
{
	const GLfloat  params[4];
	crDebug ( "ProgramLocalParameter4fvARB is a stub and needs to be special cased  0!");
	return;
	glProgramLocalParameter4fvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glProgramLocalParameter4fvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramLocalParameter4fvARB( GL_VERTEX_PROGRAM_ARB, (unsigned) 3,  )");
	glProgramLocalParameter4fvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glProgramLocalParameter4fvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramLocalParameter4fvARB( GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3,  )");
	glProgramLocalParameter4fvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glProgramLocalParameter4fvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramLocalParameter4fvARB( GL_VERTEX_PROGRAM_ARB, (unsigned) 3,  )");
	glProgramLocalParameter4fvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glProgramLocalParameter4fvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramLocalParameter4fvARB( GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3,  )");
	glProgramLocalParameter4fvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glProgramLocalParameter4fvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramLocalParameter4fvARB( GL_VERTEX_PROGRAM_ARB, (unsigned) 3,  )");
	glProgramLocalParameter4fvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glProgramLocalParameter4fvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramLocalParameter4fvARB( GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3,  )");
	glProgramLocalParameter4fvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glProgramLocalParameter4fvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramLocalParameter4fvARB( GL_VERTEX_PROGRAM_ARB, (unsigned) 3,  )");
	glProgramLocalParameter4fvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glProgramLocalParameter4fvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramLocalParameter4fvARB( GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3,  )");
	glProgramLocalParameter4fvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glProgramLocalParameter4fvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramLocalParameter4fvARB( GL_VERTEX_PROGRAM_ARB, (unsigned) 3,  )");
	glProgramLocalParameter4fvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glProgramLocalParameter4fvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramLocalParameter4fvARB( GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3,  )");
	glProgramLocalParameter4fvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glProgramLocalParameter4fvARB(GL_VERTEX_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramLocalParameter4fvARB( GL_VERTEX_PROGRAM_ARB, (unsigned) 3,  )");
	glProgramLocalParameter4fvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, params);
	if(errChk)
		printError("glProgramLocalParameter4fvARB(GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3, )");
	if (verbose)
		crDebug("glProgramLocalParameter4fvARB( GL_FRAGMENT_PROGRAM_ARB, (unsigned) 3,  )");
}
void crPackTestProgramStringARB(void)
{
	GLubyte string[100000];/* VECP2 */
	crDebug ( "ProgramStringARB is a stub and needs to be special cased  0!");
	return;
	glProgramStringARB(GL_VERTEX_PROGRAM_ARB, GL_PROGRAM_FORMAT_ASCII_ARB, (unsigned) 10, 	(const GLvoid *)string /* VEC3 */
);
	if(errChk)
		printError("glProgramStringARB(GL_VERTEX_PROGRAM_ARB, GL_PROGRAM_FORMAT_ASCII_ARB, (unsigned) 10, )");
	if (verbose)
		crDebug("glProgramStringARB( GL_VERTEX_PROGRAM_ARB, GL_PROGRAM_FORMAT_ASCII_ARB, (unsigned) 10,  )");
	glProgramStringARB(GL_FRAGMENT_PROGRAM_ARB, GL_PROGRAM_FORMAT_ASCII_ARB, (unsigned) 10, 	(const GLvoid *)string /* VEC3 */
);
	if(errChk)
		printError("glProgramStringARB(GL_FRAGMENT_PROGRAM_ARB, GL_PROGRAM_FORMAT_ASCII_ARB, (unsigned) 10, )");
	if (verbose)
		crDebug("glProgramStringARB( GL_FRAGMENT_PROGRAM_ARB, GL_PROGRAM_FORMAT_ASCII_ARB, (unsigned) 10,  )");
}
