/* Copyright (c) 2001, Stanford University
	All rights reserved.

	See the file LICENSE.txt for information on redistributing this software. */
	
/* DO NOT EDIT - THIS FILE GENERATED BY THE opcodes.py SCRIPT */



#define GL_GLEXT_PROTOTYPES
#include <GL/gl.h>
#include <GL/glext.h>
#include <GL/glut.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "chromium.h"
#include "cr_error.h"
#include "packertest.h"

extern int errChk;
extern int verbose;
void printError(char *name);

void crPackTestCallLists(void)
{
	GLubyte lists[100000];/* VECP2 */
	crDebug ( "CallLists is a stub and needs to be special cased  0!");
	return;
	glCallLists((unsigned) 10, GL_BYTE, 	(const GLvoid *)lists /* VEC3 */
);
	if(errChk)
		printError("glCallLists((unsigned) 10, GL_BYTE, )");
	if (verbose)
		crDebug("glCallLists( (unsigned) 10, GL_BYTE,  )");
	glCallLists((unsigned) 10, GL_UNSIGNED_BYTE, 	(const GLvoid *)lists /* VEC3 */
);
	if(errChk)
		printError("glCallLists((unsigned) 10, GL_UNSIGNED_BYTE, )");
	if (verbose)
		crDebug("glCallLists( (unsigned) 10, GL_UNSIGNED_BYTE,  )");
	glCallLists((unsigned) 10, GL_SHORT, 	(const GLvoid *)lists /* VEC3 */
);
	if(errChk)
		printError("glCallLists((unsigned) 10, GL_SHORT, )");
	if (verbose)
		crDebug("glCallLists( (unsigned) 10, GL_SHORT,  )");
	glCallLists((unsigned) 10, GL_UNSIGNED_SHORT, 	(const GLvoid *)lists /* VEC3 */
);
	if(errChk)
		printError("glCallLists((unsigned) 10, GL_UNSIGNED_SHORT, )");
	if (verbose)
		crDebug("glCallLists( (unsigned) 10, GL_UNSIGNED_SHORT,  )");
	glCallLists((unsigned) 10, GL_INT, 	(const GLvoid *)lists /* VEC3 */
);
	if(errChk)
		printError("glCallLists((unsigned) 10, GL_INT, )");
	if (verbose)
		crDebug("glCallLists( (unsigned) 10, GL_INT,  )");
	glCallLists((unsigned) 10, GL_UNSIGNED_INT, 	(const GLvoid *)lists /* VEC3 */
);
	if(errChk)
		printError("glCallLists((unsigned) 10, GL_UNSIGNED_INT, )");
	if (verbose)
		crDebug("glCallLists( (unsigned) 10, GL_UNSIGNED_INT,  )");
	glCallLists((unsigned) 10, GL_FLOAT, 	(const GLvoid *)lists /* VEC3 */
);
	if(errChk)
		printError("glCallLists((unsigned) 10, GL_FLOAT, )");
	if (verbose)
		crDebug("glCallLists( (unsigned) 10, GL_FLOAT,  )");
	glCallLists((unsigned) 10, GL_2_BYTES, 	(const GLvoid *)lists /* VEC3 */
);
	if(errChk)
		printError("glCallLists((unsigned) 10, GL_2_BYTES, )");
	if (verbose)
		crDebug("glCallLists( (unsigned) 10, GL_2_BYTES,  )");
	glCallLists((unsigned) 10, GL_3_BYTES, 	(const GLvoid *)lists /* VEC3 */
);
	if(errChk)
		printError("glCallLists((unsigned) 10, GL_3_BYTES, )");
	if (verbose)
		crDebug("glCallLists( (unsigned) 10, GL_3_BYTES,  )");
	glCallLists((unsigned) 10, GL_4_BYTES, 	(const GLvoid *)lists /* VEC3 */
);
	if(errChk)
		printError("glCallLists((unsigned) 10, GL_4_BYTES, )");
	if (verbose)
		crDebug("glCallLists( (unsigned) 10, GL_4_BYTES,  )");
}
void crPackTestEndList(void)
{
	crDebug ( "EndList is a stub and needs to be special cased  0!");
	return;
	glEndList();
	if(errChk)
		printError("gl(EndList)");
	if (verbose)
		crDebug("glEndList( )");
}
