/* Copyright (c) 2001, Stanford University
	All rights reserved.

	See the file LICENSE.txt for information on redistributing this software. */
	
/* DO NOT EDIT - THIS FILE GENERATED BY THE opcodes.py SCRIPT */



#define GL_GLEXT_PROTOTYPES
#include <GL/gl.h>
#include <GL/glext.h>
#include <GL/glut.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "chromium.h"
#include "cr_error.h"
#include "packertest.h"

int errChk;
int verbose;
void printError(char *name);

struct TexImage3DEXT_params {
	GLenum TexImage3DEXT_target;
	GLint TexImage3DEXT_level;
	GLenum TexImage3DEXT_internalFormat;
	GLsizei TexImage3DEXT_width;
	GLsizei TexImage3DEXT_height;
	GLsizei TexImage3DEXT_depth;
	GLint TexImage3DEXT_border;
	GLenum TexImage3DEXT_format;
	GLenum TexImage3DEXT_type;
	char *prgstr;
} TexImage3DEXT_tab[] = {
#if 0
{ 	GL_TEXTURE_3D, 	(int) 0, 	0, 	(unsigned) 8, 	(unsigned) 8, 	(unsigned) 16, 	(int) 1, 	1, 	1, 
	"TexImage3DEXT_tab.GL_TEXTURE_3D, (int) 0, 0, (unsigned) 8, (unsigned) 8, (unsigned) 16, (int) 1, 1, 1, "},
#endif
{ 	GL_TEXTURE_3D, 	(int) 0, 	GL_ALPHA, 	(unsigned) 8, 	(unsigned) 8, 	(unsigned) 16, 	(int) 1, 	1, 	1, 
	"TexImage3DEXT_tab.GL_TEXTURE_3D, (int) 0, GL_ALPHA, (unsigned) 8, (unsigned) 8, (unsigned) 16, (int) 1, 1, 1, "},
{ 	GL_TEXTURE_3D, 	(int) 0, 	GL_ALPHA4, 	(unsigned) 8, 	(unsigned) 8, 	(unsigned) 16, 	(int) 1, 	1, 	1, 
	"TexImage3DEXT_tab.GL_TEXTURE_3D, (int) 0, GL_ALPHA4, (unsigned) 8, (unsigned) 8, (unsigned) 16, (int) 1, 1, 1, "},
{ 	GL_TEXTURE_3D, 	(int) 0, 	GL_ALPHA8, 	(unsigned) 8, 	(unsigned) 8, 	(unsigned) 16, 	(int) 1, 	1, 	1, 
	"TexImage3DEXT_tab.GL_TEXTURE_3D, (int) 0, GL_ALPHA8, (unsigned) 8, (unsigned) 8, (unsigned) 16, (int) 1, 1, 1, "},
{ 	GL_TEXTURE_3D, 	(int) 0, 	GL_ALPHA12, 	(unsigned) 8, 	(unsigned) 8, 	(unsigned) 16, 	(int) 1, 	1, 	1, 
	"TexImage3DEXT_tab.GL_TEXTURE_3D, (int) 0, GL_ALPHA12, (unsigned) 8, (unsigned) 8, (unsigned) 16, (int) 1, 1, 1, "},
{ 	GL_TEXTURE_3D, 	(int) 0, 	GL_ALPHA16, 	(unsigned) 8, 	(unsigned) 8, 	(unsigned) 16, 	(int) 1, 	1, 	1, 
	"TexImage3DEXT_tab.GL_TEXTURE_3D, (int) 0, GL_ALPHA16, (unsigned) 8, (unsigned) 8, (unsigned) 16, (int) 1, 1, 1, "},
{ 	GL_TEXTURE_3D, 	(int) 0, 	GL_LUMINANCE, 	(unsigned) 8, 	(unsigned) 8, 	(unsigned) 16, 	(int) 1, 	1, 	1, 
	"TexImage3DEXT_tab.GL_TEXTURE_3D, (int) 0, GL_LUMINANCE, (unsigned) 8, (unsigned) 8, (unsigned) 16, (int) 1, 1, 1, "},
{ 	GL_TEXTURE_3D, 	(int) 0, 	GL_LUMINANCE4, 	(unsigned) 8, 	(unsigned) 8, 	(unsigned) 16, 	(int) 1, 	1, 	1, 
	"TexImage3DEXT_tab.GL_TEXTURE_3D, (int) 0, GL_LUMINANCE4, (unsigned) 8, (unsigned) 8, (unsigned) 16, (int) 1, 1, 1, "},
{ 	GL_TEXTURE_3D, 	(int) 0, 	GL_LUMINANCE8, 	(unsigned) 8, 	(unsigned) 8, 	(unsigned) 16, 	(int) 1, 	1, 	1, 
	"TexImage3DEXT_tab.GL_TEXTURE_3D, (int) 0, GL_LUMINANCE8, (unsigned) 8, (unsigned) 8, (unsigned) 16, (int) 1, 1, 1, "},
{ 	GL_TEXTURE_3D, 	(int) 0, 	GL_LUMINANCE12, 	(unsigned) 8, 	(unsigned) 8, 	(unsigned) 16, 	(int) 1, 	1, 	1, 
	"TexImage3DEXT_tab.GL_TEXTURE_3D, (int) 0, GL_LUMINANCE12, (unsigned) 8, (unsigned) 8, (unsigned) 16, (int) 1, 1, 1, "},
{ 	GL_TEXTURE_3D, 	(int) 0, 	GL_LUMINANCE16, 	(unsigned) 8, 	(unsigned) 8, 	(unsigned) 16, 	(int) 1, 	1, 	1, 
	"TexImage3DEXT_tab.GL_TEXTURE_3D, (int) 0, GL_LUMINANCE16, (unsigned) 8, (unsigned) 8, (unsigned) 16, (int) 1, 1, 1, "},
{ 	GL_TEXTURE_3D, 	(int) 0, 	GL_LUMINANCE_ALPHA, 	(unsigned) 8, 	(unsigned) 8, 	(unsigned) 16, 	(int) 1, 	1, 	1, 
	"TexImage3DEXT_tab.GL_TEXTURE_3D, (int) 0, GL_LUMINANCE_ALPHA, (unsigned) 8, (unsigned) 8, (unsigned) 16, (int) 1, 1, 1, "},
{ 	GL_TEXTURE_3D, 	(int) 0, 	GL_LUMINANCE4_ALPHA4, 	(unsigned) 8, 	(unsigned) 8, 	(unsigned) 16, 	(int) 1, 	1, 	1, 
	"TexImage3DEXT_tab.GL_TEXTURE_3D, (int) 0, GL_LUMINANCE4_ALPHA4, (unsigned) 8, (unsigned) 8, (unsigned) 16, (int) 1, 1, 1, "},
{ 	GL_TEXTURE_3D, 	(int) 0, 	GL_LUMINANCE6_ALPHA2, 	(unsigned) 8, 	(unsigned) 8, 	(unsigned) 16, 	(int) 1, 	1, 	1, 
	"TexImage3DEXT_tab.GL_TEXTURE_3D, (int) 0, GL_LUMINANCE6_ALPHA2, (unsigned) 8, (unsigned) 8, (unsigned) 16, (int) 1, 1, 1, "},
{ 	GL_TEXTURE_3D, 	(int) 0, 	GL_LUMINANCE8_ALPHA8, 	(unsigned) 8, 	(unsigned) 8, 	(unsigned) 16, 	(int) 1, 	1, 	1, 
	"TexImage3DEXT_tab.GL_TEXTURE_3D, (int) 0, GL_LUMINANCE8_ALPHA8, (unsigned) 8, (unsigned) 8, (unsigned) 16, (int) 1, 1, 1, "},
{ 	GL_TEXTURE_3D, 	(int) 0, 	GL_LUMINANCE12_ALPHA4, 	(unsigned) 8, 	(unsigned) 8, 	(unsigned) 16, 	(int) 1, 	1, 	1, 
	"TexImage3DEXT_tab.GL_TEXTURE_3D, (int) 0, GL_LUMINANCE12_ALPHA4, (unsigned) 8, (unsigned) 8, (unsigned) 16, (int) 1, 1, 1, "},
{ 	GL_TEXTURE_3D, 	(int) 0, 	GL_LUMINANCE12_ALPHA12, 	(unsigned) 8, 	(unsigned) 8, 	(unsigned) 16, 	(int) 1, 	1, 	1, 
	"TexImage3DEXT_tab.GL_TEXTURE_3D, (int) 0, GL_LUMINANCE12_ALPHA12, (unsigned) 8, (unsigned) 8, (unsigned) 16, (int) 1, 1, 1, "},
{ 	GL_TEXTURE_3D, 	(int) 0, 	GL_LUMINANCE16_ALPHA16, 	(unsigned) 8, 	(unsigned) 8, 	(unsigned) 16, 	(int) 1, 	1, 	1, 
	"TexImage3DEXT_tab.GL_TEXTURE_3D, (int) 0, GL_LUMINANCE16_ALPHA16, (unsigned) 8, (unsigned) 8, (unsigned) 16, (int) 1, 1, 1, "},
{ 	GL_TEXTURE_3D, 	(int) 0, 	GL_INTENSITY, 	(unsigned) 8, 	(unsigned) 8, 	(unsigned) 16, 	(int) 1, 	1, 	1, 
	"TexImage3DEXT_tab.GL_TEXTURE_3D, (int) 0, GL_INTENSITY, (unsigned) 8, (unsigned) 8, (unsigned) 16, (int) 1, 1, 1, "},
{ 	GL_TEXTURE_3D, 	(int) 0, 	GL_INTENSITY4, 	(unsigned) 8, 	(unsigned) 8, 	(unsigned) 16, 	(int) 1, 	1, 	1, 
	"TexImage3DEXT_tab.GL_TEXTURE_3D, (int) 0, GL_INTENSITY4, (unsigned) 8, (unsigned) 8, (unsigned) 16, (int) 1, 1, 1, "},
{ 	GL_TEXTURE_3D, 	(int) 0, 	GL_INTENSITY8, 	(unsigned) 8, 	(unsigned) 8, 	(unsigned) 16, 	(int) 1, 	1, 	1, 
	"TexImage3DEXT_tab.GL_TEXTURE_3D, (int) 0, GL_INTENSITY8, (unsigned) 8, (unsigned) 8, (unsigned) 16, (int) 1, 1, 1, "},
{ 	GL_TEXTURE_3D, 	(int) 0, 	GL_INTENSITY12, 	(unsigned) 8, 	(unsigned) 8, 	(unsigned) 16, 	(int) 1, 	1, 	1, 
	"TexImage3DEXT_tab.GL_TEXTURE_3D, (int) 0, GL_INTENSITY12, (unsigned) 8, (unsigned) 8, (unsigned) 16, (int) 1, 1, 1, "},
{ 	GL_TEXTURE_3D, 	(int) 0, 	GL_INTENSITY16, 	(unsigned) 8, 	(unsigned) 8, 	(unsigned) 16, 	(int) 1, 	1, 	1, 
	"TexImage3DEXT_tab.GL_TEXTURE_3D, (int) 0, GL_INTENSITY16, (unsigned) 8, (unsigned) 8, (unsigned) 16, (int) 1, 1, 1, "},
{ 	GL_TEXTURE_3D, 	(int) 0, 	GL_R3_G3_B2, 	(unsigned) 8, 	(unsigned) 8, 	(unsigned) 16, 	(int) 1, 	1, 	1, 
	"TexImage3DEXT_tab.GL_TEXTURE_3D, (int) 0, GL_R3_G3_B2, (unsigned) 8, (unsigned) 8, (unsigned) 16, (int) 1, 1, 1, "},
{ 	GL_TEXTURE_3D, 	(int) 0, 	GL_RGB, 	(unsigned) 8, 	(unsigned) 8, 	(unsigned) 16, 	(int) 1, 	1, 	1, 
	"TexImage3DEXT_tab.GL_TEXTURE_3D, (int) 0, GL_RGB, (unsigned) 8, (unsigned) 8, (unsigned) 16, (int) 1, 1, 1, "},
{ 	GL_TEXTURE_3D, 	(int) 0, 	GL_RGB4, 	(unsigned) 8, 	(unsigned) 8, 	(unsigned) 16, 	(int) 1, 	1, 	1, 
	"TexImage3DEXT_tab.GL_TEXTURE_3D, (int) 0, GL_RGB4, (unsigned) 8, (unsigned) 8, (unsigned) 16, (int) 1, 1, 1, "},
{ 	GL_TEXTURE_3D, 	(int) 0, 	GL_RGB5, 	(unsigned) 8, 	(unsigned) 8, 	(unsigned) 16, 	(int) 1, 	1, 	1, 
	"TexImage3DEXT_tab.GL_TEXTURE_3D, (int) 0, GL_RGB5, (unsigned) 8, (unsigned) 8, (unsigned) 16, (int) 1, 1, 1, "},
{ 	GL_TEXTURE_3D, 	(int) 0, 	GL_RGB8, 	(unsigned) 8, 	(unsigned) 8, 	(unsigned) 16, 	(int) 1, 	1, 	1, 
	"TexImage3DEXT_tab.GL_TEXTURE_3D, (int) 0, GL_RGB8, (unsigned) 8, (unsigned) 8, (unsigned) 16, (int) 1, 1, 1, "},
{ 	GL_TEXTURE_3D, 	(int) 0, 	GL_RGB10, 	(unsigned) 8, 	(unsigned) 8, 	(unsigned) 16, 	(int) 1, 	1, 	1, 
	"TexImage3DEXT_tab.GL_TEXTURE_3D, (int) 0, GL_RGB10, (unsigned) 8, (unsigned) 8, (unsigned) 16, (int) 1, 1, 1, "},
{ 	GL_TEXTURE_3D, 	(int) 0, 	GL_RGB12, 	(unsigned) 8, 	(unsigned) 8, 	(unsigned) 16, 	(int) 1, 	1, 	1, 
	"TexImage3DEXT_tab.GL_TEXTURE_3D, (int) 0, GL_RGB12, (unsigned) 8, (unsigned) 8, (unsigned) 16, (int) 1, 1, 1, "},
{ 	GL_TEXTURE_3D, 	(int) 0, 	GL_RGB16, 	(unsigned) 8, 	(unsigned) 8, 	(unsigned) 16, 	(int) 1, 	1, 	1, 
	"TexImage3DEXT_tab.GL_TEXTURE_3D, (int) 0, GL_RGB16, (unsigned) 8, (unsigned) 8, (unsigned) 16, (int) 1, 1, 1, "},
{ 	GL_TEXTURE_3D, 	(int) 0, 	GL_RGBA, 	(unsigned) 8, 	(unsigned) 8, 	(unsigned) 16, 	(int) 1, 	1, 	1, 
	"TexImage3DEXT_tab.GL_TEXTURE_3D, (int) 0, GL_RGBA, (unsigned) 8, (unsigned) 8, (unsigned) 16, (int) 1, 1, 1, "},
{ 	GL_TEXTURE_3D, 	(int) 0, 	GL_RGBA2, 	(unsigned) 8, 	(unsigned) 8, 	(unsigned) 16, 	(int) 1, 	1, 	1, 
	"TexImage3DEXT_tab.GL_TEXTURE_3D, (int) 0, GL_RGBA2, (unsigned) 8, (unsigned) 8, (unsigned) 16, (int) 1, 1, 1, "},
{ 	GL_TEXTURE_3D, 	(int) 0, 	GL_RGBA4, 	(unsigned) 8, 	(unsigned) 8, 	(unsigned) 16, 	(int) 1, 	1, 	1, 
	"TexImage3DEXT_tab.GL_TEXTURE_3D, (int) 0, GL_RGBA4, (unsigned) 8, (unsigned) 8, (unsigned) 16, (int) 1, 1, 1, "},
{ 	GL_TEXTURE_3D, 	(int) 0, 	GL_RGB5_A1, 	(unsigned) 8, 	(unsigned) 8, 	(unsigned) 16, 	(int) 1, 	1, 	1, 
	"TexImage3DEXT_tab.GL_TEXTURE_3D, (int) 0, GL_RGB5_A1, (unsigned) 8, (unsigned) 8, (unsigned) 16, (int) 1, 1, 1, "},
{ 	GL_TEXTURE_3D, 	(int) 0, 	GL_RGBA8, 	(unsigned) 8, 	(unsigned) 8, 	(unsigned) 16, 	(int) 1, 	1, 	1, 
	"TexImage3DEXT_tab.GL_TEXTURE_3D, (int) 0, GL_RGBA8, (unsigned) 8, (unsigned) 8, (unsigned) 16, (int) 1, 1, 1, "},
{ 	GL_TEXTURE_3D, 	(int) 0, 	GL_RGB10_A2, 	(unsigned) 8, 	(unsigned) 8, 	(unsigned) 16, 	(int) 1, 	1, 	1, 
	"TexImage3DEXT_tab.GL_TEXTURE_3D, (int) 0, GL_RGB10_A2, (unsigned) 8, (unsigned) 8, (unsigned) 16, (int) 1, 1, 1, "},
{ 	GL_TEXTURE_3D, 	(int) 0, 	GL_RGBA12, 	(unsigned) 8, 	(unsigned) 8, 	(unsigned) 16, 	(int) 1, 	1, 	1, 
	"TexImage3DEXT_tab.GL_TEXTURE_3D, (int) 0, GL_RGBA12, (unsigned) 8, (unsigned) 8, (unsigned) 16, (int) 1, 1, 1, "},
{ 	GL_TEXTURE_3D, 	(int) 0, 	GL_RGBA16, 	(unsigned) 8, 	(unsigned) 8, 	(unsigned) 16, 	(int) 1, 	1, 	1, 
	"TexImage3DEXT_tab.GL_TEXTURE_3D, (int) 0, GL_RGBA16, (unsigned) 8, (unsigned) 8, (unsigned) 16, (int) 1, 1, 1, "},
{ 	GL_TEXTURE_3D, 	(int) 0, 	GL_ALPHA, 	(unsigned) 8, 	(unsigned) 8, 	(unsigned) 16, 	(int) 1, 	1, 	1, 
	"TexImage3DEXT_tab.GL_TEXTURE_3D, (int) 0, GL_ALPHA, (unsigned) 8, (unsigned) 8, (unsigned) 16, (int) 1, 1, 1, "},
{ 	GL_TEXTURE_3D, 	(int) 0, 	GL_ALPHA4, 	(unsigned) 8, 	(unsigned) 8, 	(unsigned) 16, 	(int) 1, 	1, 	1, 
	"TexImage3DEXT_tab.GL_TEXTURE_3D, (int) 0, GL_ALPHA4, (unsigned) 8, (unsigned) 8, (unsigned) 16, (int) 1, 1, 1, "},
{ 	GL_TEXTURE_3D, 	(int) 0, 	GL_ALPHA8, 	(unsigned) 8, 	(unsigned) 8, 	(unsigned) 16, 	(int) 1, 	1, 	1, 
	"TexImage3DEXT_tab.GL_TEXTURE_3D, (int) 0, GL_ALPHA8, (unsigned) 8, (unsigned) 8, (unsigned) 16, (int) 1, 1, 1, "},
{ 	GL_TEXTURE_3D, 	(int) 0, 	GL_ALPHA12, 	(unsigned) 8, 	(unsigned) 8, 	(unsigned) 16, 	(int) 1, 	1, 	1, 
	"TexImage3DEXT_tab.GL_TEXTURE_3D, (int) 0, GL_ALPHA12, (unsigned) 8, (unsigned) 8, (unsigned) 16, (int) 1, 1, 1, "},
{ 	GL_TEXTURE_3D, 	(int) 0, 	GL_ALPHA16, 	(unsigned) 8, 	(unsigned) 8, 	(unsigned) 16, 	(int) 1, 	1, 	1, 
	"TexImage3DEXT_tab.GL_TEXTURE_3D, (int) 0, GL_ALPHA16, (unsigned) 8, (unsigned) 8, (unsigned) 16, (int) 1, 1, 1, "},
{ 	GL_TEXTURE_3D, 	(int) 0, 	GL_LUMINANCE, 	(unsigned) 8, 	(unsigned) 8, 	(unsigned) 16, 	(int) 1, 	1, 	1, 
	"TexImage3DEXT_tab.GL_TEXTURE_3D, (int) 0, GL_LUMINANCE, (unsigned) 8, (unsigned) 8, (unsigned) 16, (int) 1, 1, 1, "},
{ 	GL_TEXTURE_3D, 	(int) 0, 	GL_LUMINANCE4, 	(unsigned) 8, 	(unsigned) 8, 	(unsigned) 16, 	(int) 1, 	1, 	1, 
	"TexImage3DEXT_tab.GL_TEXTURE_3D, (int) 0, GL_LUMINANCE4, (unsigned) 8, (unsigned) 8, (unsigned) 16, (int) 1, 1, 1, "},
{ 	GL_TEXTURE_3D, 	(int) 0, 	GL_LUMINANCE8, 	(unsigned) 8, 	(unsigned) 8, 	(unsigned) 16, 	(int) 1, 	1, 	1, 
	"TexImage3DEXT_tab.GL_TEXTURE_3D, (int) 0, GL_LUMINANCE8, (unsigned) 8, (unsigned) 8, (unsigned) 16, (int) 1, 1, 1, "},
{ 	GL_TEXTURE_3D, 	(int) 0, 	GL_LUMINANCE12, 	(unsigned) 8, 	(unsigned) 8, 	(unsigned) 16, 	(int) 1, 	1, 	1, 
	"TexImage3DEXT_tab.GL_TEXTURE_3D, (int) 0, GL_LUMINANCE12, (unsigned) 8, (unsigned) 8, (unsigned) 16, (int) 1, 1, 1, "},
{ 	GL_TEXTURE_3D, 	(int) 0, 	GL_LUMINANCE16, 	(unsigned) 8, 	(unsigned) 8, 	(unsigned) 16, 	(int) 1, 	1, 	1, 
	"TexImage3DEXT_tab.GL_TEXTURE_3D, (int) 0, GL_LUMINANCE16, (unsigned) 8, (unsigned) 8, (unsigned) 16, (int) 1, 1, 1, "},
{ 	GL_TEXTURE_3D, 	(int) 0, 	GL_LUMINANCE_ALPHA, 	(unsigned) 8, 	(unsigned) 8, 	(unsigned) 16, 	(int) 1, 	1, 	1, 
	"TexImage3DEXT_tab.GL_TEXTURE_3D, (int) 0, GL_LUMINANCE_ALPHA, (unsigned) 8, (unsigned) 8, (unsigned) 16, (int) 1, 1, 1, "},
{ 	GL_TEXTURE_3D, 	(int) 0, 	GL_LUMINANCE4_ALPHA4, 	(unsigned) 8, 	(unsigned) 8, 	(unsigned) 16, 	(int) 1, 	1, 	1, 
	"TexImage3DEXT_tab.GL_TEXTURE_3D, (int) 0, GL_LUMINANCE4_ALPHA4, (unsigned) 8, (unsigned) 8, (unsigned) 16, (int) 1, 1, 1, "},
{ 	GL_TEXTURE_3D, 	(int) 0, 	GL_LUMINANCE6_ALPHA2, 	(unsigned) 8, 	(unsigned) 8, 	(unsigned) 16, 	(int) 1, 	1, 	1, 
	"TexImage3DEXT_tab.GL_TEXTURE_3D, (int) 0, GL_LUMINANCE6_ALPHA2, (unsigned) 8, (unsigned) 8, (unsigned) 16, (int) 1, 1, 1, "},
{ 	GL_TEXTURE_3D, 	(int) 0, 	GL_LUMINANCE8_ALPHA8, 	(unsigned) 8, 	(unsigned) 8, 	(unsigned) 16, 	(int) 1, 	1, 	1, 
	"TexImage3DEXT_tab.GL_TEXTURE_3D, (int) 0, GL_LUMINANCE8_ALPHA8, (unsigned) 8, (unsigned) 8, (unsigned) 16, (int) 1, 1, 1, "},
{ 	GL_TEXTURE_3D, 	(int) 0, 	GL_LUMINANCE12_ALPHA4, 	(unsigned) 8, 	(unsigned) 8, 	(unsigned) 16, 	(int) 1, 	1, 	1, 
	"TexImage3DEXT_tab.GL_TEXTURE_3D, (int) 0, GL_LUMINANCE12_ALPHA4, (unsigned) 8, (unsigned) 8, (unsigned) 16, (int) 1, 1, 1, "},
{ 	GL_TEXTURE_3D, 	(int) 0, 	GL_LUMINANCE12_ALPHA12, 	(unsigned) 8, 	(unsigned) 8, 	(unsigned) 16, 	(int) 1, 	1, 	1, 
	"TexImage3DEXT_tab.GL_TEXTURE_3D, (int) 0, GL_LUMINANCE12_ALPHA12, (unsigned) 8, (unsigned) 8, (unsigned) 16, (int) 1, 1, 1, "},
{ 	GL_TEXTURE_3D, 	(int) 0, 	GL_LUMINANCE16_ALPHA16, 	(unsigned) 8, 	(unsigned) 8, 	(unsigned) 16, 	(int) 1, 	1, 	1, 
	"TexImage3DEXT_tab.GL_TEXTURE_3D, (int) 0, GL_LUMINANCE16_ALPHA16, (unsigned) 8, (unsigned) 8, (unsigned) 16, (int) 1, 1, 1, "},
{ 	GL_TEXTURE_3D, 	(int) 0, 	GL_INTENSITY, 	(unsigned) 8, 	(unsigned) 8, 	(unsigned) 16, 	(int) 1, 	1, 	1, 
	"TexImage3DEXT_tab.GL_TEXTURE_3D, (int) 0, GL_INTENSITY, (unsigned) 8, (unsigned) 8, (unsigned) 16, (int) 1, 1, 1, "},
{ 	GL_TEXTURE_3D, 	(int) 0, 	GL_INTENSITY4, 	(unsigned) 8, 	(unsigned) 8, 	(unsigned) 16, 	(int) 1, 	1, 	1, 
	"TexImage3DEXT_tab.GL_TEXTURE_3D, (int) 0, GL_INTENSITY4, (unsigned) 8, (unsigned) 8, (unsigned) 16, (int) 1, 1, 1, "},
{ 	GL_TEXTURE_3D, 	(int) 0, 	GL_INTENSITY8, 	(unsigned) 8, 	(unsigned) 8, 	(unsigned) 16, 	(int) 1, 	1, 	1, 
	"TexImage3DEXT_tab.GL_TEXTURE_3D, (int) 0, GL_INTENSITY8, (unsigned) 8, (unsigned) 8, (unsigned) 16, (int) 1, 1, 1, "},
{ 	GL_TEXTURE_3D, 	(int) 0, 	GL_INTENSITY12, 	(unsigned) 8, 	(unsigned) 8, 	(unsigned) 16, 	(int) 1, 	1, 	1, 
	"TexImage3DEXT_tab.GL_TEXTURE_3D, (int) 0, GL_INTENSITY12, (unsigned) 8, (unsigned) 8, (unsigned) 16, (int) 1, 1, 1, "},
{ 	GL_TEXTURE_3D, 	(int) 0, 	GL_INTENSITY16, 	(unsigned) 8, 	(unsigned) 8, 	(unsigned) 16, 	(int) 1, 	1, 	1, 
	"TexImage3DEXT_tab.GL_TEXTURE_3D, (int) 0, GL_INTENSITY16, (unsigned) 8, (unsigned) 8, (unsigned) 16, (int) 1, 1, 1, "},
{ 	GL_TEXTURE_3D, 	(int) 0, 	GL_R3_G3_B2, 	(unsigned) 8, 	(unsigned) 8, 	(unsigned) 16, 	(int) 1, 	1, 	1, 
	"TexImage3DEXT_tab.GL_TEXTURE_3D, (int) 0, GL_R3_G3_B2, (unsigned) 8, (unsigned) 8, (unsigned) 16, (int) 1, 1, 1, "},
{ 	GL_TEXTURE_3D, 	(int) 0, 	GL_RGB, 	(unsigned) 8, 	(unsigned) 8, 	(unsigned) 16, 	(int) 1, 	1, 	1, 
	"TexImage3DEXT_tab.GL_TEXTURE_3D, (int) 0, GL_RGB, (unsigned) 8, (unsigned) 8, (unsigned) 16, (int) 1, 1, 1, "},
{ 	GL_TEXTURE_3D, 	(int) 0, 	GL_RGB4, 	(unsigned) 8, 	(unsigned) 8, 	(unsigned) 16, 	(int) 1, 	1, 	1, 
	"TexImage3DEXT_tab.GL_TEXTURE_3D, (int) 0, GL_RGB4, (unsigned) 8, (unsigned) 8, (unsigned) 16, (int) 1, 1, 1, "},
{ 	GL_TEXTURE_3D, 	(int) 0, 	GL_RGB5, 	(unsigned) 8, 	(unsigned) 8, 	(unsigned) 16, 	(int) 1, 	1, 	1, 
	"TexImage3DEXT_tab.GL_TEXTURE_3D, (int) 0, GL_RGB5, (unsigned) 8, (unsigned) 8, (unsigned) 16, (int) 1, 1, 1, "},
{ 	GL_TEXTURE_3D, 	(int) 0, 	GL_RGB8, 	(unsigned) 8, 	(unsigned) 8, 	(unsigned) 16, 	(int) 1, 	1, 	1, 
	"TexImage3DEXT_tab.GL_TEXTURE_3D, (int) 0, GL_RGB8, (unsigned) 8, (unsigned) 8, (unsigned) 16, (int) 1, 1, 1, "},
{ 	GL_TEXTURE_3D, 	(int) 0, 	GL_RGB10, 	(unsigned) 8, 	(unsigned) 8, 	(unsigned) 16, 	(int) 1, 	1, 	1, 
	"TexImage3DEXT_tab.GL_TEXTURE_3D, (int) 0, GL_RGB10, (unsigned) 8, (unsigned) 8, (unsigned) 16, (int) 1, 1, 1, "},
{ 	GL_TEXTURE_3D, 	(int) 0, 	GL_RGB12, 	(unsigned) 8, 	(unsigned) 8, 	(unsigned) 16, 	(int) 1, 	1, 	1, 
	"TexImage3DEXT_tab.GL_TEXTURE_3D, (int) 0, GL_RGB12, (unsigned) 8, (unsigned) 8, (unsigned) 16, (int) 1, 1, 1, "},
{ 	GL_TEXTURE_3D, 	(int) 0, 	GL_RGB16, 	(unsigned) 8, 	(unsigned) 8, 	(unsigned) 16, 	(int) 1, 	1, 	1, 
	"TexImage3DEXT_tab.GL_TEXTURE_3D, (int) 0, GL_RGB16, (unsigned) 8, (unsigned) 8, (unsigned) 16, (int) 1, 1, 1, "},
{ 	GL_TEXTURE_3D, 	(int) 0, 	GL_RGBA, 	(unsigned) 8, 	(unsigned) 8, 	(unsigned) 16, 	(int) 1, 	1, 	1, 
	"TexImage3DEXT_tab.GL_TEXTURE_3D, (int) 0, GL_RGBA, (unsigned) 8, (unsigned) 8, (unsigned) 16, (int) 1, 1, 1, "},
{ 	GL_TEXTURE_3D, 	(int) 0, 	GL_RGBA2, 	(unsigned) 8, 	(unsigned) 8, 	(unsigned) 16, 	(int) 1, 	1, 	1, 
	"TexImage3DEXT_tab.GL_TEXTURE_3D, (int) 0, GL_RGBA2, (unsigned) 8, (unsigned) 8, (unsigned) 16, (int) 1, 1, 1, "},
{ 	GL_TEXTURE_3D, 	(int) 0, 	GL_RGBA4, 	(unsigned) 8, 	(unsigned) 8, 	(unsigned) 16, 	(int) 1, 	1, 	1, 
	"TexImage3DEXT_tab.GL_TEXTURE_3D, (int) 0, GL_RGBA4, (unsigned) 8, (unsigned) 8, (unsigned) 16, (int) 1, 1, 1, "},
{ 	GL_TEXTURE_3D, 	(int) 0, 	GL_RGB5_A1, 	(unsigned) 8, 	(unsigned) 8, 	(unsigned) 16, 	(int) 1, 	1, 	1, 
	"TexImage3DEXT_tab.GL_TEXTURE_3D, (int) 0, GL_RGB5_A1, (unsigned) 8, (unsigned) 8, (unsigned) 16, (int) 1, 1, 1, "},
{ 	GL_TEXTURE_3D, 	(int) 0, 	GL_RGBA8, 	(unsigned) 8, 	(unsigned) 8, 	(unsigned) 16, 	(int) 1, 	1, 	1, 
	"TexImage3DEXT_tab.GL_TEXTURE_3D, (int) 0, GL_RGBA8, (unsigned) 8, (unsigned) 8, (unsigned) 16, (int) 1, 1, 1, "},
{ 	GL_TEXTURE_3D, 	(int) 0, 	GL_RGB10_A2, 	(unsigned) 8, 	(unsigned) 8, 	(unsigned) 16, 	(int) 1, 	1, 	1, 
	"TexImage3DEXT_tab.GL_TEXTURE_3D, (int) 0, GL_RGB10_A2, (unsigned) 8, (unsigned) 8, (unsigned) 16, (int) 1, 1, 1, "},
{ 	GL_TEXTURE_3D, 	(int) 0, 	GL_RGBA12, 	(unsigned) 8, 	(unsigned) 8, 	(unsigned) 16, 	(int) 1, 	1, 	1, 
	"TexImage3DEXT_tab.GL_TEXTURE_3D, (int) 0, GL_RGBA12, (unsigned) 8, (unsigned) 8, (unsigned) 16, (int) 1, 1, 1, "},
{ 	GL_TEXTURE_3D, 	(int) 0, 	GL_RGBA16, 	(unsigned) 8, 	(unsigned) 8, 	(unsigned) 16, 	(int) 1, 	1, 	1, 
	"TexImage3DEXT_tab.GL_TEXTURE_3D, (int) 0, GL_RGBA16, (unsigned) 8, (unsigned) 8, (unsigned) 16, (int) 1, 1, 1, "},
};

/* COUNT = 38 */
void crPackTestTexImage3DEXT(void)
{
	int i;
	GLubyte pixels[100000];/* VECP2 */
	for ( i = 0; i < 38; i++) {
	if (verbose)
		crDebug("glTexImage3DEXT( %s )",TexImage3DEXT_tab[i].prgstr);
		glTexImage3DEXT(	TexImage3DEXT_tab[i].TexImage3DEXT_target, 	TexImage3DEXT_tab[i].TexImage3DEXT_level, 	TexImage3DEXT_tab[i].TexImage3DEXT_internalFormat, 	TexImage3DEXT_tab[i].TexImage3DEXT_width, 	TexImage3DEXT_tab[i].TexImage3DEXT_height, 	TexImage3DEXT_tab[i].TexImage3DEXT_depth, 	TexImage3DEXT_tab[i].TexImage3DEXT_border, 	TexImage3DEXT_tab[i].TexImage3DEXT_format, 	TexImage3DEXT_tab[i].TexImage3DEXT_type, pixels /* VECS2 */
);
		if(errChk)
			printError("gl(TexImage3DEXT)");
	}
}
