# Copyright (c) 2001, Stanford University
# All rights reserved.
#
# See the file LICENSE.txt for information on redistributing this software.

import sys

sys.path.append( "../../glapi_parser" )
import apiutil


keys = apiutil.GetDispatchedFunctions("../../glapi_parser/APIspec.txt")

apiutil.CopyrightC()

print """
/* DO NOT EDIT - THIS FILE GENERATED BY THE tilesortspu_proto.py SCRIPT */

#ifndef TILESORT_SPU_PROTO_H
#define TILESORT_SPU_PROTO_H 1

#include <stdio.h>
#include "cr_string.h"
#include "cr_spu.h"
#include "tilesortspu.h"
#include "cr_packfunctions.h"
#include "cr_glstate.h"
"""


for func_name in keys:
	return_type = apiutil.ReturnType(func_name)
	params = apiutil.Parameters(func_name)
	if apiutil.FindSpecial( "tilesort_unimplemented", func_name ):
		print 'extern %s TILESORTSPU_APIENTRY tilesortspu_%s( %s );' % ( return_type, func_name, apiutil.MakeDeclarationString(params) )
	if apiutil.FindSpecial( "tilesort", func_name ):
		print 'extern %s TILESORTSPU_APIENTRY tilesortspu_%s( %s );' % ( return_type, func_name, apiutil.MakeDeclarationString(params) )


print """
#endif
"""
