# Copyright (c) 2001, Stanford University
# All rights reserved.
#
# See the file LICENSE.txt for information on redistributing this software.

import sys,os;
import cPickle;
import string;
import re;

sys.path.append( "../../opengl_stub" )
parsed_file = open( "../../glapi_parser/gl_header.parsed", "rb" )
gl_mapping = cPickle.load( parsed_file )

import stub_common;

keys = gl_mapping.keys()
keys.sort();

stub_common.CopyrightC()

print """/* DO NOT EDIT - AUTOMATICALLY GENERATED BY packspu_beginend.py */
#include "packspu.h"
#include "assert.h"
#include "cr_packfunctions.h"
#include "packspu_proto.h"

void PACKSPU_APIENTRY packspu_Begin( GLenum mode )
{
	GET_THREAD(thread);
	CRPackBuffer *buf = &thread->BeginEndBuffer;

	CRASSERT( mode >= GL_POINTS && mode <= GL_POLYGON );

	if (pack_spu.swap)
	{
		crPackBeginSWAP( mode );
	}
	else
	{
		crPackBegin( mode );
	}

	if ( thread->server.conn->Barf ) {
		thread->BeginEndMode = mode;
		thread->BeginEndState = -1;
		if ( mode == GL_LINES || mode == GL_TRIANGLES || mode == GL_QUADS || mode == GL_POLYGON )
		{
			CRASSERT(!buf->pack);
			crPackGetBuffer( thread->packer, &thread->normBuffer );
			buf->pack = crNetAlloc( thread->server.conn );
			crPackInitBuffer( buf, buf->pack, thread->server.conn->buffer_size, thread->server.conn->mtu );
			buf->holds_BeginEnd = 1;
			buf->in_BeginEnd = 1;
			crPackSetBuffer( thread->packer, buf );

			thread->BeginEndState = 0;
		}
	}
}

void PACKSPU_APIENTRY packspu_End( void )
{
	GET_THREAD(thread);
	CRPackBuffer *buf = &thread->BeginEndBuffer;

	if ( thread->server.conn->Barf &&
		(thread->BeginEndMode == GL_LINES
		|| thread->BeginEndMode == GL_TRIANGLES
		|| thread->BeginEndMode == GL_QUADS
		|| thread->BeginEndMode == GL_POLYGON ) )
	{
		CRASSERT(buf->pack);

		crPackGetBuffer( thread->packer, buf );
		crPackSetBuffer( thread->packer, &thread->normBuffer );
		if ( !crPackCanHoldBuffer( buf ) )
			packspuFlush( (void *) thread );

		crPackAppendBuffer( buf );
		crNetFree( thread->server.conn, buf->pack );
		buf->pack = NULL;
	}

	if (pack_spu.swap)
	{
		crPackEndSWAP();
	}
	else
	{
		crPackEnd();
	}
}

static void DoVertex( void )
{
	GET_THREAD(thread);
	CRPackBuffer *buf = &thread->BeginEndBuffer;
	CRPackBuffer *gbuf = &thread->normBuffer;
	int num_data;
	int num_opcode;

	/*crDebug( "really doing Vertex" );*/
	crPackGetBuffer( thread->packer, buf );
	num_data = buf->data_current - buf->data_start;
	num_opcode = buf->opcode_start - buf->opcode_current;
	crPackSetBuffer( thread->packer, gbuf );
	if ( !crPackCanHoldBuffer( buf ) )
		/* doesn't hold, first flush gbuf*/
		packspuFlush( (void *) thread );

	crPackAppendBuffer( buf );
	crPackGetBuffer( thread->packer, gbuf );
	crPackSetBuffer( thread->packer, buf );
	crPackResetPointers(thread->packer);
}

static void RunState( void )
{
	GET_THREAD(thread);
	if (! thread->server.conn->Barf ) return;
	if (thread->BeginEndState == -1) return;
	switch(thread->BeginEndMode) {
	case GL_POLYGON:
		return;
	case GL_LINES:
		if ((thread->BeginEndState + 1) % 2)
		{
			thread->BeginEndState = (thread->BeginEndState + 1) % 2;
			return;
		}
		break;
	case GL_TRIANGLES:
		if ((thread->BeginEndState + 1) % 3)
		{
			thread->BeginEndState = (thread->BeginEndState + 1) % 3;
			return;
		}
		break;
	case GL_QUADS:
		if ((thread->BeginEndState + 1) % 4)
		{
			thread->BeginEndState = (thread->BeginEndState + 1) % 4;
			return;
		}
		break;
	}
	DoVertex();
}
"""

for func_name in stub_common.AllSpecials( "packspu_vertex" ):
	(return_type, args, types) = gl_mapping[func_name]
	print 'void PACKSPU_APIENTRY packspu_%s%s' % ( func_name, stub_common.ArgumentString( args, types ) )
	print '{'
	print '\tif (pack_spu.swap)'
	print '\t{'
	print '\t\tcrPack%sSWAP%s;' % ( func_name, stub_common.CallString( args ) )
	print '\t}'
	print '\telse'
	print '\t{'
	print '\t\tcrPack%s%s;' % ( func_name, stub_common.CallString( args ) )
	print '\t}'
	print '\tRunState();'
	print '}'
