# Copyright (c) 2001, Stanford University
# All rights reserved.
#
# See the file LICENSE.txt for information on redistributing this software.

TOP = ../..

PROGRAM = nullapp
OPENGL = 1
GLUT = 1
MATH = 1

FILES = nullapp

include ${TOP}/cr.mk
