# Copyright (c) 2001, Stanford University
# All rights reserved.
#
# See the file LICENSE.txt for information on redistributing this software.

TOP = ..

include $(TOP)/arch.mk

PROGRAM = crserver
FILES = main

UNPACKS = 1

LIBRARIES = crserverlib spuload crmothership crstate crpacker crutil

include $(TOP)/cr.mk
