# Copyright (c) 2001, Stanford University
# All rights reserved.
#
# See the file LICENSE.txt for information on redistributing this software.

TOP = ../..

PROGRAM = sputest
FILES = sputest

LIBRARIES = spuload crutil crmothership

include $(TOP)/cr.mk
