# Copyright (c) 2001, Stanford University
# All rights reserved.
#
# See the file LICENSE.txt for information on redistributing this software.

TOP = ../..

PROGRAM = psubmit_crut
FILES = psubmit_crut
MATH = 1

LIBRARIES =  crutil crfaker crmothership spuload crutapi crutclientapi glut GLU X11 Xi Xext Xmu

include ${TOP}/cr.mk
