# Copyright (c) 2001, Stanford University
# All rights reserved.
#
# See the file LICENSE.txt for information on redistributing this software.

TOP = ../..

PROGRAM = spheres
FILES = spheres
MATH = 1

LIBRARIES = crutil crfaker crmothership spuload

include ${TOP}/cr.mk
