# Copyright (c) 2001, Stanford University
# All rights reserved.
#
# See the file LICENSE.txt for information on redistributing this software.

TOP = ../../..

PROGRAM = kirchner_material
OPENGL = 1
GLUT = 1

FILES = bug

include ${TOP}/cr.mk
