# Copyright (c) 2001, Stanford University
# All rights reserved.
#
# See the file LICENSE.txt for information on redistributing this software.

TOP = ../..

PROGRAM = plyview
FILES = ball plyfile pmodel readply
#MPI = 1
OPENGL=1
GLUT=1

LIBRARIES = crutil

include ${TOP}/cr.mk
