# Written by Dale Beermann (beermann@cs.virginia.edu)

TOP = ..
FILES = crutclientapi

SHARED = 1
LIBRARY = crutclientapi
LIBRARIES = crutapi crfaker crmothership crutil
LIB_DEFS = crutclientapi.def

include $(TOP)/cr.mk
