# Copyright (c) 2001, Stanford University
# All rights reserved.
#
# See the file LICENSE.txt for information on redistributing this software.

TOP = ../../..

PROGRAM = npserver
FILES = npserver

LIBRARIES = crmothership crutil

include $(TOP)/cr.mk
