# Written by Dale Beermann (beermann@cs.virginia.edu) 

TOP = ..

PROGRAM = crutserver
FILES = main \

PRECOMP = 
SLOP = ${PRECOMP}

OPENGL = 1
GLUT = 1
MATH = 1

LIBRARIES = crmothership crutil crutapi

include $(TOP)/cr.mk
