# Written by Dale Beermann (beermann@cs.virginia.edu) 

TOP = ..

PROGRAM = crutserver
FILES = main \

PRECOMP = 
SLOP = ${PRECOMP}

ifndef WINDOWS
LIBRARIES = crutil crmothership crutapi X11 Xi Xext Xmu GL GLU glut
endif

include $(TOP)/cr.mk
