# Copyright (c) 2001, Stanford University
# All rights reserved.
#
# See the file LICENSE.txt for information on redistributing this software.

TOP = ../..

SUBDIRS = colormaterial_bug material_bug

include ${TOP}/cr.mk
